
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class Trainingcenter1Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7420, -10, -11, 0}, {7419, -11, -11, 0}, {7421, -9, -11, 0}// 100	101	102	
			, {7422, -8, -11, 0}, {7423, -7, -11, 0}, {7421, 0, -11, 0}// 103	104	105	
			, {7419, -2, -11, 0}, {7420, -1, -11, 0}, {7422, 1, -11, 0}// 106	107	108	
			, {7423, 2, -11, 0}, {7409, -8, -6, 0}, {7410, -9, -6, 0}// 109	366	367	
			, {7411, -10, -6, 0}, {7412, -11, -6, 0}, {7418, -11, -10, 0}// 368	369	370	
			, {7424, -7, -10, 0}, {7425, -7, -9, 0}, {7426, -7, -8, 0}// 371	372	373	
			, {7427, -7, -7, 0}, {7428, -8, -7, 0}, {7429, -9, -7, 0}// 374	375	376	
			, {7430, -10, -7, 0}, {7431, -11, -7, 0}, {7432, -11, -8, 0}// 377	378	379	
			, {7433, -11, -9, 0}, {7434, -10, -10, 0}, {7435, -9, -10, 0}// 380	381	382	
			, {7436, -8, -10, 0}, {7437, -8, -9, 0}, {7438, -8, -8, 0}// 383	384	385	
			, {7442, -9, -9, 0}, {7441, -10, -9, 0}, {7440, -10, -8, 0}// 386	387	388	
			, {7439, -9, -8, 0}, {7409, 1, -6, 0}, {7410, 0, -6, 0}// 389	390	391	
			, {7411, -1, -6, 0}, {7412, -2, -6, 0}, {7413, -3, -6, 0}// 392	393	394	
			, {7414, -3, -7, 0}, {7415, -3, -8, 0}, {7416, -3, -9, 0}// 395	396	397	
			, {7417, -3, -10, 0}, {7418, -2, -10, 0}, {7424, 2, -10, 0}// 398	399	400	
			, {7425, 2, -9, 0}, {7426, 2, -8, 0}, {7427, 2, -7, 0}// 401	402	403	
			, {7428, 1, -7, 0}, {7429, 0, -7, 0}, {7430, -1, -7, 0}// 404	405	406	
			, {7431, -2, -7, 0}, {7432, -2, -8, 0}, {7433, -2, -9, 0}// 407	408	409	
			, {7434, -1, -10, 0}, {7435, 0, -10, 0}, {7436, 1, -10, 0}// 410	411	412	
			, {7437, 1, -9, 0}, {7438, 1, -8, 0}, {7442, 0, -9, 0}// 413	414	415	
			, {7441, -1, -9, 0}, {7440, -1, -8, 0}, {7439, 0, -8, 0}// 416	417	418	
			, {7413, -12, -6, 0}, {7414, -12, -7, 0}, {7415, -12, -8, 0}// 419	420	421	
			, {7416, -12, -9, 0}, {7417, -12, -10, 0}, {7409, -8, 11, 0}// 422	423	562	
			, {7410, -9, 11, 0}, {7411, -10, 11, 0}, {7412, -11, 11, 0}// 563	564	565	
			, {7413, -12, 11, 0}, {7414, -12, 10, 0}, {7415, -12, 9, 0}// 566	567	568	
			, {7416, -12, 8, 0}, {7417, -12, 7, 0}, {7418, -11, 7, 0}// 569	570	571	
			, {7419, -11, 6, 0}, {7420, -10, 6, 0}, {7421, -9, 6, 0}// 572	573	574	
			, {7422, -8, 6, 0}, {7423, -7, 6, 0}, {7424, -7, 7, 0}// 575	576	577	
			, {7425, -7, 8, 0}, {7426, -7, 9, 0}, {7427, -7, 10, 0}// 578	579	580	
			, {7428, -8, 10, 0}, {7429, -9, 10, 0}, {7430, -10, 10, 0}// 581	582	583	
			, {7431, -11, 10, 0}, {7432, -11, 9, 0}, {7433, -11, 8, 0}// 584	585	586	
			, {7434, -10, 7, 0}, {7435, -9, 7, 0}, {7436, -8, 7, 0}// 587	588	589	
			, {7437, -8, 8, 0}, {7438, -8, 9, 0}, {7442, -9, 8, 0}// 590	591	592	
			, {7441, -10, 8, 0}, {7440, -10, 9, 0}, {7439, -9, 9, 0}// 593	594	595	
			, {7409, 1, 11, 0}, {7410, 0, 11, 0}, {7411, -1, 11, 0}// 596	597	598	
			, {7412, -2, 11, 0}, {7413, -3, 11, 0}, {7414, -3, 10, 0}// 599	600	601	
			, {7415, -3, 9, 0}, {7416, -3, 8, 0}, {7417, -3, 7, 0}// 602	603	604	
			, {7418, -2, 7, 0}, {7419, -2, 6, 0}, {7420, -1, 6, 0}// 605	606	607	
			, {7421, 0, 6, 0}, {7422, 1, 6, 0}, {7423, 2, 6, 0}// 608	609	610	
			, {7424, 2, 7, 0}, {7425, 2, 8, 0}, {7426, 2, 9, 0}// 611	612	613	
			, {7427, 2, 10, 0}, {7428, 1, 10, 0}, {7429, 0, 10, 0}// 614	615	616	
			, {7430, -1, 10, 0}, {7431, -2, 10, 0}, {7432, -2, 9, 0}// 617	618	619	
			, {7433, -2, 8, 0}, {7434, -1, 7, 0}, {7435, 0, 7, 0}// 620	621	622	
			, {7436, 1, 7, 0}, {7437, 1, 8, 0}, {7438, 1, 9, 0}// 623	624	625	
			, {7442, 0, 8, 0}, {7441, -1, 8, 0}, {7440, -1, 9, 0}// 626	627	628	
			, {7439, 0, 9, 0}, {7420, 8, -11, 0}, {7419, 7, -11, 0}// 629	662	663	
			, {7421, 9, -11, 0}, {7422, 10, -11, 0}, {7423, 11, -11, 0}// 664	665	666	
			, {7409, 10, -6, 0}, {7410, 9, -6, 0}, {7411, 8, -6, 0}// 835	836	837	
			, {7412, 7, -6, 0}, {7413, 6, -6, 0}, {7414, 6, -7, 0}// 838	839	840	
			, {7415, 6, -8, 0}, {7416, 6, -9, 0}, {7417, 6, -10, 0}// 841	842	843	
			, {7418, 7, -10, 0}, {7424, 11, -10, 0}, {7425, 11, -9, 0}// 844	845	846	
			, {7426, 11, -8, 0}, {7427, 11, -7, 0}, {7428, 10, -7, 0}// 847	848	849	
			, {7429, 9, -7, 0}, {7430, 8, -7, 0}, {7431, 7, -7, 0}// 850	851	852	
			, {7432, 7, -8, 0}, {7433, 7, -9, 0}, {7434, 8, -10, 0}// 853	854	855	
			, {7435, 9, -10, 0}, {7436, 10, -10, 0}, {7437, 10, -9, 0}// 856	857	858	
			, {7438, 10, -8, 0}, {7442, 9, -9, 0}, {7441, 8, -9, 0}// 859	860	861	
			, {7440, 8, -8, 0}, {7439, 9, -8, 0}, {7409, 10, 11, 0}// 862	863	952	
			, {7410, 9, 11, 0}, {7411, 8, 11, 0}, {7412, 7, 11, 0}// 953	954	955	
			, {7413, 6, 11, 0}, {7414, 6, 10, 0}, {7415, 6, 9, 0}// 956	957	958	
			, {7416, 6, 8, 0}, {7417, 6, 7, 0}, {7418, 7, 7, 0}// 959	960	961	
			, {7419, 7, 6, 0}, {7420, 8, 6, 0}, {7421, 9, 6, 0}// 962	963	964	
			, {7422, 10, 6, 0}, {7423, 11, 6, 0}, {7424, 11, 7, 0}// 965	966	967	
			, {7425, 11, 8, 0}, {7426, 11, 9, 0}, {7427, 11, 10, 0}// 968	969	970	
			, {7428, 10, 10, 0}, {7429, 9, 10, 0}, {7430, 8, 10, 0}// 971	972	973	
			, {7431, 7, 10, 0}, {7432, 7, 9, 0}, {7433, 7, 8, 0}// 974	975	976	
			, {7434, 8, 7, 0}, {7435, 9, 7, 0}, {7436, 10, 7, 0}// 977	978	979	
			, {7437, 10, 8, 0}, {7438, 10, 9, 0}, {7442, 9, 8, 0}// 980	981	982	
			, {7441, 8, 8, 0}, {7440, 8, 9, 0}, {7439, 9, 9, 0}// 983	984	985	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new Trainingcenter1AddonDeed();
			}
		}

		[ Constructable ]
		public Trainingcenter1Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1304, -13, -12, 0, 1083, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1304, -13, -11, 0, 1083, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 128, -13, -12, 0, 1083, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 128, -13, -11, 0, 1083, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1304, -13, -10, 0, 1083, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1304, -13, -9, 0, 1083, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1304, -13, -8, 0, 1083, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1304, -13, -7, 0, 1083, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1304, -13, -6, 0, 1083, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1304, -13, -5, 0, 1083, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1304, -13, -4, 0, 1083, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1304, -13, -3, 0, 1083, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1304, -13, -2, 0, 1083, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1304, -13, -1, 0, 1083, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1304, -13, 0, 0, 1083, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1304, -13, 1, 0, 1083, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1304, -13, 2, 0, 1083, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1304, -13, 3, 0, 1083, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1304, -13, 4, 0, 1083, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1304, -13, 5, 0, 1083, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 128, -13, -10, 0, 1083, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 128, -13, -9, 0, 1083, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 128, -13, -8, 0, 1083, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 128, -13, -7, 0, 1083, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 128, -13, -6, 0, 1083, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 128, -13, -5, 0, 1083, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 128, -13, -4, 0, 1083, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 128, -13, -3, 0, 1083, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 128, -13, -2, 0, 1083, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 128, -13, -1, 0, 1083, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 128, -13, 0, 0, 1083, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 128, -13, 1, 0, 1083, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 128, -13, 2, 0, 1083, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 128, -13, 3, 0, 1083, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 128, -13, 4, 0, 1083, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 128, -13, 5, 0, 1083, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1304, -13, 6, 0, 1083, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1304, -13, 7, 0, 1083, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 1304, -13, 8, 0, 1083, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 1304, -13, 9, 0, 1083, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 1304, -13, 10, 0, 1083, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 1304, -13, 11, 0, 1083, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1304, -13, 12, 0, 1083, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 128, -13, 12, 0, 1083, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 128, -13, 6, 0, 1083, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 128, -13, 7, 0, 1083, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 128, -13, 8, 0, 1083, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 128, -13, 9, 0, 1083, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 128, -13, 10, 0, 1083, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 128, -13, 11, 0, 1083, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 128, -13, 12, 0, 1083, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 1304, -12, -12, 0, 1083, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 1304, -12, -11, 0, 1083, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 1304, -11, -12, 0, 1083, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 1304, -11, -11, 0, 1083, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 1304, -10, -12, 0, 1083, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 1304, -10, -11, 0, 1083, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 1304, -9, -12, 0, 1083, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 1304, -9, -11, 0, 1083, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 1304, -8, -12, 0, 1083, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 1304, -8, -11, 0, 1083, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1304, -7, -12, 0, 1083, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 1304, -7, -11, 0, 1083, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 1304, -6, -12, 0, 1083, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 1304, -6, -11, 0, 1083, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 1304, -5, -12, 0, 1083, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 1304, -5, -11, 0, 1083, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 1304, -4, -12, 0, 1083, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 1304, -4, -11, 0, 1083, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 1304, -3, -12, 0, 1083, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 1304, -3, -11, 0, 1083, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 1304, -2, -12, 0, 1083, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 1304, -2, -11, 0, 1083, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 1304, -1, -12, 0, 1083, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 1304, -1, -11, 0, 1083, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 1304, 0, -12, 0, 1083, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 1304, 0, -11, 0, 1083, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 1304, 1, -12, 0, 1083, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 1304, 1, -11, 0, 1083, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 1304, 2, -12, 0, 1083, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 1304, 2, -11, 0, 1083, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 1304, 3, -12, 0, 1083, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 1304, 3, -11, 0, 1083, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 128, -12, -12, 0, 1083, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 128, -11, -12, 0, 1083, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 128, -10, -12, 0, 1083, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 128, -9, -12, 0, 1083, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 128, -8, -12, 0, 1083, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 128, -7, -12, 0, 1083, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 128, -6, -12, 0, 1083, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 128, -5, -12, 0, 1083, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 128, -4, -12, 0, 1083, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 128, -3, -12, 0, 1083, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 128, -2, -12, 0, 1083, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 128, -1, -12, 0, 1083, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 128, 0, -12, 0, 1083, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 128, 1, -12, 0, 1083, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 128, 2, -12, 0, 1083, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 128, 3, -12, 0, 1083, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 1304, -12, -10, 0, 1083, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 1304, -12, -9, 0, 1083, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 1304, -12, -8, 0, 1083, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 1304, -12, -7, 0, 1083, -1, "", 1);// 113
			AddComplexComponent( (BaseAddon) this, 1304, -12, -6, 0, 1083, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 1304, -12, -5, 0, 1083, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 1304, -12, -4, 0, 1083, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 1304, -12, -3, 0, 1083, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 1304, -12, -2, 0, 1083, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 1304, -12, -1, 0, 1083, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 1304, -12, 0, 0, 1083, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 1304, -12, 1, 0, 1083, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 1304, -12, 2, 0, 1083, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 1304, -12, 3, 0, 1083, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 1304, -12, 4, 0, 1083, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 1304, -12, 5, 0, 1083, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 1304, -11, -10, 0, 1083, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 1304, -11, -9, 0, 1083, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 1304, -11, -8, 0, 1083, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 1304, -11, -7, 0, 1083, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 1304, -11, -6, 0, 1083, -1, "", 1);// 130
			AddComplexComponent( (BaseAddon) this, 1304, -11, -5, 0, 1083, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 1304, -11, -4, 0, 1083, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 1304, -11, -3, 0, 1083, -1, "", 1);// 133
			AddComplexComponent( (BaseAddon) this, 1304, -11, -2, 0, 1083, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 1304, -11, -1, 0, 1083, -1, "", 1);// 135
			AddComplexComponent( (BaseAddon) this, 1304, -11, 0, 0, 1083, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 1304, -11, 1, 0, 1083, -1, "", 1);// 137
			AddComplexComponent( (BaseAddon) this, 1304, -11, 2, 0, 1083, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 1304, -11, 3, 0, 1083, -1, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 1304, -11, 4, 0, 1083, -1, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 1304, -11, 5, 0, 1083, -1, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 1304, -10, -10, 0, 1083, -1, "", 1);// 142
			AddComplexComponent( (BaseAddon) this, 1304, -10, -9, 0, 1083, -1, "", 1);// 143
			AddComplexComponent( (BaseAddon) this, 1304, -10, -8, 0, 1083, -1, "", 1);// 144
			AddComplexComponent( (BaseAddon) this, 1304, -10, -7, 0, 1083, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 1304, -10, -6, 0, 1083, -1, "", 1);// 146
			AddComplexComponent( (BaseAddon) this, 1304, -10, -5, 0, 1083, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 1304, -10, -4, 0, 1083, -1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 1304, -10, -3, 0, 1083, -1, "", 1);// 149
			AddComplexComponent( (BaseAddon) this, 1304, -10, -2, 0, 1083, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 1304, -10, -1, 0, 1083, -1, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 1304, -10, 0, 0, 1083, -1, "", 1);// 152
			AddComplexComponent( (BaseAddon) this, 1304, -10, 1, 0, 1083, -1, "", 1);// 153
			AddComplexComponent( (BaseAddon) this, 1304, -10, 2, 0, 1083, -1, "", 1);// 154
			AddComplexComponent( (BaseAddon) this, 1304, -10, 3, 0, 1083, -1, "", 1);// 155
			AddComplexComponent( (BaseAddon) this, 1304, -10, 4, 0, 1083, -1, "", 1);// 156
			AddComplexComponent( (BaseAddon) this, 1304, -10, 5, 0, 1083, -1, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 1304, -9, -10, 0, 1083, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 1304, -9, -9, 0, 1083, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 1304, -9, -8, 0, 1083, -1, "", 1);// 160
			AddComplexComponent( (BaseAddon) this, 1304, -9, -7, 0, 1083, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 1304, -9, -6, 0, 1083, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 1304, -9, -5, 0, 1083, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 1304, -9, -4, 0, 1083, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 1304, -9, -3, 0, 1083, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 1304, -9, -2, 0, 1083, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 1304, -9, -1, 0, 1083, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 1304, -9, 0, 0, 1083, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 1304, -9, 1, 0, 1083, -1, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 1304, -9, 2, 0, 1083, -1, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 1304, -9, 3, 0, 1083, -1, "", 1);// 171
			AddComplexComponent( (BaseAddon) this, 1304, -9, 4, 0, 1083, -1, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 1304, -9, 5, 0, 1083, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 1304, -8, -10, 0, 1083, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 1304, -8, -9, 0, 1083, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 1304, -8, -8, 0, 1083, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 1304, -8, -7, 0, 1083, -1, "", 1);// 177
			AddComplexComponent( (BaseAddon) this, 1304, -8, -6, 0, 1083, -1, "", 1);// 178
			AddComplexComponent( (BaseAddon) this, 1304, -8, -5, 0, 1083, -1, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 1304, -8, -4, 0, 1083, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 1304, -8, -3, 0, 1083, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 1304, -8, -2, 0, 1083, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 1304, -8, -1, 0, 1083, -1, "", 1);// 183
			AddComplexComponent( (BaseAddon) this, 1304, -8, 0, 0, 1083, -1, "", 1);// 184
			AddComplexComponent( (BaseAddon) this, 1304, -8, 1, 0, 1083, -1, "", 1);// 185
			AddComplexComponent( (BaseAddon) this, 1304, -8, 2, 0, 1083, -1, "", 1);// 186
			AddComplexComponent( (BaseAddon) this, 1304, -8, 3, 0, 1083, -1, "", 1);// 187
			AddComplexComponent( (BaseAddon) this, 1304, -8, 4, 0, 1083, -1, "", 1);// 188
			AddComplexComponent( (BaseAddon) this, 1304, -8, 5, 0, 1083, -1, "", 1);// 189
			AddComplexComponent( (BaseAddon) this, 1304, -7, -10, 0, 1083, -1, "", 1);// 190
			AddComplexComponent( (BaseAddon) this, 1304, -7, -9, 0, 1083, -1, "", 1);// 191
			AddComplexComponent( (BaseAddon) this, 1304, -7, -8, 0, 1083, -1, "", 1);// 192
			AddComplexComponent( (BaseAddon) this, 1304, -7, -7, 0, 1083, -1, "", 1);// 193
			AddComplexComponent( (BaseAddon) this, 1304, -7, -6, 0, 1083, -1, "", 1);// 194
			AddComplexComponent( (BaseAddon) this, 1304, -7, -5, 0, 1083, -1, "", 1);// 195
			AddComplexComponent( (BaseAddon) this, 1304, -7, -4, 0, 1083, -1, "", 1);// 196
			AddComplexComponent( (BaseAddon) this, 1304, -7, -3, 0, 1083, -1, "", 1);// 197
			AddComplexComponent( (BaseAddon) this, 1304, -7, -2, 0, 1083, -1, "", 1);// 198
			AddComplexComponent( (BaseAddon) this, 1304, -7, -1, 0, 1083, -1, "", 1);// 199
			AddComplexComponent( (BaseAddon) this, 1304, -7, 0, 0, 1083, -1, "", 1);// 200
			AddComplexComponent( (BaseAddon) this, 1304, -7, 1, 0, 1083, -1, "", 1);// 201
			AddComplexComponent( (BaseAddon) this, 1304, -7, 2, 0, 1083, -1, "", 1);// 202
			AddComplexComponent( (BaseAddon) this, 1304, -7, 3, 0, 1083, -1, "", 1);// 203
			AddComplexComponent( (BaseAddon) this, 1304, -7, 4, 0, 1083, -1, "", 1);// 204
			AddComplexComponent( (BaseAddon) this, 1304, -7, 5, 0, 1083, -1, "", 1);// 205
			AddComplexComponent( (BaseAddon) this, 1304, -6, -10, 0, 1083, -1, "", 1);// 206
			AddComplexComponent( (BaseAddon) this, 1304, -6, -9, 0, 1083, -1, "", 1);// 207
			AddComplexComponent( (BaseAddon) this, 1304, -6, -8, 0, 1083, -1, "", 1);// 208
			AddComplexComponent( (BaseAddon) this, 1304, -6, -7, 0, 1083, -1, "", 1);// 209
			AddComplexComponent( (BaseAddon) this, 1304, -6, -6, 0, 1083, -1, "", 1);// 210
			AddComplexComponent( (BaseAddon) this, 1304, -6, -5, 0, 1083, -1, "", 1);// 211
			AddComplexComponent( (BaseAddon) this, 1304, -6, -4, 0, 1083, -1, "", 1);// 212
			AddComplexComponent( (BaseAddon) this, 1304, -6, -3, 0, 1083, -1, "", 1);// 213
			AddComplexComponent( (BaseAddon) this, 1304, -6, -2, 0, 1083, -1, "", 1);// 214
			AddComplexComponent( (BaseAddon) this, 1304, -6, -1, 0, 1083, -1, "", 1);// 215
			AddComplexComponent( (BaseAddon) this, 1304, -6, 0, 0, 1083, -1, "", 1);// 216
			AddComplexComponent( (BaseAddon) this, 1304, -6, 1, 0, 1083, -1, "", 1);// 217
			AddComplexComponent( (BaseAddon) this, 1304, -6, 2, 0, 1083, -1, "", 1);// 218
			AddComplexComponent( (BaseAddon) this, 1304, -6, 3, 0, 1083, -1, "", 1);// 219
			AddComplexComponent( (BaseAddon) this, 1304, -6, 4, 0, 1083, -1, "", 1);// 220
			AddComplexComponent( (BaseAddon) this, 1304, -6, 5, 0, 1083, -1, "", 1);// 221
			AddComplexComponent( (BaseAddon) this, 1304, -5, -10, 0, 1083, -1, "", 1);// 222
			AddComplexComponent( (BaseAddon) this, 1304, -5, -9, 0, 1083, -1, "", 1);// 223
			AddComplexComponent( (BaseAddon) this, 1304, -5, -8, 0, 1083, -1, "", 1);// 224
			AddComplexComponent( (BaseAddon) this, 1304, -5, -7, 0, 1083, -1, "", 1);// 225
			AddComplexComponent( (BaseAddon) this, 1304, -5, -6, 0, 1083, -1, "", 1);// 226
			AddComplexComponent( (BaseAddon) this, 1304, -5, -5, 0, 1083, -1, "", 1);// 227
			AddComplexComponent( (BaseAddon) this, 1304, -5, -4, 0, 1083, -1, "", 1);// 228
			AddComplexComponent( (BaseAddon) this, 1304, -5, -3, 0, 1083, -1, "", 1);// 229
			AddComplexComponent( (BaseAddon) this, 1304, -5, -2, 0, 1083, -1, "", 1);// 230
			AddComplexComponent( (BaseAddon) this, 1304, -5, -1, 0, 1083, -1, "", 1);// 231
			AddComplexComponent( (BaseAddon) this, 1304, -5, 0, 0, 1083, -1, "", 1);// 232
			AddComplexComponent( (BaseAddon) this, 1304, -5, 1, 0, 1083, -1, "", 1);// 233
			AddComplexComponent( (BaseAddon) this, 1304, -5, 2, 0, 1083, -1, "", 1);// 234
			AddComplexComponent( (BaseAddon) this, 1304, -5, 3, 0, 1083, -1, "", 1);// 235
			AddComplexComponent( (BaseAddon) this, 1304, -5, 4, 0, 1083, -1, "", 1);// 236
			AddComplexComponent( (BaseAddon) this, 1304, -5, 5, 0, 1083, -1, "", 1);// 237
			AddComplexComponent( (BaseAddon) this, 1304, -4, -10, 0, 1083, -1, "", 1);// 238
			AddComplexComponent( (BaseAddon) this, 1304, -4, -9, 0, 1083, -1, "", 1);// 239
			AddComplexComponent( (BaseAddon) this, 1304, -4, -8, 0, 1083, -1, "", 1);// 240
			AddComplexComponent( (BaseAddon) this, 1304, -4, -7, 0, 1083, -1, "", 1);// 241
			AddComplexComponent( (BaseAddon) this, 1304, -4, -6, 0, 1083, -1, "", 1);// 242
			AddComplexComponent( (BaseAddon) this, 1304, -4, -5, 0, 1083, -1, "", 1);// 243
			AddComplexComponent( (BaseAddon) this, 1304, -4, -4, 0, 1083, -1, "", 1);// 244
			AddComplexComponent( (BaseAddon) this, 1304, -4, -3, 0, 1083, -1, "", 1);// 245
			AddComplexComponent( (BaseAddon) this, 1304, -4, -2, 0, 1083, -1, "", 1);// 246
			AddComplexComponent( (BaseAddon) this, 1304, -4, -1, 0, 1083, -1, "", 1);// 247
			AddComplexComponent( (BaseAddon) this, 1304, -4, 0, 0, 1083, -1, "", 1);// 248
			AddComplexComponent( (BaseAddon) this, 1304, -4, 1, 0, 1083, -1, "", 1);// 249
			AddComplexComponent( (BaseAddon) this, 1304, -4, 2, 0, 1083, -1, "", 1);// 250
			AddComplexComponent( (BaseAddon) this, 1304, -4, 3, 0, 1083, -1, "", 1);// 251
			AddComplexComponent( (BaseAddon) this, 1304, -4, 4, 0, 1083, -1, "", 1);// 252
			AddComplexComponent( (BaseAddon) this, 1304, -4, 5, 0, 1083, -1, "", 1);// 253
			AddComplexComponent( (BaseAddon) this, 1304, -3, -10, 0, 1083, -1, "", 1);// 254
			AddComplexComponent( (BaseAddon) this, 1304, -3, -9, 0, 1083, -1, "", 1);// 255
			AddComplexComponent( (BaseAddon) this, 1304, -3, -8, 0, 1083, -1, "", 1);// 256
			AddComplexComponent( (BaseAddon) this, 1304, -3, -7, 0, 1083, -1, "", 1);// 257
			AddComplexComponent( (BaseAddon) this, 1304, -3, -6, 0, 1083, -1, "", 1);// 258
			AddComplexComponent( (BaseAddon) this, 1304, -3, -5, 0, 1083, -1, "", 1);// 259
			AddComplexComponent( (BaseAddon) this, 1304, -3, -4, 0, 1083, -1, "", 1);// 260
			AddComplexComponent( (BaseAddon) this, 1304, -3, -3, 0, 1083, -1, "", 1);// 261
			AddComplexComponent( (BaseAddon) this, 1304, -3, -2, 0, 1083, -1, "", 1);// 262
			AddComplexComponent( (BaseAddon) this, 1304, -3, -1, 0, 1083, -1, "", 1);// 263
			AddComplexComponent( (BaseAddon) this, 1304, -3, 0, 0, 1083, -1, "", 1);// 264
			AddComplexComponent( (BaseAddon) this, 1304, -3, 1, 0, 1083, -1, "", 1);// 265
			AddComplexComponent( (BaseAddon) this, 1304, -3, 2, 0, 1083, -1, "", 1);// 266
			AddComplexComponent( (BaseAddon) this, 1304, -3, 3, 0, 1083, -1, "", 1);// 267
			AddComplexComponent( (BaseAddon) this, 1304, -3, 4, 0, 1083, -1, "", 1);// 268
			AddComplexComponent( (BaseAddon) this, 1304, -3, 5, 0, 1083, -1, "", 1);// 269
			AddComplexComponent( (BaseAddon) this, 1304, -2, -10, 0, 1083, -1, "", 1);// 270
			AddComplexComponent( (BaseAddon) this, 1304, -2, -9, 0, 1083, -1, "", 1);// 271
			AddComplexComponent( (BaseAddon) this, 1304, -2, -8, 0, 1083, -1, "", 1);// 272
			AddComplexComponent( (BaseAddon) this, 1304, -2, -7, 0, 1083, -1, "", 1);// 273
			AddComplexComponent( (BaseAddon) this, 1304, -2, -6, 0, 1083, -1, "", 1);// 274
			AddComplexComponent( (BaseAddon) this, 1304, -2, -5, 0, 1083, -1, "", 1);// 275
			AddComplexComponent( (BaseAddon) this, 1304, -2, -4, 0, 1083, -1, "", 1);// 276
			AddComplexComponent( (BaseAddon) this, 1304, -2, -3, 0, 1083, -1, "", 1);// 277
			AddComplexComponent( (BaseAddon) this, 1304, -2, -2, 0, 1083, -1, "", 1);// 278
			AddComplexComponent( (BaseAddon) this, 1304, -2, -1, 0, 1083, -1, "", 1);// 279
			AddComplexComponent( (BaseAddon) this, 1304, -2, 0, 0, 1083, -1, "", 1);// 280
			AddComplexComponent( (BaseAddon) this, 1304, -2, 1, 0, 1083, -1, "", 1);// 281
			AddComplexComponent( (BaseAddon) this, 1304, -2, 2, 0, 1083, -1, "", 1);// 282
			AddComplexComponent( (BaseAddon) this, 1304, -2, 3, 0, 1083, -1, "", 1);// 283
			AddComplexComponent( (BaseAddon) this, 1304, -2, 4, 0, 1083, -1, "", 1);// 284
			AddComplexComponent( (BaseAddon) this, 1304, -2, 5, 0, 1083, -1, "", 1);// 285
			AddComplexComponent( (BaseAddon) this, 1304, -1, -10, 0, 1083, -1, "", 1);// 286
			AddComplexComponent( (BaseAddon) this, 1304, -1, -9, 0, 1083, -1, "", 1);// 287
			AddComplexComponent( (BaseAddon) this, 1304, -1, -8, 0, 1083, -1, "", 1);// 288
			AddComplexComponent( (BaseAddon) this, 1304, -1, -7, 0, 1083, -1, "", 1);// 289
			AddComplexComponent( (BaseAddon) this, 1304, -1, -6, 0, 1083, -1, "", 1);// 290
			AddComplexComponent( (BaseAddon) this, 1304, -1, -5, 0, 1083, -1, "", 1);// 291
			AddComplexComponent( (BaseAddon) this, 1304, -1, -4, 0, 1083, -1, "", 1);// 292
			AddComplexComponent( (BaseAddon) this, 1304, -1, -3, 0, 1083, -1, "", 1);// 293
			AddComplexComponent( (BaseAddon) this, 1304, -1, -2, 0, 1083, -1, "", 1);// 294
			AddComplexComponent( (BaseAddon) this, 1304, -1, -1, 0, 1083, -1, "", 1);// 295
			AddComplexComponent( (BaseAddon) this, 1304, -1, 0, 0, 1083, -1, "", 1);// 296
			AddComplexComponent( (BaseAddon) this, 1304, -1, 1, 0, 1083, -1, "", 1);// 297
			AddComplexComponent( (BaseAddon) this, 1304, -1, 2, 0, 1083, -1, "", 1);// 298
			AddComplexComponent( (BaseAddon) this, 1304, -1, 3, 0, 1083, -1, "", 1);// 299
			AddComplexComponent( (BaseAddon) this, 1304, -1, 4, 0, 1083, -1, "", 1);// 300
			AddComplexComponent( (BaseAddon) this, 1304, -1, 5, 0, 1083, -1, "", 1);// 301
			AddComplexComponent( (BaseAddon) this, 1304, 0, -10, 0, 1083, -1, "", 1);// 302
			AddComplexComponent( (BaseAddon) this, 1304, 0, -9, 0, 1083, -1, "", 1);// 303
			AddComplexComponent( (BaseAddon) this, 1304, 0, -8, 0, 1083, -1, "", 1);// 304
			AddComplexComponent( (BaseAddon) this, 1304, 0, -7, 0, 1083, -1, "", 1);// 305
			AddComplexComponent( (BaseAddon) this, 1304, 0, -6, 0, 1083, -1, "", 1);// 306
			AddComplexComponent( (BaseAddon) this, 1304, 0, -5, 0, 1083, -1, "", 1);// 307
			AddComplexComponent( (BaseAddon) this, 1304, 0, -4, 0, 1083, -1, "", 1);// 308
			AddComplexComponent( (BaseAddon) this, 1304, 0, -3, 0, 1083, -1, "", 1);// 309
			AddComplexComponent( (BaseAddon) this, 1304, 0, -2, 0, 1083, -1, "", 1);// 310
			AddComplexComponent( (BaseAddon) this, 1304, 0, -1, 0, 1083, -1, "", 1);// 311
			AddComplexComponent( (BaseAddon) this, 1304, 0, 0, 0, 1083, -1, "", 1);// 312
			AddComplexComponent( (BaseAddon) this, 1304, 0, 1, 0, 1083, -1, "", 1);// 313
			AddComplexComponent( (BaseAddon) this, 1304, 0, 2, 0, 1083, -1, "", 1);// 314
			AddComplexComponent( (BaseAddon) this, 1304, 0, 3, 0, 1083, -1, "", 1);// 315
			AddComplexComponent( (BaseAddon) this, 1304, 0, 4, 0, 1083, -1, "", 1);// 316
			AddComplexComponent( (BaseAddon) this, 1304, 0, 5, 0, 1083, -1, "", 1);// 317
			AddComplexComponent( (BaseAddon) this, 1304, 1, -10, 0, 1083, -1, "", 1);// 318
			AddComplexComponent( (BaseAddon) this, 1304, 1, -9, 0, 1083, -1, "", 1);// 319
			AddComplexComponent( (BaseAddon) this, 1304, 1, -8, 0, 1083, -1, "", 1);// 320
			AddComplexComponent( (BaseAddon) this, 1304, 1, -7, 0, 1083, -1, "", 1);// 321
			AddComplexComponent( (BaseAddon) this, 1304, 1, -6, 0, 1083, -1, "", 1);// 322
			AddComplexComponent( (BaseAddon) this, 1304, 1, -5, 0, 1083, -1, "", 1);// 323
			AddComplexComponent( (BaseAddon) this, 1304, 1, -4, 0, 1083, -1, "", 1);// 324
			AddComplexComponent( (BaseAddon) this, 1304, 1, -3, 0, 1083, -1, "", 1);// 325
			AddComplexComponent( (BaseAddon) this, 1304, 1, -2, 0, 1083, -1, "", 1);// 326
			AddComplexComponent( (BaseAddon) this, 1304, 1, -1, 0, 1083, -1, "", 1);// 327
			AddComplexComponent( (BaseAddon) this, 1304, 1, 0, 0, 1083, -1, "", 1);// 328
			AddComplexComponent( (BaseAddon) this, 1304, 1, 1, 0, 1083, -1, "", 1);// 329
			AddComplexComponent( (BaseAddon) this, 1304, 1, 2, 0, 1083, -1, "", 1);// 330
			AddComplexComponent( (BaseAddon) this, 1304, 1, 3, 0, 1083, -1, "", 1);// 331
			AddComplexComponent( (BaseAddon) this, 1304, 1, 4, 0, 1083, -1, "", 1);// 332
			AddComplexComponent( (BaseAddon) this, 1304, 1, 5, 0, 1083, -1, "", 1);// 333
			AddComplexComponent( (BaseAddon) this, 1304, 2, -10, 0, 1083, -1, "", 1);// 334
			AddComplexComponent( (BaseAddon) this, 1304, 2, -9, 0, 1083, -1, "", 1);// 335
			AddComplexComponent( (BaseAddon) this, 1304, 2, -8, 0, 1083, -1, "", 1);// 336
			AddComplexComponent( (BaseAddon) this, 1304, 2, -7, 0, 1083, -1, "", 1);// 337
			AddComplexComponent( (BaseAddon) this, 1304, 2, -6, 0, 1083, -1, "", 1);// 338
			AddComplexComponent( (BaseAddon) this, 1304, 2, -5, 0, 1083, -1, "", 1);// 339
			AddComplexComponent( (BaseAddon) this, 1304, 2, -4, 0, 1083, -1, "", 1);// 340
			AddComplexComponent( (BaseAddon) this, 1304, 2, -3, 0, 1083, -1, "", 1);// 341
			AddComplexComponent( (BaseAddon) this, 1304, 2, -2, 0, 1083, -1, "", 1);// 342
			AddComplexComponent( (BaseAddon) this, 1304, 2, -1, 0, 1083, -1, "", 1);// 343
			AddComplexComponent( (BaseAddon) this, 1304, 2, 0, 0, 1083, -1, "", 1);// 344
			AddComplexComponent( (BaseAddon) this, 1304, 2, 1, 0, 1083, -1, "", 1);// 345
			AddComplexComponent( (BaseAddon) this, 1304, 2, 2, 0, 1083, -1, "", 1);// 346
			AddComplexComponent( (BaseAddon) this, 1304, 2, 3, 0, 1083, -1, "", 1);// 347
			AddComplexComponent( (BaseAddon) this, 1304, 2, 4, 0, 1083, -1, "", 1);// 348
			AddComplexComponent( (BaseAddon) this, 1304, 2, 5, 0, 1083, -1, "", 1);// 349
			AddComplexComponent( (BaseAddon) this, 1304, 3, -10, 0, 1083, -1, "", 1);// 350
			AddComplexComponent( (BaseAddon) this, 1304, 3, -9, 0, 1083, -1, "", 1);// 351
			AddComplexComponent( (BaseAddon) this, 1304, 3, -8, 0, 1083, -1, "", 1);// 352
			AddComplexComponent( (BaseAddon) this, 1304, 3, -7, 0, 1083, -1, "", 1);// 353
			AddComplexComponent( (BaseAddon) this, 1304, 3, -6, 0, 1083, -1, "", 1);// 354
			AddComplexComponent( (BaseAddon) this, 1304, 3, -5, 0, 1083, -1, "", 1);// 355
			AddComplexComponent( (BaseAddon) this, 1304, 3, -4, 0, 1083, -1, "", 1);// 356
			AddComplexComponent( (BaseAddon) this, 1304, 3, -3, 0, 1083, -1, "", 1);// 357
			AddComplexComponent( (BaseAddon) this, 1304, 3, -2, 0, 1083, -1, "", 1);// 358
			AddComplexComponent( (BaseAddon) this, 1304, 3, -1, 0, 1083, -1, "", 1);// 359
			AddComplexComponent( (BaseAddon) this, 1304, 3, 0, 0, 1083, -1, "", 1);// 360
			AddComplexComponent( (BaseAddon) this, 1304, 3, 1, 0, 1083, -1, "", 1);// 361
			AddComplexComponent( (BaseAddon) this, 1304, 3, 2, 0, 1083, -1, "", 1);// 362
			AddComplexComponent( (BaseAddon) this, 1304, 3, 3, 0, 1083, -1, "", 1);// 363
			AddComplexComponent( (BaseAddon) this, 1304, 3, 4, 0, 1083, -1, "", 1);// 364
			AddComplexComponent( (BaseAddon) this, 1304, 3, 5, 0, 1083, -1, "", 1);// 365
			AddComplexComponent( (BaseAddon) this, 2879, -4, 0, 0, 1083, -1, "", 1);// 424
			AddComplexComponent( (BaseAddon) this, 2879, -3, 0, 0, 1083, -1, "", 1);// 425
			AddComplexComponent( (BaseAddon) this, 2879, -2, 0, 0, 1083, -1, "", 1);// 426
			AddComplexComponent( (BaseAddon) this, 2879, -1, 0, 0, 1083, -1, "", 1);// 427
			AddComplexComponent( (BaseAddon) this, 2879, 0, 0, 0, 1083, -1, "", 1);// 428
			AddComplexComponent( (BaseAddon) this, 2879, 1, 0, 0, 1083, -1, "", 1);// 429
			AddComplexComponent( (BaseAddon) this, 2879, 2, 0, 0, 1083, -1, "", 1);// 430
			AddComplexComponent( (BaseAddon) this, 2879, 3, 0, 0, 1083, -1, "", 1);// 431
			AddComplexComponent( (BaseAddon) this, 2879, -6, 0, 0, 1083, -1, "", 1);// 432
			AddComplexComponent( (BaseAddon) this, 2879, -5, 0, 0, 1083, -1, "", 1);// 433
			AddComplexComponent( (BaseAddon) this, 1304, -12, 6, 0, 1083, -1, "", 1);// 434
			AddComplexComponent( (BaseAddon) this, 1304, -12, 7, 0, 1083, -1, "", 1);// 435
			AddComplexComponent( (BaseAddon) this, 1304, -12, 8, 0, 1083, -1, "", 1);// 436
			AddComplexComponent( (BaseAddon) this, 1304, -12, 9, 0, 1083, -1, "", 1);// 437
			AddComplexComponent( (BaseAddon) this, 1304, -12, 10, 0, 1083, -1, "", 1);// 438
			AddComplexComponent( (BaseAddon) this, 1304, -12, 11, 0, 1083, -1, "", 1);// 439
			AddComplexComponent( (BaseAddon) this, 1304, -12, 12, 0, 1083, -1, "", 1);// 440
			AddComplexComponent( (BaseAddon) this, 1304, -11, 6, 0, 1083, -1, "", 1);// 441
			AddComplexComponent( (BaseAddon) this, 1304, -11, 7, 0, 1083, -1, "", 1);// 442
			AddComplexComponent( (BaseAddon) this, 1304, -11, 8, 0, 1083, -1, "", 1);// 443
			AddComplexComponent( (BaseAddon) this, 1304, -11, 9, 0, 1083, -1, "", 1);// 444
			AddComplexComponent( (BaseAddon) this, 1304, -11, 10, 0, 1083, -1, "", 1);// 445
			AddComplexComponent( (BaseAddon) this, 1304, -11, 11, 0, 1083, -1, "", 1);// 446
			AddComplexComponent( (BaseAddon) this, 1304, -11, 12, 0, 1083, -1, "", 1);// 447
			AddComplexComponent( (BaseAddon) this, 1304, -10, 6, 0, 1083, -1, "", 1);// 448
			AddComplexComponent( (BaseAddon) this, 1304, -10, 7, 0, 1083, -1, "", 1);// 449
			AddComplexComponent( (BaseAddon) this, 1304, -10, 8, 0, 1083, -1, "", 1);// 450
			AddComplexComponent( (BaseAddon) this, 1304, -10, 9, 0, 1083, -1, "", 1);// 451
			AddComplexComponent( (BaseAddon) this, 1304, -10, 10, 0, 1083, -1, "", 1);// 452
			AddComplexComponent( (BaseAddon) this, 1304, -10, 11, 0, 1083, -1, "", 1);// 453
			AddComplexComponent( (BaseAddon) this, 1304, -10, 12, 0, 1083, -1, "", 1);// 454
			AddComplexComponent( (BaseAddon) this, 1304, -9, 6, 0, 1083, -1, "", 1);// 455
			AddComplexComponent( (BaseAddon) this, 1304, -9, 7, 0, 1083, -1, "", 1);// 456
			AddComplexComponent( (BaseAddon) this, 1304, -9, 8, 0, 1083, -1, "", 1);// 457
			AddComplexComponent( (BaseAddon) this, 1304, -9, 9, 0, 1083, -1, "", 1);// 458
			AddComplexComponent( (BaseAddon) this, 1304, -9, 10, 0, 1083, -1, "", 1);// 459
			AddComplexComponent( (BaseAddon) this, 1304, -9, 11, 0, 1083, -1, "", 1);// 460
			AddComplexComponent( (BaseAddon) this, 1304, -9, 12, 0, 1083, -1, "", 1);// 461
			AddComplexComponent( (BaseAddon) this, 1304, -8, 6, 0, 1083, -1, "", 1);// 462
			AddComplexComponent( (BaseAddon) this, 1304, -8, 7, 0, 1083, -1, "", 1);// 463
			AddComplexComponent( (BaseAddon) this, 1304, -8, 8, 0, 1083, -1, "", 1);// 464
			AddComplexComponent( (BaseAddon) this, 1304, -8, 9, 0, 1083, -1, "", 1);// 465
			AddComplexComponent( (BaseAddon) this, 1304, -8, 10, 0, 1083, -1, "", 1);// 466
			AddComplexComponent( (BaseAddon) this, 1304, -8, 11, 0, 1083, -1, "", 1);// 467
			AddComplexComponent( (BaseAddon) this, 1304, -8, 12, 0, 1083, -1, "", 1);// 468
			AddComplexComponent( (BaseAddon) this, 1304, -7, 6, 0, 1083, -1, "", 1);// 469
			AddComplexComponent( (BaseAddon) this, 1304, -7, 7, 0, 1083, -1, "", 1);// 470
			AddComplexComponent( (BaseAddon) this, 1304, -7, 8, 0, 1083, -1, "", 1);// 471
			AddComplexComponent( (BaseAddon) this, 1304, -7, 9, 0, 1083, -1, "", 1);// 472
			AddComplexComponent( (BaseAddon) this, 1304, -7, 10, 0, 1083, -1, "", 1);// 473
			AddComplexComponent( (BaseAddon) this, 1304, -7, 11, 0, 1083, -1, "", 1);// 474
			AddComplexComponent( (BaseAddon) this, 1304, -7, 12, 0, 1083, -1, "", 1);// 475
			AddComplexComponent( (BaseAddon) this, 1304, -6, 6, 0, 1083, -1, "", 1);// 476
			AddComplexComponent( (BaseAddon) this, 1304, -6, 7, 0, 1083, -1, "", 1);// 477
			AddComplexComponent( (BaseAddon) this, 1304, -6, 8, 0, 1083, -1, "", 1);// 478
			AddComplexComponent( (BaseAddon) this, 1304, -6, 9, 0, 1083, -1, "", 1);// 479
			AddComplexComponent( (BaseAddon) this, 1304, -6, 10, 0, 1083, -1, "", 1);// 480
			AddComplexComponent( (BaseAddon) this, 1304, -6, 11, 0, 1083, -1, "", 1);// 481
			AddComplexComponent( (BaseAddon) this, 1304, -6, 12, 0, 1083, -1, "", 1);// 482
			AddComplexComponent( (BaseAddon) this, 1304, -5, 6, 0, 1083, -1, "", 1);// 483
			AddComplexComponent( (BaseAddon) this, 1304, -5, 7, 0, 1083, -1, "", 1);// 484
			AddComplexComponent( (BaseAddon) this, 1304, -5, 8, 0, 1083, -1, "", 1);// 485
			AddComplexComponent( (BaseAddon) this, 1304, -5, 9, 0, 1083, -1, "", 1);// 486
			AddComplexComponent( (BaseAddon) this, 1304, -5, 10, 0, 1083, -1, "", 1);// 487
			AddComplexComponent( (BaseAddon) this, 1304, -5, 11, 0, 1083, -1, "", 1);// 488
			AddComplexComponent( (BaseAddon) this, 1304, -5, 12, 0, 1083, -1, "", 1);// 489
			AddComplexComponent( (BaseAddon) this, 1304, -4, 6, 0, 1083, -1, "", 1);// 490
			AddComplexComponent( (BaseAddon) this, 1304, -4, 7, 0, 1083, -1, "", 1);// 491
			AddComplexComponent( (BaseAddon) this, 1304, -4, 8, 0, 1083, -1, "", 1);// 492
			AddComplexComponent( (BaseAddon) this, 1304, -4, 9, 0, 1083, -1, "", 1);// 493
			AddComplexComponent( (BaseAddon) this, 1304, -4, 10, 0, 1083, -1, "", 1);// 494
			AddComplexComponent( (BaseAddon) this, 1304, -4, 11, 0, 1083, -1, "", 1);// 495
			AddComplexComponent( (BaseAddon) this, 1304, -4, 12, 0, 1083, -1, "", 1);// 496
			AddComplexComponent( (BaseAddon) this, 1304, -3, 6, 0, 1083, -1, "", 1);// 497
			AddComplexComponent( (BaseAddon) this, 1304, -3, 7, 0, 1083, -1, "", 1);// 498
			AddComplexComponent( (BaseAddon) this, 1304, -3, 8, 0, 1083, -1, "", 1);// 499
			AddComplexComponent( (BaseAddon) this, 1304, -3, 9, 0, 1083, -1, "", 1);// 500
			AddComplexComponent( (BaseAddon) this, 1304, -3, 10, 0, 1083, -1, "", 1);// 501
			AddComplexComponent( (BaseAddon) this, 1304, -3, 11, 0, 1083, -1, "", 1);// 502
			AddComplexComponent( (BaseAddon) this, 1304, -3, 12, 0, 1083, -1, "", 1);// 503
			AddComplexComponent( (BaseAddon) this, 1304, -2, 6, 0, 1083, -1, "", 1);// 504
			AddComplexComponent( (BaseAddon) this, 1304, -2, 7, 0, 1083, -1, "", 1);// 505
			AddComplexComponent( (BaseAddon) this, 1304, -2, 8, 0, 1083, -1, "", 1);// 506
			AddComplexComponent( (BaseAddon) this, 1304, -2, 9, 0, 1083, -1, "", 1);// 507
			AddComplexComponent( (BaseAddon) this, 1304, -2, 10, 0, 1083, -1, "", 1);// 508
			AddComplexComponent( (BaseAddon) this, 1304, -2, 11, 0, 1083, -1, "", 1);// 509
			AddComplexComponent( (BaseAddon) this, 1304, -2, 12, 0, 1083, -1, "", 1);// 510
			AddComplexComponent( (BaseAddon) this, 1304, -1, 6, 0, 1083, -1, "", 1);// 511
			AddComplexComponent( (BaseAddon) this, 1304, -1, 7, 0, 1083, -1, "", 1);// 512
			AddComplexComponent( (BaseAddon) this, 1304, -1, 8, 0, 1083, -1, "", 1);// 513
			AddComplexComponent( (BaseAddon) this, 1304, -1, 9, 0, 1083, -1, "", 1);// 514
			AddComplexComponent( (BaseAddon) this, 1304, -1, 10, 0, 1083, -1, "", 1);// 515
			AddComplexComponent( (BaseAddon) this, 1304, -1, 11, 0, 1083, -1, "", 1);// 516
			AddComplexComponent( (BaseAddon) this, 1304, -1, 12, 0, 1083, -1, "", 1);// 517
			AddComplexComponent( (BaseAddon) this, 1304, 0, 6, 0, 1083, -1, "", 1);// 518
			AddComplexComponent( (BaseAddon) this, 1304, 0, 7, 0, 1083, -1, "", 1);// 519
			AddComplexComponent( (BaseAddon) this, 1304, 0, 8, 0, 1083, -1, "", 1);// 520
			AddComplexComponent( (BaseAddon) this, 1304, 0, 9, 0, 1083, -1, "", 1);// 521
			AddComplexComponent( (BaseAddon) this, 1304, 0, 10, 0, 1083, -1, "", 1);// 522
			AddComplexComponent( (BaseAddon) this, 1304, 0, 11, 0, 1083, -1, "", 1);// 523
			AddComplexComponent( (BaseAddon) this, 1304, 0, 12, 0, 1083, -1, "", 1);// 524
			AddComplexComponent( (BaseAddon) this, 1304, 1, 6, 0, 1083, -1, "", 1);// 525
			AddComplexComponent( (BaseAddon) this, 1304, 1, 7, 0, 1083, -1, "", 1);// 526
			AddComplexComponent( (BaseAddon) this, 1304, 1, 8, 0, 1083, -1, "", 1);// 527
			AddComplexComponent( (BaseAddon) this, 1304, 1, 9, 0, 1083, -1, "", 1);// 528
			AddComplexComponent( (BaseAddon) this, 1304, 1, 10, 0, 1083, -1, "", 1);// 529
			AddComplexComponent( (BaseAddon) this, 1304, 1, 11, 0, 1083, -1, "", 1);// 530
			AddComplexComponent( (BaseAddon) this, 1304, 1, 12, 0, 1083, -1, "", 1);// 531
			AddComplexComponent( (BaseAddon) this, 1304, 2, 6, 0, 1083, -1, "", 1);// 532
			AddComplexComponent( (BaseAddon) this, 1304, 2, 7, 0, 1083, -1, "", 1);// 533
			AddComplexComponent( (BaseAddon) this, 1304, 2, 8, 0, 1083, -1, "", 1);// 534
			AddComplexComponent( (BaseAddon) this, 1304, 2, 9, 0, 1083, -1, "", 1);// 535
			AddComplexComponent( (BaseAddon) this, 1304, 2, 10, 0, 1083, -1, "", 1);// 536
			AddComplexComponent( (BaseAddon) this, 1304, 2, 11, 0, 1083, -1, "", 1);// 537
			AddComplexComponent( (BaseAddon) this, 1304, 2, 12, 0, 1083, -1, "", 1);// 538
			AddComplexComponent( (BaseAddon) this, 1304, 3, 6, 0, 1083, -1, "", 1);// 539
			AddComplexComponent( (BaseAddon) this, 1304, 3, 7, 0, 1083, -1, "", 1);// 540
			AddComplexComponent( (BaseAddon) this, 1304, 3, 8, 0, 1083, -1, "", 1);// 541
			AddComplexComponent( (BaseAddon) this, 1304, 3, 9, 0, 1083, -1, "", 1);// 542
			AddComplexComponent( (BaseAddon) this, 1304, 3, 10, 0, 1083, -1, "", 1);// 543
			AddComplexComponent( (BaseAddon) this, 1304, 3, 11, 0, 1083, -1, "", 1);// 544
			AddComplexComponent( (BaseAddon) this, 1304, 3, 12, 0, 1083, -1, "", 1);// 545
			AddComplexComponent( (BaseAddon) this, 128, -12, 12, 0, 1083, -1, "", 1);// 546
			AddComplexComponent( (BaseAddon) this, 128, -11, 12, 0, 1083, -1, "", 1);// 547
			AddComplexComponent( (BaseAddon) this, 128, -10, 12, 0, 1083, -1, "", 1);// 548
			AddComplexComponent( (BaseAddon) this, 128, -9, 12, 0, 1083, -1, "", 1);// 549
			AddComplexComponent( (BaseAddon) this, 128, -8, 12, 0, 1083, -1, "", 1);// 550
			AddComplexComponent( (BaseAddon) this, 128, -7, 12, 0, 1083, -1, "", 1);// 551
			AddComplexComponent( (BaseAddon) this, 128, -6, 12, 0, 1083, -1, "", 1);// 552
			AddComplexComponent( (BaseAddon) this, 128, -5, 12, 0, 1083, -1, "", 1);// 553
			AddComplexComponent( (BaseAddon) this, 128, -4, 12, 0, 1083, -1, "", 1);// 554
			AddComplexComponent( (BaseAddon) this, 128, -3, 12, 0, 1083, -1, "", 1);// 555
			AddComplexComponent( (BaseAddon) this, 128, -2, 12, 0, 1083, -1, "", 1);// 556
			AddComplexComponent( (BaseAddon) this, 128, -1, 12, 0, 1083, -1, "", 1);// 557
			AddComplexComponent( (BaseAddon) this, 128, 0, 12, 0, 1083, -1, "", 1);// 558
			AddComplexComponent( (BaseAddon) this, 128, 1, 12, 0, 1083, -1, "", 1);// 559
			AddComplexComponent( (BaseAddon) this, 128, 2, 12, 0, 1083, -1, "", 1);// 560
			AddComplexComponent( (BaseAddon) this, 128, 3, 12, 0, 1083, -1, "", 1);// 561
			AddComplexComponent( (BaseAddon) this, 1304, 4, -12, 0, 1083, -1, "", 1);// 630
			AddComplexComponent( (BaseAddon) this, 1304, 4, -11, 0, 1083, -1, "", 1);// 631
			AddComplexComponent( (BaseAddon) this, 1304, 5, -12, 0, 1083, -1, "", 1);// 632
			AddComplexComponent( (BaseAddon) this, 1304, 5, -11, 0, 1083, -1, "", 1);// 633
			AddComplexComponent( (BaseAddon) this, 1304, 6, -12, 0, 1083, -1, "", 1);// 634
			AddComplexComponent( (BaseAddon) this, 1304, 6, -11, 0, 1083, -1, "", 1);// 635
			AddComplexComponent( (BaseAddon) this, 1304, 7, -12, 0, 1083, -1, "", 1);// 636
			AddComplexComponent( (BaseAddon) this, 1304, 7, -11, 0, 1083, -1, "", 1);// 637
			AddComplexComponent( (BaseAddon) this, 1304, 8, -12, 0, 1083, -1, "", 1);// 638
			AddComplexComponent( (BaseAddon) this, 1304, 8, -11, 0, 1083, -1, "", 1);// 639
			AddComplexComponent( (BaseAddon) this, 1304, 9, -12, 0, 1083, -1, "", 1);// 640
			AddComplexComponent( (BaseAddon) this, 1304, 9, -11, 0, 1083, -1, "", 1);// 641
			AddComplexComponent( (BaseAddon) this, 1304, 10, -12, 0, 1083, -1, "", 1);// 642
			AddComplexComponent( (BaseAddon) this, 1304, 10, -11, 0, 1083, -1, "", 1);// 643
			AddComplexComponent( (BaseAddon) this, 1304, 11, -12, 0, 1083, -1, "", 1);// 644
			AddComplexComponent( (BaseAddon) this, 1304, 11, -11, 0, 1083, -1, "", 1);// 645
			AddComplexComponent( (BaseAddon) this, 1304, 12, -12, 0, 1083, -1, "", 1);// 646
			AddComplexComponent( (BaseAddon) this, 1304, 12, -11, 0, 1083, -1, "", 1);// 647
			AddComplexComponent( (BaseAddon) this, 1304, 13, -12, 0, 1083, -1, "", 1);// 648
			AddComplexComponent( (BaseAddon) this, 1304, 13, -11, 0, 1083, -1, "", 1);// 649
			AddComplexComponent( (BaseAddon) this, 128, 13, -12, 0, 1083, -1, "", 1);// 650
			AddComplexComponent( (BaseAddon) this, 128, 13, -11, 0, 1083, -1, "", 1);// 651
			AddComplexComponent( (BaseAddon) this, 128, 4, -12, 0, 1083, -1, "", 1);// 652
			AddComplexComponent( (BaseAddon) this, 128, 5, -12, 0, 1083, -1, "", 1);// 653
			AddComplexComponent( (BaseAddon) this, 128, 6, -12, 0, 1083, -1, "", 1);// 654
			AddComplexComponent( (BaseAddon) this, 128, 7, -12, 0, 1083, -1, "", 1);// 655
			AddComplexComponent( (BaseAddon) this, 128, 8, -12, 0, 1083, -1, "", 1);// 656
			AddComplexComponent( (BaseAddon) this, 128, 9, -12, 0, 1083, -1, "", 1);// 657
			AddComplexComponent( (BaseAddon) this, 128, 10, -12, 0, 1083, -1, "", 1);// 658
			AddComplexComponent( (BaseAddon) this, 128, 11, -12, 0, 1083, -1, "", 1);// 659
			AddComplexComponent( (BaseAddon) this, 128, 12, -12, 0, 1083, -1, "", 1);// 660
			AddComplexComponent( (BaseAddon) this, 128, 13, -12, 0, 1083, -1, "", 1);// 661
			AddComplexComponent( (BaseAddon) this, 1304, 4, -10, 0, 1083, -1, "", 1);// 667
			AddComplexComponent( (BaseAddon) this, 1304, 4, -9, 0, 1083, -1, "", 1);// 668
			AddComplexComponent( (BaseAddon) this, 1304, 4, -8, 0, 1083, -1, "", 1);// 669
			AddComplexComponent( (BaseAddon) this, 1304, 4, -7, 0, 1083, -1, "", 1);// 670
			AddComplexComponent( (BaseAddon) this, 1304, 4, -6, 0, 1083, -1, "", 1);// 671
			AddComplexComponent( (BaseAddon) this, 1304, 4, -5, 0, 1083, -1, "", 1);// 672
			AddComplexComponent( (BaseAddon) this, 1304, 4, -4, 0, 1083, -1, "", 1);// 673
			AddComplexComponent( (BaseAddon) this, 1304, 4, -3, 0, 1083, -1, "", 1);// 674
			AddComplexComponent( (BaseAddon) this, 1304, 4, -2, 0, 1083, -1, "", 1);// 675
			AddComplexComponent( (BaseAddon) this, 1304, 4, -1, 0, 1083, -1, "", 1);// 676
			AddComplexComponent( (BaseAddon) this, 1304, 4, 0, 0, 1083, -1, "", 1);// 677
			AddComplexComponent( (BaseAddon) this, 1304, 4, 1, 0, 1083, -1, "", 1);// 678
			AddComplexComponent( (BaseAddon) this, 1304, 4, 2, 0, 1083, -1, "", 1);// 679
			AddComplexComponent( (BaseAddon) this, 1304, 4, 3, 0, 1083, -1, "", 1);// 680
			AddComplexComponent( (BaseAddon) this, 1304, 4, 4, 0, 1083, -1, "", 1);// 681
			AddComplexComponent( (BaseAddon) this, 1304, 4, 5, 0, 1083, -1, "", 1);// 682
			AddComplexComponent( (BaseAddon) this, 1304, 5, -10, 0, 1083, -1, "", 1);// 683
			AddComplexComponent( (BaseAddon) this, 1304, 5, -9, 0, 1083, -1, "", 1);// 684
			AddComplexComponent( (BaseAddon) this, 1304, 5, -8, 0, 1083, -1, "", 1);// 685
			AddComplexComponent( (BaseAddon) this, 1304, 5, -7, 0, 1083, -1, "", 1);// 686
			AddComplexComponent( (BaseAddon) this, 1304, 5, -6, 0, 1083, -1, "", 1);// 687
			AddComplexComponent( (BaseAddon) this, 1304, 5, -5, 0, 1083, -1, "", 1);// 688
			AddComplexComponent( (BaseAddon) this, 1304, 5, -4, 0, 1083, -1, "", 1);// 689
			AddComplexComponent( (BaseAddon) this, 1304, 5, -3, 0, 1083, -1, "", 1);// 690
			AddComplexComponent( (BaseAddon) this, 1304, 5, -2, 0, 1083, -1, "", 1);// 691
			AddComplexComponent( (BaseAddon) this, 1304, 5, -1, 0, 1083, -1, "", 1);// 692
			AddComplexComponent( (BaseAddon) this, 1304, 5, 0, 0, 1083, -1, "", 1);// 693
			AddComplexComponent( (BaseAddon) this, 1304, 5, 1, 0, 1083, -1, "", 1);// 694
			AddComplexComponent( (BaseAddon) this, 1304, 5, 2, 0, 1083, -1, "", 1);// 695
			AddComplexComponent( (BaseAddon) this, 1304, 5, 3, 0, 1083, -1, "", 1);// 696
			AddComplexComponent( (BaseAddon) this, 1304, 5, 4, 0, 1083, -1, "", 1);// 697
			AddComplexComponent( (BaseAddon) this, 1304, 5, 5, 0, 1083, -1, "", 1);// 698
			AddComplexComponent( (BaseAddon) this, 1304, 6, -10, 0, 1083, -1, "", 1);// 699
			AddComplexComponent( (BaseAddon) this, 1304, 6, -9, 0, 1083, -1, "", 1);// 700
			AddComplexComponent( (BaseAddon) this, 1304, 6, -8, 0, 1083, -1, "", 1);// 701
			AddComplexComponent( (BaseAddon) this, 1304, 6, -7, 0, 1083, -1, "", 1);// 702
			AddComplexComponent( (BaseAddon) this, 1304, 6, -6, 0, 1083, -1, "", 1);// 703
			AddComplexComponent( (BaseAddon) this, 1304, 6, -5, 0, 1083, -1, "", 1);// 704
			AddComplexComponent( (BaseAddon) this, 1304, 6, -4, 0, 1083, -1, "", 1);// 705
			AddComplexComponent( (BaseAddon) this, 1304, 6, -3, 0, 1083, -1, "", 1);// 706
			AddComplexComponent( (BaseAddon) this, 1304, 6, -2, 0, 1083, -1, "", 1);// 707
			AddComplexComponent( (BaseAddon) this, 1304, 6, -1, 0, 1083, -1, "", 1);// 708
			AddComplexComponent( (BaseAddon) this, 1304, 6, 0, 0, 1083, -1, "", 1);// 709
			AddComplexComponent( (BaseAddon) this, 1304, 6, 1, 0, 1083, -1, "", 1);// 710
			AddComplexComponent( (BaseAddon) this, 1304, 6, 2, 0, 1083, -1, "", 1);// 711
			AddComplexComponent( (BaseAddon) this, 1304, 6, 3, 0, 1083, -1, "", 1);// 712
			AddComplexComponent( (BaseAddon) this, 1304, 6, 4, 0, 1083, -1, "", 1);// 713
			AddComplexComponent( (BaseAddon) this, 1304, 6, 5, 0, 1083, -1, "", 1);// 714
			AddComplexComponent( (BaseAddon) this, 1304, 7, -10, 0, 1083, -1, "", 1);// 715
			AddComplexComponent( (BaseAddon) this, 1304, 7, -9, 0, 1083, -1, "", 1);// 716
			AddComplexComponent( (BaseAddon) this, 1304, 7, -8, 0, 1083, -1, "", 1);// 717
			AddComplexComponent( (BaseAddon) this, 1304, 7, -7, 0, 1083, -1, "", 1);// 718
			AddComplexComponent( (BaseAddon) this, 1304, 7, -6, 0, 1083, -1, "", 1);// 719
			AddComplexComponent( (BaseAddon) this, 1304, 7, -5, 0, 1083, -1, "", 1);// 720
			AddComplexComponent( (BaseAddon) this, 1304, 7, -4, 0, 1083, -1, "", 1);// 721
			AddComplexComponent( (BaseAddon) this, 1304, 7, -3, 0, 1083, -1, "", 1);// 722
			AddComplexComponent( (BaseAddon) this, 1304, 7, -2, 0, 1083, -1, "", 1);// 723
			AddComplexComponent( (BaseAddon) this, 1304, 7, -1, 0, 1083, -1, "", 1);// 724
			AddComplexComponent( (BaseAddon) this, 1304, 7, 0, 0, 1083, -1, "", 1);// 725
			AddComplexComponent( (BaseAddon) this, 1304, 7, 1, 0, 1083, -1, "", 1);// 726
			AddComplexComponent( (BaseAddon) this, 1304, 7, 2, 0, 1083, -1, "", 1);// 727
			AddComplexComponent( (BaseAddon) this, 1304, 7, 3, 0, 1083, -1, "", 1);// 728
			AddComplexComponent( (BaseAddon) this, 1304, 7, 4, 0, 1083, -1, "", 1);// 729
			AddComplexComponent( (BaseAddon) this, 1304, 7, 5, 0, 1083, -1, "", 1);// 730
			AddComplexComponent( (BaseAddon) this, 1304, 8, -10, 0, 1083, -1, "", 1);// 731
			AddComplexComponent( (BaseAddon) this, 1304, 8, -9, 0, 1083, -1, "", 1);// 732
			AddComplexComponent( (BaseAddon) this, 1304, 8, -8, 0, 1083, -1, "", 1);// 733
			AddComplexComponent( (BaseAddon) this, 1304, 8, -7, 0, 1083, -1, "", 1);// 734
			AddComplexComponent( (BaseAddon) this, 1304, 8, -6, 0, 1083, -1, "", 1);// 735
			AddComplexComponent( (BaseAddon) this, 1304, 8, -5, 0, 1083, -1, "", 1);// 736
			AddComplexComponent( (BaseAddon) this, 1304, 8, -4, 0, 1083, -1, "", 1);// 737
			AddComplexComponent( (BaseAddon) this, 1304, 8, -3, 0, 1083, -1, "", 1);// 738
			AddComplexComponent( (BaseAddon) this, 1304, 8, -2, 0, 1083, -1, "", 1);// 739
			AddComplexComponent( (BaseAddon) this, 1304, 8, -1, 0, 1083, -1, "", 1);// 740
			AddComplexComponent( (BaseAddon) this, 1304, 8, 0, 0, 1083, -1, "", 1);// 741
			AddComplexComponent( (BaseAddon) this, 1304, 8, 1, 0, 1083, -1, "", 1);// 742
			AddComplexComponent( (BaseAddon) this, 1304, 8, 2, 0, 1083, -1, "", 1);// 743
			AddComplexComponent( (BaseAddon) this, 1304, 8, 3, 0, 1083, -1, "", 1);// 744
			AddComplexComponent( (BaseAddon) this, 1304, 8, 4, 0, 1083, -1, "", 1);// 745
			AddComplexComponent( (BaseAddon) this, 1304, 8, 5, 0, 1083, -1, "", 1);// 746
			AddComplexComponent( (BaseAddon) this, 1304, 9, -10, 0, 1083, -1, "", 1);// 747
			AddComplexComponent( (BaseAddon) this, 1304, 9, -9, 0, 1083, -1, "", 1);// 748
			AddComplexComponent( (BaseAddon) this, 1304, 9, -8, 0, 1083, -1, "", 1);// 749
			AddComplexComponent( (BaseAddon) this, 1304, 9, -7, 0, 1083, -1, "", 1);// 750
			AddComplexComponent( (BaseAddon) this, 1304, 9, -6, 0, 1083, -1, "", 1);// 751
			AddComplexComponent( (BaseAddon) this, 1304, 9, -5, 0, 1083, -1, "", 1);// 752
			AddComplexComponent( (BaseAddon) this, 1304, 9, -4, 0, 1083, -1, "", 1);// 753
			AddComplexComponent( (BaseAddon) this, 1304, 9, -3, 0, 1083, -1, "", 1);// 754
			AddComplexComponent( (BaseAddon) this, 1304, 9, -2, 0, 1083, -1, "", 1);// 755
			AddComplexComponent( (BaseAddon) this, 1304, 9, -1, 0, 1083, -1, "", 1);// 756
			AddComplexComponent( (BaseAddon) this, 1304, 9, 0, 0, 1083, -1, "", 1);// 757
			AddComplexComponent( (BaseAddon) this, 1304, 9, 1, 0, 1083, -1, "", 1);// 758
			AddComplexComponent( (BaseAddon) this, 1304, 9, 2, 0, 1083, -1, "", 1);// 759
			AddComplexComponent( (BaseAddon) this, 1304, 9, 3, 0, 1083, -1, "", 1);// 760
			AddComplexComponent( (BaseAddon) this, 1304, 9, 4, 0, 1083, -1, "", 1);// 761
			AddComplexComponent( (BaseAddon) this, 1304, 9, 5, 0, 1083, -1, "", 1);// 762
			AddComplexComponent( (BaseAddon) this, 1304, 10, -10, 0, 1083, -1, "", 1);// 763
			AddComplexComponent( (BaseAddon) this, 1304, 10, -9, 0, 1083, -1, "", 1);// 764
			AddComplexComponent( (BaseAddon) this, 1304, 10, -8, 0, 1083, -1, "", 1);// 765
			AddComplexComponent( (BaseAddon) this, 1304, 10, -7, 0, 1083, -1, "", 1);// 766
			AddComplexComponent( (BaseAddon) this, 1304, 10, -6, 0, 1083, -1, "", 1);// 767
			AddComplexComponent( (BaseAddon) this, 1304, 10, -5, 0, 1083, -1, "", 1);// 768
			AddComplexComponent( (BaseAddon) this, 1304, 10, -4, 0, 1083, -1, "", 1);// 769
			AddComplexComponent( (BaseAddon) this, 1304, 10, -3, 0, 1083, -1, "", 1);// 770
			AddComplexComponent( (BaseAddon) this, 1304, 10, -2, 0, 1083, -1, "", 1);// 771
			AddComplexComponent( (BaseAddon) this, 1304, 10, -1, 0, 1083, -1, "", 1);// 772
			AddComplexComponent( (BaseAddon) this, 1304, 10, 0, 0, 1083, -1, "", 1);// 773
			AddComplexComponent( (BaseAddon) this, 1304, 10, 1, 0, 1083, -1, "", 1);// 774
			AddComplexComponent( (BaseAddon) this, 1304, 10, 2, 0, 1083, -1, "", 1);// 775
			AddComplexComponent( (BaseAddon) this, 1304, 10, 3, 0, 1083, -1, "", 1);// 776
			AddComplexComponent( (BaseAddon) this, 1304, 10, 4, 0, 1083, -1, "", 1);// 777
			AddComplexComponent( (BaseAddon) this, 1304, 10, 5, 0, 1083, -1, "", 1);// 778
			AddComplexComponent( (BaseAddon) this, 1304, 11, -10, 0, 1083, -1, "", 1);// 779
			AddComplexComponent( (BaseAddon) this, 1304, 11, -9, 0, 1083, -1, "", 1);// 780
			AddComplexComponent( (BaseAddon) this, 1304, 11, -8, 0, 1083, -1, "", 1);// 781
			AddComplexComponent( (BaseAddon) this, 1304, 11, -7, 0, 1083, -1, "", 1);// 782
			AddComplexComponent( (BaseAddon) this, 1304, 11, -6, 0, 1083, -1, "", 1);// 783
			AddComplexComponent( (BaseAddon) this, 1304, 11, -5, 0, 1083, -1, "", 1);// 784
			AddComplexComponent( (BaseAddon) this, 1304, 11, -4, 0, 1083, -1, "", 1);// 785
			AddComplexComponent( (BaseAddon) this, 1304, 11, -3, 0, 1083, -1, "", 1);// 786
			AddComplexComponent( (BaseAddon) this, 1304, 11, -2, 0, 1083, -1, "", 1);// 787
			AddComplexComponent( (BaseAddon) this, 1304, 11, -1, 0, 1083, -1, "", 1);// 788
			AddComplexComponent( (BaseAddon) this, 1304, 11, 0, 0, 1083, -1, "", 1);// 789
			AddComplexComponent( (BaseAddon) this, 1304, 11, 1, 0, 1083, -1, "", 1);// 790
			AddComplexComponent( (BaseAddon) this, 1304, 11, 2, 0, 1083, -1, "", 1);// 791
			AddComplexComponent( (BaseAddon) this, 1304, 11, 3, 0, 1083, -1, "", 1);// 792
			AddComplexComponent( (BaseAddon) this, 1304, 11, 4, 0, 1083, -1, "", 1);// 793
			AddComplexComponent( (BaseAddon) this, 1304, 11, 5, 0, 1083, -1, "", 1);// 794
			AddComplexComponent( (BaseAddon) this, 1304, 12, -10, 0, 1083, -1, "", 1);// 795
			AddComplexComponent( (BaseAddon) this, 1304, 12, -9, 0, 1083, -1, "", 1);// 796
			AddComplexComponent( (BaseAddon) this, 1304, 12, -8, 0, 1083, -1, "", 1);// 797
			AddComplexComponent( (BaseAddon) this, 1304, 12, -7, 0, 1083, -1, "", 1);// 798
			AddComplexComponent( (BaseAddon) this, 1304, 12, -6, 0, 1083, -1, "", 1);// 799
			AddComplexComponent( (BaseAddon) this, 1304, 12, -5, 0, 1083, -1, "", 1);// 800
			AddComplexComponent( (BaseAddon) this, 1304, 12, -4, 0, 1083, -1, "", 1);// 801
			AddComplexComponent( (BaseAddon) this, 1304, 12, -3, 0, 1083, -1, "", 1);// 802
			AddComplexComponent( (BaseAddon) this, 1304, 12, -2, 0, 1083, -1, "", 1);// 803
			AddComplexComponent( (BaseAddon) this, 1304, 12, -1, 0, 1083, -1, "", 1);// 804
			AddComplexComponent( (BaseAddon) this, 1304, 12, 0, 0, 1083, -1, "", 1);// 805
			AddComplexComponent( (BaseAddon) this, 1304, 12, 1, 0, 1083, -1, "", 1);// 806
			AddComplexComponent( (BaseAddon) this, 1304, 12, 2, 0, 1083, -1, "", 1);// 807
			AddComplexComponent( (BaseAddon) this, 1304, 12, 3, 0, 1083, -1, "", 1);// 808
			AddComplexComponent( (BaseAddon) this, 1304, 12, 4, 0, 1083, -1, "", 1);// 809
			AddComplexComponent( (BaseAddon) this, 1304, 12, 5, 0, 1083, -1, "", 1);// 810
			AddComplexComponent( (BaseAddon) this, 1304, 13, -10, 0, 1083, -1, "", 1);// 811
			AddComplexComponent( (BaseAddon) this, 1304, 13, -9, 0, 1083, -1, "", 1);// 812
			AddComplexComponent( (BaseAddon) this, 1304, 13, -8, 0, 1083, -1, "", 1);// 813
			AddComplexComponent( (BaseAddon) this, 1304, 13, -7, 0, 1083, -1, "", 1);// 814
			AddComplexComponent( (BaseAddon) this, 1304, 13, -6, 0, 1083, -1, "", 1);// 815
			AddComplexComponent( (BaseAddon) this, 1304, 13, -5, 0, 1083, -1, "", 1);// 816
			AddComplexComponent( (BaseAddon) this, 1304, 13, -4, 0, 1083, -1, "", 1);// 817
			AddComplexComponent( (BaseAddon) this, 1304, 13, -3, 0, 1083, -1, "", 1);// 818
			AddComplexComponent( (BaseAddon) this, 1304, 13, -2, 0, 1083, -1, "", 1);// 819
			AddComplexComponent( (BaseAddon) this, 1304, 13, -1, 0, 1083, -1, "", 1);// 820
			AddComplexComponent( (BaseAddon) this, 1304, 13, 0, 0, 1083, -1, "", 1);// 821
			AddComplexComponent( (BaseAddon) this, 1304, 13, 1, 0, 1083, -1, "", 1);// 822
			AddComplexComponent( (BaseAddon) this, 1304, 13, 2, 0, 1083, -1, "", 1);// 823
			AddComplexComponent( (BaseAddon) this, 1304, 13, 3, 0, 1083, -1, "", 1);// 824
			AddComplexComponent( (BaseAddon) this, 1304, 13, 4, 0, 1083, -1, "", 1);// 825
			AddComplexComponent( (BaseAddon) this, 1304, 13, 5, 0, 1083, -1, "", 1);// 826
			AddComplexComponent( (BaseAddon) this, 128, 13, -10, 0, 1083, -1, "", 1);// 827
			AddComplexComponent( (BaseAddon) this, 128, 13, -9, 0, 1083, -1, "", 1);// 828
			AddComplexComponent( (BaseAddon) this, 128, 13, -8, 0, 1083, -1, "", 1);// 829
			AddComplexComponent( (BaseAddon) this, 128, 13, -7, 0, 1083, -1, "", 1);// 830
			AddComplexComponent( (BaseAddon) this, 128, 13, -6, 0, 1083, -1, "", 1);// 831
			AddComplexComponent( (BaseAddon) this, 128, 13, -5, 0, 1083, -1, "", 1);// 832
			AddComplexComponent( (BaseAddon) this, 128, 13, 5, 0, 1083, -1, "", 1);// 833
			AddComplexComponent( (BaseAddon) this, 2879, 13, -4, 0, 1083, -1, "", 1);// 834
			AddComplexComponent( (BaseAddon) this, 2879, 4, 0, 0, 1083, -1, "", 1);// 864
			AddComplexComponent( (BaseAddon) this, 2879, 5, 0, 0, 1083, -1, "", 1);// 865
			AddComplexComponent( (BaseAddon) this, 1304, 4, 6, 0, 1083, -1, "", 1);// 866
			AddComplexComponent( (BaseAddon) this, 1304, 4, 7, 0, 1083, -1, "", 1);// 867
			AddComplexComponent( (BaseAddon) this, 1304, 4, 8, 0, 1083, -1, "", 1);// 868
			AddComplexComponent( (BaseAddon) this, 1304, 4, 9, 0, 1083, -1, "", 1);// 869
			AddComplexComponent( (BaseAddon) this, 1304, 4, 10, 0, 1083, -1, "", 1);// 870
			AddComplexComponent( (BaseAddon) this, 1304, 4, 11, 0, 1083, -1, "", 1);// 871
			AddComplexComponent( (BaseAddon) this, 1304, 4, 12, 0, 1083, -1, "", 1);// 872
			AddComplexComponent( (BaseAddon) this, 1304, 5, 6, 0, 1083, -1, "", 1);// 873
			AddComplexComponent( (BaseAddon) this, 1304, 5, 7, 0, 1083, -1, "", 1);// 874
			AddComplexComponent( (BaseAddon) this, 1304, 5, 8, 0, 1083, -1, "", 1);// 875
			AddComplexComponent( (BaseAddon) this, 1304, 5, 9, 0, 1083, -1, "", 1);// 876
			AddComplexComponent( (BaseAddon) this, 1304, 5, 10, 0, 1083, -1, "", 1);// 877
			AddComplexComponent( (BaseAddon) this, 1304, 5, 11, 0, 1083, -1, "", 1);// 878
			AddComplexComponent( (BaseAddon) this, 1304, 5, 12, 0, 1083, -1, "", 1);// 879
			AddComplexComponent( (BaseAddon) this, 1304, 6, 6, 0, 1083, -1, "", 1);// 880
			AddComplexComponent( (BaseAddon) this, 1304, 6, 7, 0, 1083, -1, "", 1);// 881
			AddComplexComponent( (BaseAddon) this, 1304, 6, 8, 0, 1083, -1, "", 1);// 882
			AddComplexComponent( (BaseAddon) this, 1304, 6, 9, 0, 1083, -1, "", 1);// 883
			AddComplexComponent( (BaseAddon) this, 1304, 6, 10, 0, 1083, -1, "", 1);// 884
			AddComplexComponent( (BaseAddon) this, 1304, 6, 11, 0, 1083, -1, "", 1);// 885
			AddComplexComponent( (BaseAddon) this, 1304, 6, 12, 0, 1083, -1, "", 1);// 886
			AddComplexComponent( (BaseAddon) this, 1304, 7, 6, 0, 1083, -1, "", 1);// 887
			AddComplexComponent( (BaseAddon) this, 1304, 7, 7, 0, 1083, -1, "", 1);// 888
			AddComplexComponent( (BaseAddon) this, 1304, 7, 8, 0, 1083, -1, "", 1);// 889
			AddComplexComponent( (BaseAddon) this, 1304, 7, 9, 0, 1083, -1, "", 1);// 890
			AddComplexComponent( (BaseAddon) this, 1304, 7, 10, 0, 1083, -1, "", 1);// 891
			AddComplexComponent( (BaseAddon) this, 1304, 7, 11, 0, 1083, -1, "", 1);// 892
			AddComplexComponent( (BaseAddon) this, 1304, 7, 12, 0, 1083, -1, "", 1);// 893
			AddComplexComponent( (BaseAddon) this, 1304, 8, 6, 0, 1083, -1, "", 1);// 894
			AddComplexComponent( (BaseAddon) this, 1304, 8, 7, 0, 1083, -1, "", 1);// 895
			AddComplexComponent( (BaseAddon) this, 1304, 8, 8, 0, 1083, -1, "", 1);// 896
			AddComplexComponent( (BaseAddon) this, 1304, 8, 9, 0, 1083, -1, "", 1);// 897
			AddComplexComponent( (BaseAddon) this, 1304, 8, 10, 0, 1083, -1, "", 1);// 898
			AddComplexComponent( (BaseAddon) this, 1304, 8, 11, 0, 1083, -1, "", 1);// 899
			AddComplexComponent( (BaseAddon) this, 1304, 8, 12, 0, 1083, -1, "", 1);// 900
			AddComplexComponent( (BaseAddon) this, 1304, 9, 6, 0, 1083, -1, "", 1);// 901
			AddComplexComponent( (BaseAddon) this, 1304, 9, 7, 0, 1083, -1, "", 1);// 902
			AddComplexComponent( (BaseAddon) this, 1304, 9, 8, 0, 1083, -1, "", 1);// 903
			AddComplexComponent( (BaseAddon) this, 1304, 9, 9, 0, 1083, -1, "", 1);// 904
			AddComplexComponent( (BaseAddon) this, 1304, 9, 10, 0, 1083, -1, "", 1);// 905
			AddComplexComponent( (BaseAddon) this, 1304, 9, 11, 0, 1083, -1, "", 1);// 906
			AddComplexComponent( (BaseAddon) this, 1304, 9, 12, 0, 1083, -1, "", 1);// 907
			AddComplexComponent( (BaseAddon) this, 1304, 10, 6, 0, 1083, -1, "", 1);// 908
			AddComplexComponent( (BaseAddon) this, 1304, 10, 7, 0, 1083, -1, "", 1);// 909
			AddComplexComponent( (BaseAddon) this, 1304, 10, 8, 0, 1083, -1, "", 1);// 910
			AddComplexComponent( (BaseAddon) this, 1304, 10, 9, 0, 1083, -1, "", 1);// 911
			AddComplexComponent( (BaseAddon) this, 1304, 10, 10, 0, 1083, -1, "", 1);// 912
			AddComplexComponent( (BaseAddon) this, 1304, 10, 11, 0, 1083, -1, "", 1);// 913
			AddComplexComponent( (BaseAddon) this, 1304, 10, 12, 0, 1083, -1, "", 1);// 914
			AddComplexComponent( (BaseAddon) this, 1304, 11, 6, 0, 1083, -1, "", 1);// 915
			AddComplexComponent( (BaseAddon) this, 1304, 11, 7, 0, 1083, -1, "", 1);// 916
			AddComplexComponent( (BaseAddon) this, 1304, 11, 8, 0, 1083, -1, "", 1);// 917
			AddComplexComponent( (BaseAddon) this, 1304, 11, 9, 0, 1083, -1, "", 1);// 918
			AddComplexComponent( (BaseAddon) this, 1304, 11, 10, 0, 1083, -1, "", 1);// 919
			AddComplexComponent( (BaseAddon) this, 1304, 11, 11, 0, 1083, -1, "", 1);// 920
			AddComplexComponent( (BaseAddon) this, 1304, 11, 12, 0, 1083, -1, "", 1);// 921
			AddComplexComponent( (BaseAddon) this, 1304, 12, 6, 0, 1083, -1, "", 1);// 922
			AddComplexComponent( (BaseAddon) this, 1304, 12, 7, 0, 1083, -1, "", 1);// 923
			AddComplexComponent( (BaseAddon) this, 1304, 12, 8, 0, 1083, -1, "", 1);// 924
			AddComplexComponent( (BaseAddon) this, 1304, 12, 9, 0, 1083, -1, "", 1);// 925
			AddComplexComponent( (BaseAddon) this, 1304, 12, 10, 0, 1083, -1, "", 1);// 926
			AddComplexComponent( (BaseAddon) this, 1304, 12, 11, 0, 1083, -1, "", 1);// 927
			AddComplexComponent( (BaseAddon) this, 1304, 12, 12, 0, 1083, -1, "", 1);// 928
			AddComplexComponent( (BaseAddon) this, 1304, 13, 6, 0, 1083, -1, "", 1);// 929
			AddComplexComponent( (BaseAddon) this, 1304, 13, 7, 0, 1083, -1, "", 1);// 930
			AddComplexComponent( (BaseAddon) this, 1304, 13, 8, 0, 1083, -1, "", 1);// 931
			AddComplexComponent( (BaseAddon) this, 1304, 13, 9, 0, 1083, -1, "", 1);// 932
			AddComplexComponent( (BaseAddon) this, 1304, 13, 10, 0, 1083, -1, "", 1);// 933
			AddComplexComponent( (BaseAddon) this, 1304, 13, 11, 0, 1083, -1, "", 1);// 934
			AddComplexComponent( (BaseAddon) this, 1304, 13, 12, 0, 1083, -1, "", 1);// 935
			AddComplexComponent( (BaseAddon) this, 128, 13, 6, 0, 1083, -1, "", 1);// 936
			AddComplexComponent( (BaseAddon) this, 128, 13, 7, 0, 1083, -1, "", 1);// 937
			AddComplexComponent( (BaseAddon) this, 128, 13, 8, 0, 1083, -1, "", 1);// 938
			AddComplexComponent( (BaseAddon) this, 128, 13, 9, 0, 1083, -1, "", 1);// 939
			AddComplexComponent( (BaseAddon) this, 128, 13, 10, 0, 1083, -1, "", 1);// 940
			AddComplexComponent( (BaseAddon) this, 128, 13, 11, 0, 1083, -1, "", 1);// 941
			AddComplexComponent( (BaseAddon) this, 128, 13, 12, 0, 1083, -1, "", 1);// 942
			AddComplexComponent( (BaseAddon) this, 128, 4, 12, 0, 1083, -1, "", 1);// 943
			AddComplexComponent( (BaseAddon) this, 128, 5, 12, 0, 1083, -1, "", 1);// 944
			AddComplexComponent( (BaseAddon) this, 128, 6, 12, 0, 1083, -1, "", 1);// 945
			AddComplexComponent( (BaseAddon) this, 128, 7, 12, 0, 1083, -1, "", 1);// 946
			AddComplexComponent( (BaseAddon) this, 128, 8, 12, 0, 1083, -1, "", 1);// 947
			AddComplexComponent( (BaseAddon) this, 128, 9, 12, 0, 1083, -1, "", 1);// 948
			AddComplexComponent( (BaseAddon) this, 128, 10, 12, 0, 1083, -1, "", 1);// 949
			AddComplexComponent( (BaseAddon) this, 128, 11, 12, 0, 1083, -1, "", 1);// 950
			AddComplexComponent( (BaseAddon) this, 128, 12, 12, 0, 1083, -1, "", 1);// 951

		}

		public Trainingcenter1Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class Trainingcenter1AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new Trainingcenter1Addon();
			}
		}

		[Constructable]
		public Trainingcenter1AddonDeed()
		{
			Name = "Trainingcenter1";
		}

		public Trainingcenter1AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}