
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ArchDigSiteAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {192, -1, 2, 0}, {192, -1, -1, 0}, {192, 2, -1, 0}// 1	2	3	
			, {192, 2, 2, 0}, {934, 0, 2, 0}, {934, 1, 2, 0}// 4	5	6	
			, {934, 2, 2, 0}, {934, -1, 2, 0}, {937, 2, 2, 0}// 7	8	9	
			, {937, 2, 1, 0}, {937, 2, 0, 0}, {937, 2, -1, 0}// 10	11	12	
			, {10000, 2, -1, 0}, {10000, 1, -1, 0}, {10000, 0, -1, 0}// 13	14	15	
			, {10000, -1, -1, 0}, {10001, -1, -1, 0}, {10001, -1, 0, 0}// 16	17	18	
			, {10001, -1, 1, 0}, {10001, -1, 2, 0}, {3966, 1, 1, 5}// 19	20	33	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ArchDigSiteAddonDeed();
			}
		}

		[ Constructable ]
		public ArchDigSiteAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 4978, 1, 0, 0, 0, -1, "an Archeologists Brush", 1);// 21
			AddComplexComponent( (BaseAddon) this, 3701, 0, 0, 0, 1154, -1, "an Archeologists Pack", 1);// 22
			AddComplexComponent( (BaseAddon) this, 6949, 0, 0, 0, 2416, -1, "dirt", 1);// 23
			AddComplexComponent( (BaseAddon) this, 3810, 0, 1, 0, 0, -1, "dirt", 1);// 24
			AddComplexComponent( (BaseAddon) this, 6950, 0, 2, 0, 2416, -1, "dirt", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2324, 1, 1, 0, 0, -1, "dirt", 1);// 26
			AddComplexComponent( (BaseAddon) this, 4650, 1, 1, 0, 1, -1, "a hole", 1);// 27
			AddComplexComponent( (BaseAddon) this, 6947, 2, 2, 0, 2416, -1, "dirt", 1);// 28
			AddComplexComponent( (BaseAddon) this, 6948, 2, 0, 0, 2416, -1, "dirt", 1);// 29
			AddComplexComponent( (BaseAddon) this, 3809, 1, 0, 0, 0, -1, "dirt", 1);// 30
			AddComplexComponent( (BaseAddon) this, 3795, 1, 2, 0, 0, -1, "dirt", 1);// 31
			AddComplexComponent( (BaseAddon) this, 3808, 2, 1, 0, 0, -1, "dirt", 1);// 32

		}

		public ArchDigSiteAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ArchDigSiteAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ArchDigSiteAddon();
			}
		}

		[Constructable]
		public ArchDigSiteAddonDeed()
		{
			Name = "ArchDigSite";
		}

		public ArchDigSiteAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}