
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LgArcheDigSiteAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {10001, -3, 1, 0}, {10001, -3, -3, 0}, {10001, -3, -2, 0}// 1	2	3	
			, {10001, -3, -1, 0}, {10001, -3, 0, 0}, {10001, -3, 1, 0}// 4	5	6	
			, {10001, -3, 2, 0}, {10001, -3, 3, 0}, {10001, -3, 4, 0}// 7	8	9	
			, {10000, -3, -3, 0}, {934, -3, 4, 0}, {192, -3, 4, 0}// 10	11	12	
			, {192, -3, -3, 4}, {937, 4, -3, 0}, {937, 4, -2, 0}// 13	14	15	
			, {937, 4, -1, 0}, {937, 4, 0, 0}, {937, 4, 1, 0}// 16	17	18	
			, {937, 4, 2, 0}, {937, 4, 3, 0}, {937, 4, 4, 0}// 19	20	21	
			, {10000, -2, -3, 0}, {10000, -1, -3, 0}, {10000, 0, -3, 0}// 22	23	24	
			, {10000, 1, -3, 0}, {10000, 2, -3, 0}, {10000, 3, -3, 0}// 25	26	27	
			, {10000, 4, -3, 0}, {934, -2, 4, 0}, {934, -1, 4, 0}// 28	29	30	
			, {934, 0, 4, 0}, {934, 1, 4, 0}, {934, 2, 4, 0}// 31	32	33	
			, {934, 3, 4, 0}, {934, 4, 4, 0}, {192, 4, 4, 0}// 34	35	36	
			, {192, 4, -3, 0}, {2886, 1, 3, 0}// 37	76	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LgArcheDigSiteAddonDeed();
			}
		}

		[ Constructable ]
		public LgArcheDigSiteAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2324, -1, -1, 0, 0, -1, "dirt", 1);// 38
			AddComplexComponent( (BaseAddon) this, 4650, -1, -1, 0, 1, -1, "a hole", 1);// 39
			AddComplexComponent( (BaseAddon) this, 6947, 0, 0, 0, 2416, -1, "dirt", 1);// 40
			AddComplexComponent( (BaseAddon) this, 3808, 0, -1, 0, 0, -1, "dirt", 1);// 41
			AddComplexComponent( (BaseAddon) this, 6948, 0, -2, 0, 2416, -1, "dirt", 1);// 42
			AddComplexComponent( (BaseAddon) this, 3809, -1, -2, 0, 0, -1, "dirt", 1);// 43
			AddComplexComponent( (BaseAddon) this, 6949, -2, -2, 0, 2416, -1, "dirt", 1);// 44
			AddComplexComponent( (BaseAddon) this, 3810, -2, -1, 0, 0, -1, "dirt", 1);// 45
			AddComplexComponent( (BaseAddon) this, 6950, -2, 0, 0, 2416, -1, "dirt", 1);// 46
			AddComplexComponent( (BaseAddon) this, 3795, -1, 0, 0, 0, -1, "dirt", 1);// 47
			AddComplexComponent( (BaseAddon) this, 2324, 1, 3, 0, 0, -1, "dirt", 1);// 48
			AddComplexComponent( (BaseAddon) this, 4650, 1, 3, 0, 1, -1, "a hole", 1);// 49
			AddComplexComponent( (BaseAddon) this, 6947, 2, 4, 0, 2416, -1, "dirt", 1);// 50
			AddComplexComponent( (BaseAddon) this, 3808, 2, 3, 0, 0, -1, "dirt", 1);// 51
			AddComplexComponent( (BaseAddon) this, 6948, 2, 2, 0, 2416, -1, "dirt", 1);// 52
			AddComplexComponent( (BaseAddon) this, 3809, 1, 2, 0, 0, -1, "dirt", 1);// 53
			AddComplexComponent( (BaseAddon) this, 6949, 0, 2, 0, 2416, -1, "dirt", 1);// 54
			AddComplexComponent( (BaseAddon) this, 3810, 0, 3, 0, 0, -1, "dirt", 1);// 55
			AddComplexComponent( (BaseAddon) this, 6950, 0, 4, 0, 2416, -1, "dirt", 1);// 56
			AddComplexComponent( (BaseAddon) this, 3795, 1, 4, 0, 0, -1, "dirt", 1);// 57
			AddComplexComponent( (BaseAddon) this, 2324, 3, -1, 0, 0, -1, "dirt", 1);// 58
			AddComplexComponent( (BaseAddon) this, 4650, 3, -1, 0, 1, -1, "a hole", 1);// 59
			AddComplexComponent( (BaseAddon) this, 6947, 4, 0, 0, 2416, -1, "dirt", 1);// 60
			AddComplexComponent( (BaseAddon) this, 3808, 4, -1, 0, 0, -1, "dirt", 1);// 61
			AddComplexComponent( (BaseAddon) this, 6948, 4, -2, 0, 2416, -1, "dirt", 1);// 62
			AddComplexComponent( (BaseAddon) this, 3809, 3, -2, 0, 0, -1, "dirt", 1);// 63
			AddComplexComponent( (BaseAddon) this, 6949, 2, -2, 0, 2416, -1, "dirt", 1);// 64
			AddComplexComponent( (BaseAddon) this, 3810, 2, -1, 0, 0, -1, "dirt", 1);// 65
			AddComplexComponent( (BaseAddon) this, 6950, 2, 0, 0, 2416, -1, "dirt", 1);// 66
			AddComplexComponent( (BaseAddon) this, 3795, 3, 0, 0, 0, -1, "dirt", 1);// 67
			AddComplexComponent( (BaseAddon) this, 4978, -2, 3, 0, 0, -1, "an Archeologists Brush", 1);// 68
			AddComplexComponent( (BaseAddon) this, 4978, 1, -1, 0, 0, -1, "an Archeologists Brush", 1);// 69
			AddComplexComponent( (BaseAddon) this, 4978, 3, 3, 0, 0, -1, "an Archeologists Brush", 1);// 70
			AddComplexComponent( (BaseAddon) this, 4978, 3, 0, 0, 0, -1, "an Archeologists Brush", 1);// 71
			AddComplexComponent( (BaseAddon) this, 2594, 1, 2, 0, 0, 29, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 2594, 2, -1, 0, 0, 29, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 2594, -2, -1, 0, 0, 29, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 2594, -1, 0, 0, 0, 29, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 8700, -1, -1, 0, 0, -1, "Old Bones", 1);// 77

		}

		public LgArcheDigSiteAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LgArcheDigSiteAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LgArcheDigSiteAddon();
			}
		}

		[Constructable]
		public LgArcheDigSiteAddonDeed()
		{
			Name = "LgArcheDigSite";
		}

		public LgArcheDigSiteAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}