
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class pvp_arenaAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6013, -8, -7, 0}, {6013, -8, -6, 0}, {6013, -8, -5, 0}// 1	2	3	
			, {6013, -8, -4, 0}, {6013, -8, -3, 0}, {6013, -7, -7, 0}// 4	5	6	
			, {6013, -7, -6, 0}, {6013, -7, -5, 0}, {6013, -7, -4, 0}// 7	8	9	
			, {6013, -7, -3, 0}, {6013, -6, -7, 0}, {6013, -6, -6, 0}// 10	11	12	
			, {6013, -6, -5, 0}, {6013, -6, -4, 0}, {6013, -6, -3, 0}// 13	14	15	
			, {6013, -5, -7, 0}, {6013, -5, -6, 0}, {6013, -5, -5, 0}// 16	17	18	
			, {6013, -5, -4, 0}, {6013, -5, -3, 0}, {6013, -4, -7, 0}// 19	20	21	
			, {6013, -4, -6, 0}, {6013, -4, -5, 0}, {6013, -4, -4, 0}// 22	23	24	
			, {6013, -4, -3, 0}, {6013, -9, -10, 0}, {6013, -9, -9, 0}// 25	26	27	
			, {6013, -9, -8, 0}, {6013, -9, -7, 0}, {6013, -8, -10, 0}// 28	29	30	
			, {6013, -8, -9, 0}, {6013, -8, -8, 0}, {6013, -8, -7, 0}// 31	32	33	
			, {6013, -7, -10, 0}, {6013, -7, -9, 0}, {6013, -7, -8, 0}// 34	35	36	
			, {6013, -7, -7, 0}, {6013, -6, -10, 0}, {6013, -6, -9, 0}// 37	38	39	
			, {6013, -6, -8, 0}, {6013, -6, -7, 0}, {6013, -5, -10, 0}// 40	41	42	
			, {6013, -5, -9, 0}, {6013, -5, -8, 0}, {6013, -5, -7, 0}// 43	44	45	
			, {6013, -4, -10, 0}, {6013, -4, -9, 0}, {6013, -4, -8, 0}// 46	47	48	
			, {6013, -4, -7, 0}, {6013, -10, -10, 0}, {6013, -10, -9, 0}// 49	50	51	
			, {6013, -10, -8, 0}, {6013, -10, -7, 0}, {6013, -10, -6, 0}// 52	53	54	
			, {6013, -10, -5, 0}, {6013, -10, -4, 0}, {6013, -10, -3, 0}// 55	56	57	
			, {6013, -9, -7, 0}, {6013, -9, -6, 0}, {6013, -9, -5, 0}// 58	59	60	
			, {6013, -9, -4, 0}, {6013, -9, -3, 0}, {6013, -3, -7, 0}// 61	62	63	
			, {6013, -3, -6, 0}, {6013, -3, -5, 0}, {6013, -3, -4, 0}// 64	65	66	
			, {6013, -3, -3, 0}, {6013, -2, -7, 0}, {6013, -2, -6, 0}// 67	68	69	
			, {6013, -2, -5, 0}, {6013, -2, -4, 0}, {6013, -2, -3, 0}// 70	71	72	
			, {6013, -1, -7, 0}, {6013, -1, -6, 0}, {6013, -1, -5, 0}// 73	74	75	
			, {6013, -1, -4, 0}, {6013, -1, -3, 0}, {6013, 0, -7, 0}// 76	77	78	
			, {6013, 0, -6, 0}, {6013, 0, -5, 0}, {6013, 0, -4, 0}// 79	80	81	
			, {6013, 0, -3, 0}, {6013, -3, -10, 0}, {6013, -3, -9, 0}// 82	83	84	
			, {6013, -3, -8, 0}, {6013, -3, -7, 0}, {6013, -2, -10, 0}// 85	86	87	
			, {6013, -2, -9, 0}, {6013, -2, -8, 0}, {6013, -2, -7, 0}// 88	89	90	
			, {6013, -1, -10, 0}, {6013, -1, -9, 0}, {6013, -1, -8, 0}// 91	92	93	
			, {6013, -1, -7, 0}, {6013, 0, -10, 0}, {6013, 0, -9, 0}// 94	95	96	
			, {6013, 0, -8, 0}, {6013, 0, -7, 0}, {6013, -8, -2, 0}// 97	98	227	
			, {6013, -8, -1, 0}, {6013, -8, 0, 0}, {6013, -7, -2, 0}// 228	229	230	
			, {6013, -7, -1, 0}, {6013, -7, 0, 0}, {6013, -6, -2, 0}// 231	232	233	
			, {6013, -6, -1, 0}, {6013, -6, 0, 0}, {6013, -5, -2, 0}// 234	235	236	
			, {6013, -5, -1, 0}, {6013, -5, 0, 0}, {6013, -4, -2, 0}// 237	238	239	
			, {6013, -4, -1, 0}, {6013, -4, 0, 0}, {6013, -8, 0, 0}// 240	241	242	
			, {6013, -8, 1, 0}, {6013, -8, 2, 0}, {6013, -8, 3, 0}// 243	244	245	
			, {6013, -8, 4, 0}, {6013, -7, 0, 0}, {6013, -7, 1, 0}// 246	247	248	
			, {6013, -7, 2, 0}, {6013, -7, 3, 0}, {6013, -7, 4, 0}// 249	250	251	
			, {6013, -6, 0, 0}, {6013, -6, 1, 0}, {6013, -6, 2, 0}// 252	253	254	
			, {6013, -6, 3, 0}, {6013, -6, 4, 0}, {6013, -5, 0, 0}// 255	256	257	
			, {6013, -5, 1, 0}, {6013, -5, 2, 0}, {6013, -5, 3, 0}// 258	259	260	
			, {6013, -5, 4, 0}, {6013, -4, 0, 0}, {6013, -4, 1, 0}// 261	262	263	
			, {6013, -4, 2, 0}, {6013, -4, 3, 0}, {6013, -4, 4, 0}// 264	265	266	
			, {6013, -10, 3, 0}, {6013, -10, 4, 0}, {6013, -10, 5, 0}// 267	268	269	
			, {6013, -9, 3, 0}, {6013, -9, 4, 0}, {6013, -9, 5, 0}// 270	271	272	
			, {6013, -8, 3, 0}, {6013, -8, 4, 0}, {6013, -8, 5, 0}// 273	274	275	
			, {6013, -7, 3, 0}, {6013, -7, 4, 0}, {6013, -7, 5, 0}// 276	277	278	
			, {6013, -6, 3, 0}, {6013, -6, 4, 0}, {6013, -6, 5, 0}// 279	280	281	
			, {6013, -5, 3, 0}, {6013, -5, 4, 0}, {6013, -5, 5, 0}// 282	283	284	
			, {6013, -4, 3, 0}, {6013, -4, 4, 0}, {6013, -4, 5, 0}// 285	286	287	
			, {6013, -10, -2, 0}, {6013, -10, -1, 0}, {6013, -10, 0, 0}// 288	289	290	
			, {6013, -10, 1, 0}, {6013, -10, 2, 0}, {6013, -10, 3, 0}// 291	292	293	
			, {6013, -10, 4, 0}, {6013, -10, 5, 0}, {6013, -9, -2, 0}// 294	295	296	
			, {6013, -9, -1, 0}, {6013, -9, 0, 0}, {6013, -9, 1, 0}// 297	298	299	
			, {6013, -9, 2, 0}, {6013, -9, 3, 0}, {6013, -10, 6, 0}// 300	301	302	
			, {6013, -10, 7, 0}, {6013, -10, 8, 0}, {6013, -10, 9, 0}// 303	304	305	
			, {6013, -10, 10, 0}, {6013, -9, 6, 0}, {6013, -9, 7, 0}// 306	307	308	
			, {6013, -9, 8, 0}, {6013, -9, 9, 0}, {6013, -9, 10, 0}// 309	310	311	
			, {6013, -8, 6, 0}, {6013, -8, 7, 0}, {6013, -8, 8, 0}// 312	313	314	
			, {6013, -8, 9, 0}, {6013, -8, 10, 0}, {6013, -7, 6, 0}// 315	316	317	
			, {6013, -7, 7, 0}, {6013, -7, 8, 0}, {6013, -7, 9, 0}// 318	319	320	
			, {6013, -7, 10, 0}, {6013, -6, 6, 0}, {6013, -6, 7, 0}// 321	322	323	
			, {6013, -6, 8, 0}, {6013, -6, 9, 0}, {6013, -6, 10, 0}// 324	325	326	
			, {6013, -5, 6, 0}, {6013, -5, 7, 0}, {6013, -5, 8, 0}// 327	328	329	
			, {6013, -5, 9, 0}, {6013, -5, 10, 0}, {6013, -4, 6, 0}// 330	331	332	
			, {6013, -4, 7, 0}, {6013, -4, 8, 0}, {6013, -4, 9, 0}// 333	334	335	
			, {6013, -4, 10, 0}, {6013, -10, 6, 0}, {6013, -10, 7, 0}// 336	337	338	
			, {6013, -10, 8, 0}, {6013, -10, 9, 0}, {6013, -10, 10, 0}// 339	340	341	
			, {6013, -3, 0, 0}, {6013, -3, 1, 0}, {6013, -3, 2, 0}// 342	343	344	
			, {6013, -3, 3, 0}, {6013, -3, 4, 0}, {6013, -2, 0, 0}// 345	346	347	
			, {6013, -2, 1, 0}, {6013, -2, 2, 0}, {6013, -2, 3, 0}// 348	349	350	
			, {6013, -2, 4, 0}, {6013, -1, 0, 0}, {6013, -1, 1, 0}// 351	352	353	
			, {6013, -1, 2, 0}, {6013, -1, 3, 0}, {6013, -1, 4, 0}// 354	355	356	
			, {6013, 0, 0, 0}, {6013, 0, 1, 0}, {6013, 0, 2, 0}// 357	358	359	
			, {6013, 0, 3, 0}, {6013, 0, 4, 0}, {6013, -3, -2, 0}// 360	361	362	
			, {6013, -3, -1, 0}, {6013, -3, 0, 0}, {6013, -2, -2, 0}// 363	364	365	
			, {6013, -2, -1, 0}, {6013, -2, 0, 0}, {6013, -1, -2, 0}// 366	367	368	
			, {6013, -1, -1, 0}, {6013, -1, 0, 0}, {6013, 0, -2, 0}// 369	370	371	
			, {6013, 0, -1, 0}, {6013, 0, 0, 0}, {6013, -3, 0, 0}// 372	373	374	
			, {6013, -3, 1, 0}, {6013, -3, 2, 0}, {6013, -3, 3, 0}// 375	376	377	
			, {6013, -3, 4, 0}, {6013, -3, 3, 0}, {6013, -3, 4, 0}// 378	379	380	
			, {6013, -3, 5, 0}, {6013, -2, 3, 0}, {6013, -2, 4, 0}// 381	382	383	
			, {6013, -2, 5, 0}, {6013, -1, 3, 0}, {6013, -1, 4, 0}// 384	385	386	
			, {6013, -1, 5, 0}, {6013, 0, 3, 0}, {6013, 0, 4, 0}// 387	388	389	
			, {6013, 0, 5, 0}, {6013, -3, 6, 0}, {6013, -3, 7, 0}// 390	391	392	
			, {6013, -3, 8, 0}, {6013, -3, 9, 0}, {6013, -3, 10, 0}// 393	394	395	
			, {6013, -2, 6, 0}, {6013, -2, 7, 0}, {6013, -2, 8, 0}// 396	397	398	
			, {6013, -2, 9, 0}, {6013, -2, 10, 0}, {6013, -1, 6, 0}// 399	400	401	
			, {6013, -1, 7, 0}, {6013, -1, 8, 0}, {6013, -1, 9, 0}// 402	403	404	
			, {6013, -1, 10, 0}, {6013, 0, 6, 0}, {6013, 0, 7, 0}// 405	406	407	
			, {6013, 0, 8, 0}, {6013, 0, 9, 0}, {6013, 0, 10, 0}// 408	409	410	
			, {7417, -2, 1, 0}, {7416, -2, 2, 0}, {7415, -2, 3, 0}// 671	672	673	
			, {7414, -2, 4, 0}, {7413, -2, 5, 0}, {7419, -1, 0, 0}// 674	675	676	
			, {7418, -1, 1, 0}, {7433, -1, 2, 0}, {7432, -1, 3, 0}// 677	678	679	
			, {7431, -1, 4, 0}, {7412, -1, 5, 0}, {7420, 0, 0, 0}// 680	681	682	
			, {7434, 0, 1, 0}, {7441, 0, 2, 0}, {7440, 0, 3, 0}// 683	684	685	
			, {7430, 0, 4, 0}, {7411, 0, 5, 0}, {6013, 1, -7, 0}// 686	687	716	
			, {6013, 1, -6, 0}, {6013, 1, -5, 0}, {6013, 1, -4, 0}// 717	718	719	
			, {6013, 1, -3, 0}, {6013, 2, -7, 0}, {6013, 2, -6, 0}// 720	721	722	
			, {6013, 2, -5, 0}, {6013, 2, -4, 0}, {6013, 2, -3, 0}// 723	724	725	
			, {6013, 3, -7, 0}, {6013, 3, -6, 0}, {6013, 3, -5, 0}// 726	727	728	
			, {6013, 3, -4, 0}, {6013, 3, -3, 0}, {6013, 4, -7, 0}// 729	730	731	
			, {6013, 4, -6, 0}, {6013, 4, -5, 0}, {6013, 4, -4, 0}// 732	733	734	
			, {6013, 4, -3, 0}, {6013, 5, -7, 0}, {6013, 5, -6, 0}// 735	736	737	
			, {6013, 5, -5, 0}, {6013, 5, -4, 0}, {6013, 5, -3, 0}// 738	739	740	
			, {6013, 5, -7, 0}, {6013, 5, -6, 0}, {6013, 5, -5, 0}// 741	742	743	
			, {6013, 5, -4, 0}, {6013, 5, -3, 0}, {6013, 6, -7, 0}// 744	745	746	
			, {6013, 6, -6, 0}, {6013, 6, -5, 0}, {6013, 6, -4, 0}// 747	748	749	
			, {6013, 6, -3, 0}, {6013, 7, -7, 0}, {6013, 7, -6, 0}// 750	751	752	
			, {6013, 7, -5, 0}, {6013, 7, -4, 0}, {6013, 7, -3, 0}// 753	754	755	
			, {6013, 8, -7, 0}, {6013, 8, -6, 0}, {6013, 8, -5, 0}// 756	757	758	
			, {6013, 8, -4, 0}, {6013, 8, -3, 0}, {6013, 9, -7, 0}// 759	760	761	
			, {6013, 9, -6, 0}, {6013, 9, -5, 0}, {6013, 9, -4, 0}// 762	763	764	
			, {6013, 9, -3, 0}, {6013, 10, -7, 0}, {6013, 10, -6, 0}// 765	766	767	
			, {6013, 10, -5, 0}, {6013, 10, -4, 0}, {6013, 10, -3, 0}// 768	769	770	
			, {6013, 11, -7, 0}, {6013, 11, -6, 0}, {6013, 11, -5, 0}// 771	772	773	
			, {6013, 11, -4, 0}, {6013, 11, -3, 0}, {6013, 1, -10, 0}// 774	775	776	
			, {6013, 1, -9, 0}, {6013, 1, -8, 0}, {6013, 1, -7, 0}// 777	778	779	
			, {6013, 2, -10, 0}, {6013, 2, -9, 0}, {6013, 2, -8, 0}// 780	781	782	
			, {6013, 2, -7, 0}, {6013, 3, -10, 0}, {6013, 3, -9, 0}// 783	784	785	
			, {6013, 3, -8, 0}, {6013, 3, -7, 0}, {6013, 4, -10, 0}// 786	787	788	
			, {6013, 4, -9, 0}, {6013, 4, -8, 0}, {6013, 4, -7, 0}// 789	790	791	
			, {6013, 5, -10, 0}, {6013, 5, -9, 0}, {6013, 5, -8, 0}// 792	793	794	
			, {6013, 5, -7, 0}, {6013, 6, -10, 0}, {6013, 6, -9, 0}// 795	796	797	
			, {6013, 6, -8, 0}, {6013, 6, -7, 0}, {6013, 7, -10, 0}// 798	799	800	
			, {6013, 7, -9, 0}, {6013, 7, -8, 0}, {6013, 7, -7, 0}// 801	802	803	
			, {6013, 8, -10, 0}, {6013, 8, -9, 0}, {6013, 8, -8, 0}// 804	805	806	
			, {6013, 8, -7, 0}, {6013, 9, -10, 0}, {6013, 9, -9, 0}// 807	808	809	
			, {6013, 9, -8, 0}, {6013, 9, -7, 0}, {6013, 10, -10, 0}// 810	811	812	
			, {6013, 10, -9, 0}, {6013, 10, -8, 0}, {6013, 10, -7, 0}// 813	814	815	
			, {6013, 11, -10, 0}, {6013, 11, -9, 0}, {6013, 11, -8, 0}// 816	817	818	
			, {6013, 11, -7, 0}, {15119, 10, -8, 15}, {6013, 1, 0, 0}// 819	945	947	
			, {6013, 1, 1, 0}, {6013, 1, 2, 0}, {6013, 1, 3, 0}// 948	949	950	
			, {6013, 1, 4, 0}, {6013, 2, 0, 0}, {6013, 2, 1, 0}// 951	952	953	
			, {6013, 2, 2, 0}, {6013, 2, 3, 0}, {6013, 2, 4, 0}// 954	955	956	
			, {6013, 3, 0, 0}, {6013, 3, 1, 0}, {6013, 3, 2, 0}// 957	958	959	
			, {6013, 3, 3, 0}, {6013, 3, 4, 0}, {6013, 4, 0, 0}// 960	961	962	
			, {6013, 4, 1, 0}, {6013, 4, 2, 0}, {6013, 4, 3, 0}// 963	964	965	
			, {6013, 4, 4, 0}, {6013, 5, 0, 0}, {6013, 5, 1, 0}// 966	967	968	
			, {6013, 5, 2, 0}, {6013, 5, 3, 0}, {6013, 5, 4, 0}// 969	970	971	
			, {6013, 1, -2, 0}, {6013, 1, -1, 0}, {6013, 1, 0, 0}// 972	973	974	
			, {6013, 2, -2, 0}, {6013, 2, -1, 0}, {6013, 2, 0, 0}// 975	976	977	
			, {6013, 3, -2, 0}, {6013, 3, -1, 0}, {6013, 3, 0, 0}// 978	979	980	
			, {6013, 4, -2, 0}, {6013, 4, -1, 0}, {6013, 4, 0, 0}// 981	982	983	
			, {6013, 5, -2, 0}, {6013, 5, -1, 0}, {6013, 5, 0, 0}// 984	985	986	
			, {6013, 5, -2, 0}, {6013, 5, -1, 0}, {6013, 5, 0, 0}// 987	988	989	
			, {6013, 5, 1, 0}, {6013, 5, 2, 0}, {6013, 5, 3, 0}// 990	991	992	
			, {6013, 6, -2, 0}, {6013, 6, -1, 0}, {6013, 6, 0, 0}// 993	994	995	
			, {6013, 6, 1, 0}, {6013, 6, 2, 0}, {6013, 6, 3, 0}// 996	997	998	
			, {6013, 7, -2, 0}, {6013, 7, -1, 0}, {6013, 7, 0, 0}// 999	1000	1001	
			, {6013, 7, 1, 0}, {6013, 7, 2, 0}, {6013, 7, 3, 0}// 1002	1003	1004	
			, {6013, 8, -2, 0}, {6013, 8, -1, 0}, {6013, 8, 0, 0}// 1005	1006	1007	
			, {6013, 8, 1, 0}, {6013, 8, 2, 0}, {6013, 8, 3, 0}// 1008	1009	1010	
			, {6013, 9, -2, 0}, {6013, 9, -1, 0}, {6013, 9, 0, 0}// 1011	1012	1013	
			, {6013, 9, 1, 0}, {6013, 9, 2, 0}, {6013, 9, 3, 0}// 1014	1015	1016	
			, {6013, 10, -2, 0}, {6013, 10, -1, 0}, {6013, 10, 0, 0}// 1017	1018	1019	
			, {6013, 10, 1, 0}, {6013, 10, 2, 0}, {6013, 10, 3, 0}// 1020	1021	1022	
			, {6013, 11, -2, 0}, {6013, 11, -1, 0}, {6013, 11, 0, 0}// 1023	1024	1025	
			, {6013, 11, 1, 0}, {6013, 11, 2, 0}, {6013, 11, 3, 0}// 1026	1027	1028	
			, {6013, 5, 3, 0}, {6013, 5, 4, 0}, {6013, 6, 3, 0}// 1029	1030	1031	
			, {6013, 6, 4, 0}, {6013, 7, 3, 0}, {6013, 7, 4, 0}// 1032	1033	1034	
			, {6013, 8, 3, 0}, {6013, 8, 4, 0}, {6013, 9, 3, 0}// 1035	1036	1037	
			, {6013, 9, 4, 0}, {6013, 10, 3, 0}, {6013, 10, 4, 0}// 1038	1039	1040	
			, {6013, 11, 3, 0}, {6013, 11, 4, 0}, {6013, 1, 3, 0}// 1041	1042	1043	
			, {6013, 1, 4, 0}, {6013, 1, 5, 0}, {6013, 2, 3, 0}// 1044	1045	1046	
			, {6013, 2, 4, 0}, {6013, 2, 5, 0}, {6013, 3, 3, 0}// 1047	1048	1049	
			, {6013, 3, 4, 0}, {6013, 3, 5, 0}, {6013, 4, 3, 0}// 1050	1051	1052	
			, {6013, 4, 4, 0}, {6013, 4, 5, 0}, {6013, 5, 3, 0}// 1053	1054	1055	
			, {6013, 5, 4, 0}, {6013, 5, 5, 0}, {6013, 6, 3, 0}// 1056	1057	1058	
			, {6013, 6, 4, 0}, {6013, 6, 5, 0}, {6013, 7, 3, 0}// 1059	1060	1061	
			, {6013, 7, 4, 0}, {6013, 7, 5, 0}, {6013, 8, 3, 0}// 1062	1063	1064	
			, {6013, 8, 4, 0}, {6013, 8, 5, 0}, {6013, 9, 3, 0}// 1065	1066	1067	
			, {6013, 9, 4, 0}, {6013, 9, 5, 0}, {6013, 10, 3, 0}// 1068	1069	1070	
			, {6013, 10, 4, 0}, {6013, 10, 5, 0}, {6013, 11, 3, 0}// 1071	1072	1073	
			, {6013, 11, 4, 0}, {6013, 11, 5, 0}, {6013, 1, 6, 0}// 1074	1075	1076	
			, {6013, 1, 7, 0}, {6013, 1, 8, 0}, {6013, 1, 9, 0}// 1077	1078	1079	
			, {6013, 1, 10, 0}, {6013, 2, 6, 0}, {6013, 2, 7, 0}// 1080	1081	1082	
			, {6013, 2, 8, 0}, {6013, 2, 9, 0}, {6013, 2, 10, 0}// 1083	1084	1085	
			, {6013, 3, 6, 0}, {6013, 3, 7, 0}, {6013, 3, 8, 0}// 1086	1087	1088	
			, {6013, 3, 9, 0}, {6013, 3, 10, 0}, {6013, 4, 6, 0}// 1089	1090	1091	
			, {6013, 4, 7, 0}, {6013, 4, 8, 0}, {6013, 4, 9, 0}// 1092	1093	1094	
			, {6013, 4, 10, 0}, {6013, 5, 6, 0}, {6013, 5, 7, 0}// 1095	1096	1097	
			, {6013, 5, 8, 0}, {6013, 5, 9, 0}, {6013, 5, 10, 0}// 1098	1099	1100	
			, {6013, 6, 6, 0}, {6013, 6, 7, 0}, {6013, 6, 8, 0}// 1101	1102	1103	
			, {6013, 6, 9, 0}, {6013, 6, 10, 0}, {6013, 7, 6, 0}// 1104	1105	1106	
			, {6013, 7, 7, 0}, {6013, 7, 8, 0}, {6013, 7, 9, 0}// 1107	1108	1109	
			, {6013, 7, 10, 0}, {6013, 8, 6, 0}, {6013, 8, 7, 0}// 1110	1111	1112	
			, {6013, 8, 8, 0}, {6013, 8, 9, 0}, {6013, 8, 10, 0}// 1113	1114	1115	
			, {6013, 9, 6, 0}, {6013, 9, 7, 0}, {6013, 9, 8, 0}// 1116	1117	1118	
			, {6013, 9, 9, 0}, {6013, 9, 10, 0}, {6013, 10, 6, 0}// 1119	1120	1121	
			, {6013, 10, 7, 0}, {6013, 10, 8, 0}, {6013, 10, 9, 0}// 1122	1123	1124	
			, {6013, 10, 10, 0}, {6013, 11, 6, 0}, {6013, 11, 7, 0}// 1125	1126	1127	
			, {6013, 11, 8, 0}, {6013, 11, 9, 0}, {6013, 11, 10, 0}// 1128	1129	1130	
			, {7423, 3, 0, 0}, {7424, 3, 1, 0}, {7425, 3, 2, 0}// 1366	1367	1368	
			, {7426, 3, 3, 0}, {7427, 3, 4, 0}, {7422, 2, 0, 0}// 1369	1370	1371	
			, {7436, 2, 1, 0}, {7437, 2, 2, 0}, {7438, 2, 3, 0}// 1372	1373	1374	
			, {7428, 2, 4, 0}, {7409, 2, 5, 0}, {7421, 1, 0, 0}// 1375	1376	1377	
			, {7435, 1, 1, 0}, {7442, 1, 2, 0}, {7439, 1, 3, 0}// 1378	1379	1380	
			, {7429, 1, 4, 0}, {7410, 1, 5, 0}// 1381	1382	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new pvp_arenaAddonDeed();
			}
		}

		[ Constructable ]
		public pvp_arenaAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1308, -9, -4, 0, 1083, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 1308, -9, -4, 0, 1083, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 1308, -9, -3, 0, 1083, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 1308, -8, -4, 0, 1083, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 1308, -8, -3, 0, 1083, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 1308, -7, -4, 0, 1083, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 1308, -7, -3, 0, 1083, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 1308, -6, -4, 0, 1083, -1, "", 1);// 106
			AddComplexComponent( (BaseAddon) this, 1308, -6, -3, 0, 1083, -1, "", 1);// 107
			AddComplexComponent( (BaseAddon) this, 1308, -5, -4, 0, 1083, -1, "", 1);// 108
			AddComplexComponent( (BaseAddon) this, 1308, -5, -3, 0, 1083, -1, "", 1);// 109
			AddComplexComponent( (BaseAddon) this, 1308, -4, -4, 0, 1083, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 1308, -4, -3, 0, 1083, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 1308, -3, -4, 0, 1083, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 1308, -3, -3, 0, 1083, -1, "", 1);// 113
			AddComplexComponent( (BaseAddon) this, 1308, -2, -4, 0, 1083, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 1308, -2, -3, 0, 1083, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 1308, -1, -4, 0, 1083, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 1308, -1, -3, 0, 1083, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 1308, 0, -4, 0, 1083, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 1308, 0, -3, 0, 1083, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 1305, -9, -5, 0, 1083, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 1305, -8, -5, 0, 1083, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 1305, -7, -5, 0, 1083, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 1305, -6, -5, 0, 1083, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 1305, -5, -5, 0, 1083, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 1305, -4, -5, 0, 1083, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 1305, -3, -5, 0, 1083, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 1305, -2, -5, 0, 1083, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 1305, -1, -5, 0, 1083, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 1305, 0, -5, 0, 1083, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 1305, -9, -4, 0, 1083, -1, "", 1);// 130
			AddComplexComponent( (BaseAddon) this, 1305, -9, -3, 0, 1083, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 1305, -8, -4, 0, 1083, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 1305, -8, -3, 0, 1083, -1, "", 1);// 133
			AddComplexComponent( (BaseAddon) this, 1305, -7, -4, 0, 1083, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 1305, -7, -3, 0, 1083, -1, "", 1);// 135
			AddComplexComponent( (BaseAddon) this, 1305, -6, -4, 0, 1083, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 1305, -6, -3, 0, 1083, -1, "", 1);// 137
			AddComplexComponent( (BaseAddon) this, 1305, -5, -4, 0, 1083, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 1305, -5, -3, 0, 1083, -1, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 1305, -4, -4, 0, 1083, -1, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 1305, -4, -3, 0, 1083, -1, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 1305, -3, -4, 0, 1083, -1, "", 1);// 142
			AddComplexComponent( (BaseAddon) this, 1305, -3, -3, 0, 1083, -1, "", 1);// 143
			AddComplexComponent( (BaseAddon) this, 1305, -2, -4, 0, 1083, -1, "", 1);// 144
			AddComplexComponent( (BaseAddon) this, 1305, -2, -3, 0, 1083, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 1305, -1, -4, 0, 1083, -1, "", 1);// 146
			AddComplexComponent( (BaseAddon) this, 1305, -1, -3, 0, 1083, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 1305, 0, -4, 0, 1083, -1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 1305, 0, -3, 0, 1083, -1, "", 1);// 149
			AddComplexComponent( (BaseAddon) this, 1822, -10, -5, 0, 1083, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 1822, -10, -4, 0, 1083, -1, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 1822, -10, -3, 0, 1083, -1, "", 1);// 152
			AddComplexComponent( (BaseAddon) this, 1822, -10, -6, 0, 1083, -1, "", 1);// 153
			AddComplexComponent( (BaseAddon) this, 1822, -8, -6, 0, 1083, -1, "", 1);// 154
			AddComplexComponent( (BaseAddon) this, 1822, -7, -6, 0, 1083, -1, "", 1);// 155
			AddComplexComponent( (BaseAddon) this, 1822, -6, -6, 0, 1083, -1, "", 1);// 156
			AddComplexComponent( (BaseAddon) this, 1822, -5, -6, 0, 1083, -1, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 1822, -4, -6, 0, 1083, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 1822, -3, -6, 0, 1083, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 1822, -2, -6, 0, 1083, -1, "", 1);// 160
			AddComplexComponent( (BaseAddon) this, 1822, -1, -6, 0, 1083, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 1822, 0, -6, 0, 1083, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 1822, -10, -7, 0, 1083, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 1822, -9, -7, 0, 1083, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 1822, -8, -7, 0, 1083, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 1822, -7, -7, 0, 1083, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 1822, -6, -7, 0, 1083, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 1822, -5, -7, 0, 1083, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 1822, -4, -7, 0, 1083, -1, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 1822, -3, -7, 0, 1083, -1, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 1822, -2, -7, 0, 1083, -1, "", 1);// 171
			AddComplexComponent( (BaseAddon) this, 1822, -1, -7, 0, 1083, -1, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 1822, 0, -7, 0, 1083, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 1822, -10, -8, 0, 1083, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 1822, -9, -8, 0, 1083, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 1822, -8, -8, 0, 1083, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 1822, -7, -8, 0, 1083, -1, "", 1);// 177
			AddComplexComponent( (BaseAddon) this, 1822, -6, -8, 0, 1083, -1, "", 1);// 178
			AddComplexComponent( (BaseAddon) this, 1822, -5, -8, 0, 1083, -1, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 1822, -4, -8, 0, 1083, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 1822, -3, -8, 0, 1083, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 1822, -2, -8, 0, 1083, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 1822, -1, -8, 0, 1083, -1, "", 1);// 183
			AddComplexComponent( (BaseAddon) this, 1822, 0, -8, 0, 1083, -1, "", 1);// 184
			AddComplexComponent( (BaseAddon) this, 1822, -10, -8, 5, 1083, -1, "", 1);// 185
			AddComplexComponent( (BaseAddon) this, 1822, -9, -8, 5, 1083, -1, "", 1);// 186
			AddComplexComponent( (BaseAddon) this, 1822, -8, -8, 5, 1083, -1, "", 1);// 187
			AddComplexComponent( (BaseAddon) this, 1822, -7, -8, 5, 1083, -1, "", 1);// 188
			AddComplexComponent( (BaseAddon) this, 1822, -6, -8, 5, 1083, -1, "", 1);// 189
			AddComplexComponent( (BaseAddon) this, 1822, -5, -8, 5, 1083, -1, "", 1);// 190
			AddComplexComponent( (BaseAddon) this, 1822, -4, -8, 5, 1083, -1, "", 1);// 191
			AddComplexComponent( (BaseAddon) this, 1822, -3, -8, 5, 1083, -1, "", 1);// 192
			AddComplexComponent( (BaseAddon) this, 1822, -2, -8, 5, 1083, -1, "", 1);// 193
			AddComplexComponent( (BaseAddon) this, 1822, -1, -8, 5, 1083, -1, "", 1);// 194
			AddComplexComponent( (BaseAddon) this, 1822, 0, -8, 5, 1083, -1, "", 1);// 195
			AddComplexComponent( (BaseAddon) this, 1823, -9, -6, 0, 1083, -1, "", 1);// 196
			AddComplexComponent( (BaseAddon) this, 1822, -8, -7, 5, 1083, -1, "", 1);// 197
			AddComplexComponent( (BaseAddon) this, 1822, -7, -7, 5, 1083, -1, "", 1);// 198
			AddComplexComponent( (BaseAddon) this, 1822, -6, -7, 5, 1083, -1, "", 1);// 199
			AddComplexComponent( (BaseAddon) this, 1822, -5, -7, 5, 1083, -1, "", 1);// 200
			AddComplexComponent( (BaseAddon) this, 1822, -4, -7, 5, 1083, -1, "", 1);// 201
			AddComplexComponent( (BaseAddon) this, 1822, -3, -7, 5, 1083, -1, "", 1);// 202
			AddComplexComponent( (BaseAddon) this, 1822, -2, -7, 5, 1083, -1, "", 1);// 203
			AddComplexComponent( (BaseAddon) this, 1822, -1, -7, 5, 1083, -1, "", 1);// 204
			AddComplexComponent( (BaseAddon) this, 1822, 0, -7, 5, 1083, -1, "", 1);// 205
			AddComplexComponent( (BaseAddon) this, 1822, -8, -8, 10, 1083, -1, "", 1);// 206
			AddComplexComponent( (BaseAddon) this, 1822, -7, -8, 10, 1083, -1, "", 1);// 207
			AddComplexComponent( (BaseAddon) this, 1822, -6, -8, 10, 1083, -1, "", 1);// 208
			AddComplexComponent( (BaseAddon) this, 1822, -5, -8, 10, 1083, -1, "", 1);// 209
			AddComplexComponent( (BaseAddon) this, 1822, -4, -8, 10, 1083, -1, "", 1);// 210
			AddComplexComponent( (BaseAddon) this, 1822, -3, -8, 10, 1083, -1, "", 1);// 211
			AddComplexComponent( (BaseAddon) this, 1822, -2, -8, 10, 1083, -1, "", 1);// 212
			AddComplexComponent( (BaseAddon) this, 1822, -1, -8, 10, 1083, -1, "", 1);// 213
			AddComplexComponent( (BaseAddon) this, 1822, 0, -8, 10, 1083, -1, "", 1);// 214
			AddComplexComponent( (BaseAddon) this, 1823, -9, -7, 5, 1083, -1, "", 1);// 215
			AddComplexComponent( (BaseAddon) this, 131, -10, -8, 10, 1083, 1, "", 1);// 216
			AddComplexComponent( (BaseAddon) this, 4632, -8, -7, 10, 2173, -1, "", 1);// 217
			AddComplexComponent( (BaseAddon) this, 4632, -6, -7, 10, 2173, -1, "", 1);// 218
			AddComplexComponent( (BaseAddon) this, 4632, -7, -7, 10, 1096, -1, "", 1);// 219
			AddComplexComponent( (BaseAddon) this, 4632, -5, -7, 10, 1096, -1, "", 1);// 220
			AddComplexComponent( (BaseAddon) this, 4632, -4, -7, 10, 2173, -1, "", 1);// 221
			AddComplexComponent( (BaseAddon) this, 4632, -3, -7, 10, 1096, -1, "", 1);// 222
			AddComplexComponent( (BaseAddon) this, 4632, -2, -7, 10, 2173, -1, "", 1);// 223
			AddComplexComponent( (BaseAddon) this, 4632, -1, -7, 10, 1096, -1, "", 1);// 224
			AddComplexComponent( (BaseAddon) this, 4632, 0, -7, 10, 2173, -1, "", 1);// 225
			AddComplexComponent( (BaseAddon) this, 6477, -10, -8, 32, 0, -1, "DragonBrazier", 1);// 226
			AddComplexComponent( (BaseAddon) this, 1308, -9, -2, 0, 1083, -1, "", 1);// 411
			AddComplexComponent( (BaseAddon) this, 1308, -9, -1, 0, 1083, -1, "", 1);// 412
			AddComplexComponent( (BaseAddon) this, 1308, -9, 0, 0, 1083, -1, "", 1);// 413
			AddComplexComponent( (BaseAddon) this, 1308, -9, 1, 0, 1083, -1, "", 1);// 414
			AddComplexComponent( (BaseAddon) this, 1308, -9, 2, 0, 1083, -1, "", 1);// 415
			AddComplexComponent( (BaseAddon) this, 1308, -9, 3, 0, 1083, -1, "", 1);// 416
			AddComplexComponent( (BaseAddon) this, 1308, -9, 4, 0, 1083, -1, "", 1);// 417
			AddComplexComponent( (BaseAddon) this, 1308, -9, 5, 0, 1083, -1, "", 1);// 418
			AddComplexComponent( (BaseAddon) this, 1308, -9, 6, 0, 1083, -1, "", 1);// 419
			AddComplexComponent( (BaseAddon) this, 1308, -9, 7, 0, 1083, -1, "", 1);// 420
			AddComplexComponent( (BaseAddon) this, 1308, -9, 8, 0, 1083, -1, "", 1);// 421
			AddComplexComponent( (BaseAddon) this, 1308, -9, 9, 0, 1083, -1, "", 1);// 422
			AddComplexComponent( (BaseAddon) this, 1308, -9, 10, 0, 1083, -1, "", 1);// 423
			AddComplexComponent( (BaseAddon) this, 1308, -8, -2, 0, 1083, -1, "", 1);// 424
			AddComplexComponent( (BaseAddon) this, 1308, -8, -1, 0, 1083, -1, "", 1);// 425
			AddComplexComponent( (BaseAddon) this, 1308, -8, 0, 0, 1083, -1, "", 1);// 426
			AddComplexComponent( (BaseAddon) this, 1308, -8, 1, 0, 1083, -1, "", 1);// 427
			AddComplexComponent( (BaseAddon) this, 1308, -8, 2, 0, 1083, -1, "", 1);// 428
			AddComplexComponent( (BaseAddon) this, 1308, -8, 3, 0, 1083, -1, "", 1);// 429
			AddComplexComponent( (BaseAddon) this, 1308, -8, 4, 0, 1083, -1, "", 1);// 430
			AddComplexComponent( (BaseAddon) this, 1308, -8, 5, 0, 1083, -1, "", 1);// 431
			AddComplexComponent( (BaseAddon) this, 1308, -8, 6, 0, 1083, -1, "", 1);// 432
			AddComplexComponent( (BaseAddon) this, 1308, -8, 7, 0, 1083, -1, "", 1);// 433
			AddComplexComponent( (BaseAddon) this, 1308, -8, 8, 0, 1083, -1, "", 1);// 434
			AddComplexComponent( (BaseAddon) this, 1308, -8, 9, 0, 1083, -1, "", 1);// 435
			AddComplexComponent( (BaseAddon) this, 1308, -8, 10, 0, 1083, -1, "", 1);// 436
			AddComplexComponent( (BaseAddon) this, 1308, -7, -2, 0, 1083, -1, "", 1);// 437
			AddComplexComponent( (BaseAddon) this, 1308, -7, -1, 0, 1083, -1, "", 1);// 438
			AddComplexComponent( (BaseAddon) this, 1308, -7, 0, 0, 1083, -1, "", 1);// 439
			AddComplexComponent( (BaseAddon) this, 1308, -7, 1, 0, 1083, -1, "", 1);// 440
			AddComplexComponent( (BaseAddon) this, 1308, -7, 2, 0, 1083, -1, "", 1);// 441
			AddComplexComponent( (BaseAddon) this, 1308, -7, 3, 0, 1083, -1, "", 1);// 442
			AddComplexComponent( (BaseAddon) this, 1308, -7, 4, 0, 1083, -1, "", 1);// 443
			AddComplexComponent( (BaseAddon) this, 1308, -7, 5, 0, 1083, -1, "", 1);// 444
			AddComplexComponent( (BaseAddon) this, 1308, -7, 6, 0, 1083, -1, "", 1);// 445
			AddComplexComponent( (BaseAddon) this, 1308, -7, 7, 0, 1083, -1, "", 1);// 446
			AddComplexComponent( (BaseAddon) this, 1308, -7, 8, 0, 1083, -1, "", 1);// 447
			AddComplexComponent( (BaseAddon) this, 1308, -7, 9, 0, 1083, -1, "", 1);// 448
			AddComplexComponent( (BaseAddon) this, 1308, -7, 10, 0, 1083, -1, "", 1);// 449
			AddComplexComponent( (BaseAddon) this, 1308, -6, -2, 0, 1083, -1, "", 1);// 450
			AddComplexComponent( (BaseAddon) this, 1308, -6, -1, 0, 1083, -1, "", 1);// 451
			AddComplexComponent( (BaseAddon) this, 1308, -6, 0, 0, 1083, -1, "", 1);// 452
			AddComplexComponent( (BaseAddon) this, 1308, -6, 1, 0, 1083, -1, "", 1);// 453
			AddComplexComponent( (BaseAddon) this, 1308, -6, 2, 0, 1083, -1, "", 1);// 454
			AddComplexComponent( (BaseAddon) this, 1308, -6, 3, 0, 1083, -1, "", 1);// 455
			AddComplexComponent( (BaseAddon) this, 1308, -6, 4, 0, 1083, -1, "", 1);// 456
			AddComplexComponent( (BaseAddon) this, 1308, -6, 5, 0, 1083, -1, "", 1);// 457
			AddComplexComponent( (BaseAddon) this, 1308, -6, 6, 0, 1083, -1, "", 1);// 458
			AddComplexComponent( (BaseAddon) this, 1308, -6, 7, 0, 1083, -1, "", 1);// 459
			AddComplexComponent( (BaseAddon) this, 1308, -6, 8, 0, 1083, -1, "", 1);// 460
			AddComplexComponent( (BaseAddon) this, 1308, -6, 9, 0, 1083, -1, "", 1);// 461
			AddComplexComponent( (BaseAddon) this, 1308, -6, 10, 0, 1083, -1, "", 1);// 462
			AddComplexComponent( (BaseAddon) this, 1308, -5, -2, 0, 1083, -1, "", 1);// 463
			AddComplexComponent( (BaseAddon) this, 1308, -5, -1, 0, 1083, -1, "", 1);// 464
			AddComplexComponent( (BaseAddon) this, 1308, -5, 0, 0, 1083, -1, "", 1);// 465
			AddComplexComponent( (BaseAddon) this, 1308, -5, 1, 0, 1083, -1, "", 1);// 466
			AddComplexComponent( (BaseAddon) this, 1308, -5, 2, 0, 1083, -1, "", 1);// 467
			AddComplexComponent( (BaseAddon) this, 1308, -5, 3, 0, 1083, -1, "", 1);// 468
			AddComplexComponent( (BaseAddon) this, 1308, -5, 4, 0, 1083, -1, "", 1);// 469
			AddComplexComponent( (BaseAddon) this, 1308, -5, 5, 0, 1083, -1, "", 1);// 470
			AddComplexComponent( (BaseAddon) this, 1308, -5, 6, 0, 1083, -1, "", 1);// 471
			AddComplexComponent( (BaseAddon) this, 1308, -5, 7, 0, 1083, -1, "", 1);// 472
			AddComplexComponent( (BaseAddon) this, 1308, -5, 8, 0, 1083, -1, "", 1);// 473
			AddComplexComponent( (BaseAddon) this, 1308, -5, 9, 0, 1083, -1, "", 1);// 474
			AddComplexComponent( (BaseAddon) this, 1308, -5, 10, 0, 1083, -1, "", 1);// 475
			AddComplexComponent( (BaseAddon) this, 1308, -4, -2, 0, 1083, -1, "", 1);// 476
			AddComplexComponent( (BaseAddon) this, 1308, -4, -1, 0, 1083, -1, "", 1);// 477
			AddComplexComponent( (BaseAddon) this, 1308, -4, 0, 0, 1083, -1, "", 1);// 478
			AddComplexComponent( (BaseAddon) this, 1308, -4, 1, 0, 1083, -1, "", 1);// 479
			AddComplexComponent( (BaseAddon) this, 1308, -4, 2, 0, 1083, -1, "", 1);// 480
			AddComplexComponent( (BaseAddon) this, 1308, -4, 3, 0, 1083, -1, "", 1);// 481
			AddComplexComponent( (BaseAddon) this, 1308, -4, 4, 0, 1083, -1, "", 1);// 482
			AddComplexComponent( (BaseAddon) this, 1308, -4, 5, 0, 1083, -1, "", 1);// 483
			AddComplexComponent( (BaseAddon) this, 1308, -4, 6, 0, 1083, -1, "", 1);// 484
			AddComplexComponent( (BaseAddon) this, 1308, -4, 7, 0, 1083, -1, "", 1);// 485
			AddComplexComponent( (BaseAddon) this, 1308, -4, 8, 0, 1083, -1, "", 1);// 486
			AddComplexComponent( (BaseAddon) this, 1308, -4, 9, 0, 1083, -1, "", 1);// 487
			AddComplexComponent( (BaseAddon) this, 1308, -4, 10, 0, 1083, -1, "", 1);// 488
			AddComplexComponent( (BaseAddon) this, 1308, -3, -2, 0, 1083, -1, "", 1);// 489
			AddComplexComponent( (BaseAddon) this, 1308, -3, -1, 0, 1083, -1, "", 1);// 490
			AddComplexComponent( (BaseAddon) this, 1308, -3, 0, 0, 1083, -1, "", 1);// 491
			AddComplexComponent( (BaseAddon) this, 1308, -3, 1, 0, 1083, -1, "", 1);// 492
			AddComplexComponent( (BaseAddon) this, 1308, -3, 2, 0, 1083, -1, "", 1);// 493
			AddComplexComponent( (BaseAddon) this, 1308, -3, 3, 0, 1083, -1, "", 1);// 494
			AddComplexComponent( (BaseAddon) this, 1308, -3, 4, 0, 1083, -1, "", 1);// 495
			AddComplexComponent( (BaseAddon) this, 1308, -3, 5, 0, 1083, -1, "", 1);// 496
			AddComplexComponent( (BaseAddon) this, 1308, -3, 6, 0, 1083, -1, "", 1);// 497
			AddComplexComponent( (BaseAddon) this, 1308, -3, 7, 0, 1083, -1, "", 1);// 498
			AddComplexComponent( (BaseAddon) this, 1308, -3, 8, 0, 1083, -1, "", 1);// 499
			AddComplexComponent( (BaseAddon) this, 1308, -3, 9, 0, 1083, -1, "", 1);// 500
			AddComplexComponent( (BaseAddon) this, 1308, -3, 10, 0, 1083, -1, "", 1);// 501
			AddComplexComponent( (BaseAddon) this, 1308, -2, -2, 0, 1083, -1, "", 1);// 502
			AddComplexComponent( (BaseAddon) this, 1308, -2, -1, 0, 1083, -1, "", 1);// 503
			AddComplexComponent( (BaseAddon) this, 1308, -2, 0, 0, 1083, -1, "", 1);// 504
			AddComplexComponent( (BaseAddon) this, 1308, -2, 1, 0, 1083, -1, "", 1);// 505
			AddComplexComponent( (BaseAddon) this, 1308, -2, 2, 0, 1083, -1, "", 1);// 506
			AddComplexComponent( (BaseAddon) this, 1308, -2, 3, 0, 1083, -1, "", 1);// 507
			AddComplexComponent( (BaseAddon) this, 1308, -2, 4, 0, 1083, -1, "", 1);// 508
			AddComplexComponent( (BaseAddon) this, 1308, -2, 5, 0, 1083, -1, "", 1);// 509
			AddComplexComponent( (BaseAddon) this, 1308, -2, 6, 0, 1083, -1, "", 1);// 510
			AddComplexComponent( (BaseAddon) this, 1308, -2, 7, 0, 1083, -1, "", 1);// 511
			AddComplexComponent( (BaseAddon) this, 1308, -2, 8, 0, 1083, -1, "", 1);// 512
			AddComplexComponent( (BaseAddon) this, 1308, -2, 9, 0, 1083, -1, "", 1);// 513
			AddComplexComponent( (BaseAddon) this, 1308, -2, 10, 0, 1083, -1, "", 1);// 514
			AddComplexComponent( (BaseAddon) this, 1308, -1, -2, 0, 1083, -1, "", 1);// 515
			AddComplexComponent( (BaseAddon) this, 1308, -1, -1, 0, 1083, -1, "", 1);// 516
			AddComplexComponent( (BaseAddon) this, 1308, -1, 0, 0, 1083, -1, "", 1);// 517
			AddComplexComponent( (BaseAddon) this, 1308, -1, 1, 0, 1083, -1, "", 1);// 518
			AddComplexComponent( (BaseAddon) this, 1308, -1, 2, 0, 1083, -1, "", 1);// 519
			AddComplexComponent( (BaseAddon) this, 1308, -1, 3, 0, 1083, -1, "", 1);// 520
			AddComplexComponent( (BaseAddon) this, 1308, -1, 4, 0, 1083, -1, "", 1);// 521
			AddComplexComponent( (BaseAddon) this, 1308, -1, 5, 0, 1083, -1, "", 1);// 522
			AddComplexComponent( (BaseAddon) this, 1308, -1, 6, 0, 1083, -1, "", 1);// 523
			AddComplexComponent( (BaseAddon) this, 1308, -1, 7, 0, 1083, -1, "", 1);// 524
			AddComplexComponent( (BaseAddon) this, 1308, -1, 8, 0, 1083, -1, "", 1);// 525
			AddComplexComponent( (BaseAddon) this, 1308, -1, 9, 0, 1083, -1, "", 1);// 526
			AddComplexComponent( (BaseAddon) this, 1308, -1, 10, 0, 1083, -1, "", 1);// 527
			AddComplexComponent( (BaseAddon) this, 1308, 0, -2, 0, 1083, -1, "", 1);// 528
			AddComplexComponent( (BaseAddon) this, 1308, 0, -1, 0, 1083, -1, "", 1);// 529
			AddComplexComponent( (BaseAddon) this, 1308, 0, 0, 0, 1083, -1, "", 1);// 530
			AddComplexComponent( (BaseAddon) this, 1308, 0, 1, 0, 1083, -1, "", 1);// 531
			AddComplexComponent( (BaseAddon) this, 1308, 0, 2, 0, 1083, -1, "", 1);// 532
			AddComplexComponent( (BaseAddon) this, 1308, 0, 3, 0, 1083, -1, "", 1);// 533
			AddComplexComponent( (BaseAddon) this, 1308, 0, 4, 0, 1083, -1, "", 1);// 534
			AddComplexComponent( (BaseAddon) this, 1308, 0, 5, 0, 1083, -1, "", 1);// 535
			AddComplexComponent( (BaseAddon) this, 1308, 0, 6, 0, 1083, -1, "", 1);// 536
			AddComplexComponent( (BaseAddon) this, 1308, 0, 7, 0, 1083, -1, "", 1);// 537
			AddComplexComponent( (BaseAddon) this, 1308, 0, 8, 0, 1083, -1, "", 1);// 538
			AddComplexComponent( (BaseAddon) this, 1308, 0, 9, 0, 1083, -1, "", 1);// 539
			AddComplexComponent( (BaseAddon) this, 1308, 0, 10, 0, 1083, -1, "", 1);// 540
			AddComplexComponent( (BaseAddon) this, 1305, -9, -2, 0, 1083, -1, "", 1);// 541
			AddComplexComponent( (BaseAddon) this, 1305, -9, -1, 0, 1083, -1, "", 1);// 542
			AddComplexComponent( (BaseAddon) this, 1305, -9, 0, 0, 1083, -1, "", 1);// 543
			AddComplexComponent( (BaseAddon) this, 1305, -9, 1, 0, 1083, -1, "", 1);// 544
			AddComplexComponent( (BaseAddon) this, 1305, -9, 2, 0, 1083, -1, "", 1);// 545
			AddComplexComponent( (BaseAddon) this, 1305, -9, 3, 0, 1083, -1, "", 1);// 546
			AddComplexComponent( (BaseAddon) this, 1305, -9, 4, 0, 1083, -1, "", 1);// 547
			AddComplexComponent( (BaseAddon) this, 1305, -9, 5, 0, 1083, -1, "", 1);// 548
			AddComplexComponent( (BaseAddon) this, 1305, -9, 6, 0, 1083, -1, "", 1);// 549
			AddComplexComponent( (BaseAddon) this, 1305, -9, 7, 0, 1083, -1, "", 1);// 550
			AddComplexComponent( (BaseAddon) this, 1305, -9, 8, 0, 1083, -1, "", 1);// 551
			AddComplexComponent( (BaseAddon) this, 1305, -9, 9, 0, 1083, -1, "", 1);// 552
			AddComplexComponent( (BaseAddon) this, 1305, -9, 10, 0, 1083, -1, "", 1);// 553
			AddComplexComponent( (BaseAddon) this, 1305, -8, -2, 0, 1083, -1, "", 1);// 554
			AddComplexComponent( (BaseAddon) this, 1305, -8, -1, 0, 1083, -1, "", 1);// 555
			AddComplexComponent( (BaseAddon) this, 1305, -8, 0, 0, 1083, -1, "", 1);// 556
			AddComplexComponent( (BaseAddon) this, 1305, -8, 1, 0, 1083, -1, "", 1);// 557
			AddComplexComponent( (BaseAddon) this, 1305, -8, 2, 0, 2174, -1, "", 1);// 558
			AddComplexComponent( (BaseAddon) this, 1305, -8, 3, 0, 2174, -1, "", 1);// 559
			AddComplexComponent( (BaseAddon) this, 1305, -8, 4, 0, 1083, -1, "", 1);// 560
			AddComplexComponent( (BaseAddon) this, 1305, -8, 5, 0, 1083, -1, "", 1);// 561
			AddComplexComponent( (BaseAddon) this, 1305, -8, 6, 0, 1083, -1, "", 1);// 562
			AddComplexComponent( (BaseAddon) this, 1305, -8, 7, 0, 1083, -1, "", 1);// 563
			AddComplexComponent( (BaseAddon) this, 1305, -8, 8, 0, 1083, -1, "", 1);// 564
			AddComplexComponent( (BaseAddon) this, 1305, -8, 9, 0, 1083, -1, "", 1);// 565
			AddComplexComponent( (BaseAddon) this, 1305, -8, 10, 0, 1083, -1, "", 1);// 566
			AddComplexComponent( (BaseAddon) this, 1305, -7, -2, 0, 1083, -1, "", 1);// 567
			AddComplexComponent( (BaseAddon) this, 1305, -7, -1, 0, 1083, -1, "", 1);// 568
			AddComplexComponent( (BaseAddon) this, 1305, -7, 0, 0, 1083, -1, "", 1);// 569
			AddComplexComponent( (BaseAddon) this, 1305, -7, 1, 0, 1083, -1, "", 1);// 570
			AddComplexComponent( (BaseAddon) this, 1305, -7, 2, 0, 2174, -1, "", 1);// 571
			AddComplexComponent( (BaseAddon) this, 1305, -7, 3, 0, 2174, -1, "", 1);// 572
			AddComplexComponent( (BaseAddon) this, 1305, -7, 4, 0, 1083, -1, "", 1);// 573
			AddComplexComponent( (BaseAddon) this, 1305, -7, 5, 0, 1083, -1, "", 1);// 574
			AddComplexComponent( (BaseAddon) this, 1305, -7, 6, 0, 1083, -1, "", 1);// 575
			AddComplexComponent( (BaseAddon) this, 1305, -7, 7, 0, 1083, -1, "", 1);// 576
			AddComplexComponent( (BaseAddon) this, 1305, -7, 8, 0, 1083, -1, "", 1);// 577
			AddComplexComponent( (BaseAddon) this, 1305, -7, 9, 0, 1083, -1, "", 1);// 578
			AddComplexComponent( (BaseAddon) this, 1305, -7, 10, 0, 1083, -1, "", 1);// 579
			AddComplexComponent( (BaseAddon) this, 1305, -6, -2, 0, 1083, -1, "", 1);// 580
			AddComplexComponent( (BaseAddon) this, 1305, -6, -1, 0, 1083, -1, "", 1);// 581
			AddComplexComponent( (BaseAddon) this, 1305, -6, 0, 0, 1083, -1, "", 1);// 582
			AddComplexComponent( (BaseAddon) this, 1305, -6, 1, 0, 1083, -1, "", 1);// 583
			AddComplexComponent( (BaseAddon) this, 1305, -6, 2, 0, 1083, -1, "", 1);// 584
			AddComplexComponent( (BaseAddon) this, 1305, -6, 3, 0, 1083, -1, "", 1);// 585
			AddComplexComponent( (BaseAddon) this, 1305, -6, 4, 0, 1083, -1, "", 1);// 586
			AddComplexComponent( (BaseAddon) this, 1305, -6, 5, 0, 1083, -1, "", 1);// 587
			AddComplexComponent( (BaseAddon) this, 1305, -6, 6, 0, 1083, -1, "", 1);// 588
			AddComplexComponent( (BaseAddon) this, 1305, -6, 7, 0, 1083, -1, "", 1);// 589
			AddComplexComponent( (BaseAddon) this, 1305, -6, 8, 0, 1083, -1, "", 1);// 590
			AddComplexComponent( (BaseAddon) this, 1305, -6, 9, 0, 1083, -1, "", 1);// 591
			AddComplexComponent( (BaseAddon) this, 1305, -6, 10, 0, 1083, -1, "", 1);// 592
			AddComplexComponent( (BaseAddon) this, 1305, -5, -2, 0, 1083, -1, "", 1);// 593
			AddComplexComponent( (BaseAddon) this, 1305, -5, -1, 0, 1083, -1, "", 1);// 594
			AddComplexComponent( (BaseAddon) this, 1305, -5, 0, 0, 1083, -1, "", 1);// 595
			AddComplexComponent( (BaseAddon) this, 1305, -5, 1, 0, 1083, -1, "", 1);// 596
			AddComplexComponent( (BaseAddon) this, 1305, -5, 2, 0, 1083, -1, "", 1);// 597
			AddComplexComponent( (BaseAddon) this, 1305, -5, 3, 0, 1083, -1, "", 1);// 598
			AddComplexComponent( (BaseAddon) this, 1305, -5, 4, 0, 1083, -1, "", 1);// 599
			AddComplexComponent( (BaseAddon) this, 1305, -5, 5, 0, 1083, -1, "", 1);// 600
			AddComplexComponent( (BaseAddon) this, 1305, -5, 6, 0, 1083, -1, "", 1);// 601
			AddComplexComponent( (BaseAddon) this, 1305, -5, 7, 0, 1083, -1, "", 1);// 602
			AddComplexComponent( (BaseAddon) this, 1305, -5, 8, 0, 1083, -1, "", 1);// 603
			AddComplexComponent( (BaseAddon) this, 1305, -5, 9, 0, 1083, -1, "", 1);// 604
			AddComplexComponent( (BaseAddon) this, 1305, -5, 10, 0, 1083, -1, "", 1);// 605
			AddComplexComponent( (BaseAddon) this, 1305, -4, -2, 0, 1083, -1, "", 1);// 606
			AddComplexComponent( (BaseAddon) this, 1305, -4, -1, 0, 1083, -1, "", 1);// 607
			AddComplexComponent( (BaseAddon) this, 1305, -4, 0, 0, 1083, -1, "", 1);// 608
			AddComplexComponent( (BaseAddon) this, 1305, -4, 1, 0, 1083, -1, "", 1);// 609
			AddComplexComponent( (BaseAddon) this, 1305, -4, 2, 0, 1083, -1, "", 1);// 610
			AddComplexComponent( (BaseAddon) this, 1305, -4, 3, 0, 1083, -1, "", 1);// 611
			AddComplexComponent( (BaseAddon) this, 1305, -4, 4, 0, 1083, -1, "", 1);// 612
			AddComplexComponent( (BaseAddon) this, 1305, -4, 5, 0, 1083, -1, "", 1);// 613
			AddComplexComponent( (BaseAddon) this, 1305, -4, 6, 0, 1083, -1, "", 1);// 614
			AddComplexComponent( (BaseAddon) this, 1305, -4, 7, 0, 1083, -1, "", 1);// 615
			AddComplexComponent( (BaseAddon) this, 1305, -4, 8, 0, 1083, -1, "", 1);// 616
			AddComplexComponent( (BaseAddon) this, 1305, -4, 9, 0, 1083, -1, "", 1);// 617
			AddComplexComponent( (BaseAddon) this, 1305, -4, 10, 0, 1083, -1, "", 1);// 618
			AddComplexComponent( (BaseAddon) this, 1305, -3, -2, 0, 1083, -1, "", 1);// 619
			AddComplexComponent( (BaseAddon) this, 1305, -3, -1, 0, 1083, -1, "", 1);// 620
			AddComplexComponent( (BaseAddon) this, 1305, -3, 0, 0, 1083, -1, "", 1);// 621
			AddComplexComponent( (BaseAddon) this, 1305, -3, 1, 0, 1083, -1, "", 1);// 622
			AddComplexComponent( (BaseAddon) this, 1305, -3, 2, 0, 1083, -1, "", 1);// 623
			AddComplexComponent( (BaseAddon) this, 1305, -3, 3, 0, 1083, -1, "", 1);// 624
			AddComplexComponent( (BaseAddon) this, 1305, -3, 4, 0, 1083, -1, "", 1);// 625
			AddComplexComponent( (BaseAddon) this, 1305, -3, 5, 0, 1083, -1, "", 1);// 626
			AddComplexComponent( (BaseAddon) this, 1305, -3, 6, 0, 1083, -1, "", 1);// 627
			AddComplexComponent( (BaseAddon) this, 1305, -3, 7, 0, 1083, -1, "", 1);// 628
			AddComplexComponent( (BaseAddon) this, 1305, -3, 8, 0, 1083, -1, "", 1);// 629
			AddComplexComponent( (BaseAddon) this, 1305, -3, 9, 0, 1083, -1, "", 1);// 630
			AddComplexComponent( (BaseAddon) this, 1305, -3, 10, 0, 1083, -1, "", 1);// 631
			AddComplexComponent( (BaseAddon) this, 1305, -2, -2, 0, 1083, -1, "", 1);// 632
			AddComplexComponent( (BaseAddon) this, 1305, -2, -1, 0, 1083, -1, "", 1);// 633
			AddComplexComponent( (BaseAddon) this, 1305, -2, 0, 0, 1083, -1, "", 1);// 634
			AddComplexComponent( (BaseAddon) this, 1305, -2, 1, 0, 1083, -1, "", 1);// 635
			AddComplexComponent( (BaseAddon) this, 1305, -2, 2, 0, 1083, -1, "", 1);// 636
			AddComplexComponent( (BaseAddon) this, 1305, -2, 3, 0, 1083, -1, "", 1);// 637
			AddComplexComponent( (BaseAddon) this, 1305, -2, 4, 0, 1083, -1, "", 1);// 638
			AddComplexComponent( (BaseAddon) this, 1305, -2, 5, 0, 1083, -1, "", 1);// 639
			AddComplexComponent( (BaseAddon) this, 1305, -2, 6, 0, 1083, -1, "", 1);// 640
			AddComplexComponent( (BaseAddon) this, 1305, -2, 7, 0, 1083, -1, "", 1);// 641
			AddComplexComponent( (BaseAddon) this, 1305, -2, 8, 0, 1083, -1, "", 1);// 642
			AddComplexComponent( (BaseAddon) this, 1305, -2, 9, 0, 1083, -1, "", 1);// 643
			AddComplexComponent( (BaseAddon) this, 1305, -2, 10, 0, 1083, -1, "", 1);// 644
			AddComplexComponent( (BaseAddon) this, 1305, -1, -2, 0, 1083, -1, "", 1);// 645
			AddComplexComponent( (BaseAddon) this, 1305, -1, -1, 0, 1083, -1, "", 1);// 646
			AddComplexComponent( (BaseAddon) this, 1305, -1, 0, 0, 1083, -1, "", 1);// 647
			AddComplexComponent( (BaseAddon) this, 1305, -1, 1, 0, 1083, -1, "", 1);// 648
			AddComplexComponent( (BaseAddon) this, 1305, -1, 2, 0, 1083, -1, "", 1);// 649
			AddComplexComponent( (BaseAddon) this, 1305, -1, 3, 0, 1083, -1, "", 1);// 650
			AddComplexComponent( (BaseAddon) this, 1305, -1, 4, 0, 1083, -1, "", 1);// 651
			AddComplexComponent( (BaseAddon) this, 1305, -1, 5, 0, 1083, -1, "", 1);// 652
			AddComplexComponent( (BaseAddon) this, 1305, -1, 6, 0, 1083, -1, "", 1);// 653
			AddComplexComponent( (BaseAddon) this, 1305, -1, 7, 0, 1083, -1, "", 1);// 654
			AddComplexComponent( (BaseAddon) this, 1305, -1, 8, 0, 1083, -1, "", 1);// 655
			AddComplexComponent( (BaseAddon) this, 1305, -1, 9, 0, 1083, -1, "", 1);// 656
			AddComplexComponent( (BaseAddon) this, 1305, -1, 10, 0, 1083, -1, "", 1);// 657
			AddComplexComponent( (BaseAddon) this, 1305, 0, -2, 0, 1083, -1, "", 1);// 658
			AddComplexComponent( (BaseAddon) this, 1305, 0, -1, 0, 1083, -1, "", 1);// 659
			AddComplexComponent( (BaseAddon) this, 1305, 0, 0, 0, 1083, -1, "", 1);// 660
			AddComplexComponent( (BaseAddon) this, 1305, 0, 1, 0, 1083, -1, "", 1);// 661
			AddComplexComponent( (BaseAddon) this, 1305, 0, 2, 0, 1083, -1, "", 1);// 662
			AddComplexComponent( (BaseAddon) this, 1305, 0, 3, 0, 1083, -1, "", 1);// 663
			AddComplexComponent( (BaseAddon) this, 1305, 0, 4, 0, 1083, -1, "", 1);// 664
			AddComplexComponent( (BaseAddon) this, 1305, 0, 5, 0, 1083, -1, "", 1);// 665
			AddComplexComponent( (BaseAddon) this, 1305, 0, 6, 0, 1083, -1, "", 1);// 666
			AddComplexComponent( (BaseAddon) this, 1305, 0, 7, 0, 1083, -1, "", 1);// 667
			AddComplexComponent( (BaseAddon) this, 1305, 0, 8, 0, 1083, -1, "", 1);// 668
			AddComplexComponent( (BaseAddon) this, 1305, 0, 9, 0, 1083, -1, "", 1);// 669
			AddComplexComponent( (BaseAddon) this, 1305, 0, 10, 0, 1083, -1, "", 1);// 670
			AddComplexComponent( (BaseAddon) this, 1822, -10, -2, 0, 1083, -1, "", 1);// 688
			AddComplexComponent( (BaseAddon) this, 1822, -10, -1, 0, 1083, -1, "", 1);// 689
			AddComplexComponent( (BaseAddon) this, 1822, -10, 0, 0, 1083, -1, "", 1);// 690
			AddComplexComponent( (BaseAddon) this, 1822, -10, 1, 0, 1083, -1, "", 1);// 691
			AddComplexComponent( (BaseAddon) this, 1822, -10, 2, 0, 1083, -1, "", 1);// 692
			AddComplexComponent( (BaseAddon) this, 1822, -10, 3, 0, 1083, -1, "", 1);// 693
			AddComplexComponent( (BaseAddon) this, 1822, -10, 4, 0, 1083, -1, "", 1);// 694
			AddComplexComponent( (BaseAddon) this, 1822, -10, 5, 0, 1083, -1, "", 1);// 695
			AddComplexComponent( (BaseAddon) this, 1822, -10, 6, 0, 1083, -1, "", 1);// 696
			AddComplexComponent( (BaseAddon) this, 1822, -10, 7, 0, 1083, -1, "", 1);// 697
			AddComplexComponent( (BaseAddon) this, 1822, -10, 8, 0, 1083, -1, "", 1);// 698
			AddComplexComponent( (BaseAddon) this, 1822, -10, 9, 0, 1083, -1, "", 1);// 699
			AddComplexComponent( (BaseAddon) this, 1822, -10, 10, 0, 1083, -1, "", 1);// 700
			AddComplexComponent( (BaseAddon) this, 1822, -9, 10, 0, 1083, -1, "", 1);// 701
			AddComplexComponent( (BaseAddon) this, 1822, -8, 10, 0, 1083, -1, "", 1);// 702
			AddComplexComponent( (BaseAddon) this, 1822, -7, 10, 0, 1083, -1, "", 1);// 703
			AddComplexComponent( (BaseAddon) this, 1822, -6, 10, 0, 1083, -1, "", 1);// 704
			AddComplexComponent( (BaseAddon) this, 1822, -5, 10, 0, 1083, -1, "", 1);// 705
			AddComplexComponent( (BaseAddon) this, 1822, -4, 10, 0, 1083, -1, "", 1);// 706
			AddComplexComponent( (BaseAddon) this, 1822, -3, 10, 0, 1083, -1, "", 1);// 707
			AddComplexComponent( (BaseAddon) this, 1822, -2, 10, 0, 1083, -1, "", 1);// 708
			AddComplexComponent( (BaseAddon) this, 1822, -1, 10, 0, 1083, -1, "", 1);// 709
			AddComplexComponent( (BaseAddon) this, 4633, -8, 3, 0, 1096, -1, "", 1);// 710
			AddComplexComponent( (BaseAddon) this, 4633, -8, 2, 0, 1096, -1, "", 1);// 711
			AddComplexComponent( (BaseAddon) this, 131, -10, 10, 5, 1083, 1, "", 1);// 712
			AddComplexComponent( (BaseAddon) this, 131, -1, 10, 5, 1083, 1, "", 1);// 713
			AddComplexComponent( (BaseAddon) this, 6477, -10, 10, 27, 0, -1, "DragonBrazier", 1);// 714
			AddComplexComponent( (BaseAddon) this, 6477, -1, 10, 27, 0, -1, "DragonBrazier", 1);// 715
			AddComplexComponent( (BaseAddon) this, 1308, 9, -4, 0, 1083, -1, "", 1);// 820
			AddComplexComponent( (BaseAddon) this, 1308, 1, -4, 0, 1083, -1, "", 1);// 821
			AddComplexComponent( (BaseAddon) this, 1308, 1, -3, 0, 1083, -1, "", 1);// 822
			AddComplexComponent( (BaseAddon) this, 1308, 2, -4, 0, 1083, -1, "", 1);// 823
			AddComplexComponent( (BaseAddon) this, 1308, 2, -3, 0, 1083, -1, "", 1);// 824
			AddComplexComponent( (BaseAddon) this, 1308, 3, -4, 0, 1083, -1, "", 1);// 825
			AddComplexComponent( (BaseAddon) this, 1308, 3, -3, 0, 1083, -1, "", 1);// 826
			AddComplexComponent( (BaseAddon) this, 1308, 4, -4, 0, 1083, -1, "", 1);// 827
			AddComplexComponent( (BaseAddon) this, 1308, 4, -3, 0, 1083, -1, "", 1);// 828
			AddComplexComponent( (BaseAddon) this, 1308, 5, -4, 0, 1083, -1, "", 1);// 829
			AddComplexComponent( (BaseAddon) this, 1308, 5, -3, 0, 1083, -1, "", 1);// 830
			AddComplexComponent( (BaseAddon) this, 1308, 6, -4, 0, 1083, -1, "", 1);// 831
			AddComplexComponent( (BaseAddon) this, 1308, 6, -3, 0, 1083, -1, "", 1);// 832
			AddComplexComponent( (BaseAddon) this, 1308, 7, -4, 0, 1083, -1, "", 1);// 833
			AddComplexComponent( (BaseAddon) this, 1308, 7, -3, 0, 1083, -1, "", 1);// 834
			AddComplexComponent( (BaseAddon) this, 1308, 8, -4, 0, 1083, -1, "", 1);// 835
			AddComplexComponent( (BaseAddon) this, 1308, 8, -3, 0, 1083, -1, "", 1);// 836
			AddComplexComponent( (BaseAddon) this, 1308, 9, -4, 0, 1083, -1, "", 1);// 837
			AddComplexComponent( (BaseAddon) this, 1308, 9, -3, 0, 1083, -1, "", 1);// 838
			AddComplexComponent( (BaseAddon) this, 1305, 1, -5, 0, 1083, -1, "", 1);// 839
			AddComplexComponent( (BaseAddon) this, 1305, 2, -5, 0, 1083, -1, "", 1);// 840
			AddComplexComponent( (BaseAddon) this, 1305, 3, -5, 0, 1083, -1, "", 1);// 841
			AddComplexComponent( (BaseAddon) this, 1305, 4, -5, 0, 1083, -1, "", 1);// 842
			AddComplexComponent( (BaseAddon) this, 1305, 5, -5, 0, 1083, -1, "", 1);// 843
			AddComplexComponent( (BaseAddon) this, 1305, 6, -5, 0, 1083, -1, "", 1);// 844
			AddComplexComponent( (BaseAddon) this, 1305, 7, -5, 0, 1083, -1, "", 1);// 845
			AddComplexComponent( (BaseAddon) this, 1305, 8, -5, 0, 1083, -1, "", 1);// 846
			AddComplexComponent( (BaseAddon) this, 1305, 9, -5, 0, 1083, -1, "", 1);// 847
			AddComplexComponent( (BaseAddon) this, 1305, 1, -4, 0, 1083, -1, "", 1);// 848
			AddComplexComponent( (BaseAddon) this, 1305, 1, -3, 0, 1083, -1, "", 1);// 849
			AddComplexComponent( (BaseAddon) this, 1305, 2, -4, 0, 1083, -1, "", 1);// 850
			AddComplexComponent( (BaseAddon) this, 1305, 2, -3, 0, 1083, -1, "", 1);// 851
			AddComplexComponent( (BaseAddon) this, 1305, 3, -4, 0, 1083, -1, "", 1);// 852
			AddComplexComponent( (BaseAddon) this, 1305, 3, -3, 0, 1083, -1, "", 1);// 853
			AddComplexComponent( (BaseAddon) this, 1305, 4, -4, 0, 1083, -1, "", 1);// 854
			AddComplexComponent( (BaseAddon) this, 1305, 4, -3, 0, 1083, -1, "", 1);// 855
			AddComplexComponent( (BaseAddon) this, 1305, 5, -4, 0, 1083, -1, "", 1);// 856
			AddComplexComponent( (BaseAddon) this, 1305, 5, -3, 0, 1083, -1, "", 1);// 857
			AddComplexComponent( (BaseAddon) this, 1305, 6, -4, 0, 1083, -1, "", 1);// 858
			AddComplexComponent( (BaseAddon) this, 1305, 6, -3, 0, 1083, -1, "", 1);// 859
			AddComplexComponent( (BaseAddon) this, 1305, 7, -4, 0, 1083, -1, "", 1);// 860
			AddComplexComponent( (BaseAddon) this, 1305, 7, -3, 0, 1083, -1, "", 1);// 861
			AddComplexComponent( (BaseAddon) this, 1305, 8, -4, 0, 1083, -1, "", 1);// 862
			AddComplexComponent( (BaseAddon) this, 1305, 8, -3, 0, 1083, -1, "", 1);// 863
			AddComplexComponent( (BaseAddon) this, 1305, 9, -4, 0, 1083, -1, "", 1);// 864
			AddComplexComponent( (BaseAddon) this, 1305, 9, -3, 0, 1083, -1, "", 1);// 865
			AddComplexComponent( (BaseAddon) this, 1305, 10, -5, 0, 1083, -1, "", 1);// 866
			AddComplexComponent( (BaseAddon) this, 1305, 10, -4, 0, 1083, -1, "", 1);// 867
			AddComplexComponent( (BaseAddon) this, 1305, 10, -3, 0, 1083, -1, "", 1);// 868
			AddComplexComponent( (BaseAddon) this, 1822, 11, -5, 0, 1083, -1, "", 1);// 869
			AddComplexComponent( (BaseAddon) this, 1822, 11, -4, 0, 1083, -1, "", 1);// 870
			AddComplexComponent( (BaseAddon) this, 1822, 11, -3, 0, 1083, -1, "", 1);// 871
			AddComplexComponent( (BaseAddon) this, 1822, 1, -6, 0, 1083, -1, "", 1);// 872
			AddComplexComponent( (BaseAddon) this, 1822, 2, -6, 0, 1083, -1, "", 1);// 873
			AddComplexComponent( (BaseAddon) this, 1822, 3, -6, 0, 1083, -1, "", 1);// 874
			AddComplexComponent( (BaseAddon) this, 1822, 4, -6, 0, 1083, -1, "", 1);// 875
			AddComplexComponent( (BaseAddon) this, 1822, 5, -6, 0, 1083, -1, "", 1);// 876
			AddComplexComponent( (BaseAddon) this, 1822, 6, -6, 0, 1083, -1, "", 1);// 877
			AddComplexComponent( (BaseAddon) this, 1822, 7, -6, 0, 1083, -1, "", 1);// 878
			AddComplexComponent( (BaseAddon) this, 1822, 8, -6, 0, 1083, -1, "", 1);// 879
			AddComplexComponent( (BaseAddon) this, 1822, 9, -6, 0, 1083, -1, "", 1);// 880
			AddComplexComponent( (BaseAddon) this, 1822, 11, -6, 0, 1083, -1, "", 1);// 881
			AddComplexComponent( (BaseAddon) this, 1822, 1, -7, 0, 1083, -1, "", 1);// 882
			AddComplexComponent( (BaseAddon) this, 1822, 2, -7, 0, 1083, -1, "", 1);// 883
			AddComplexComponent( (BaseAddon) this, 1822, 3, -7, 0, 1083, -1, "", 1);// 884
			AddComplexComponent( (BaseAddon) this, 1822, 4, -7, 0, 1083, -1, "", 1);// 885
			AddComplexComponent( (BaseAddon) this, 1822, 5, -7, 0, 1083, -1, "", 1);// 886
			AddComplexComponent( (BaseAddon) this, 1822, 6, -7, 0, 1083, -1, "", 1);// 887
			AddComplexComponent( (BaseAddon) this, 1822, 7, -7, 0, 1083, -1, "", 1);// 888
			AddComplexComponent( (BaseAddon) this, 1822, 8, -7, 0, 1083, -1, "", 1);// 889
			AddComplexComponent( (BaseAddon) this, 1822, 9, -7, 0, 1083, -1, "", 1);// 890
			AddComplexComponent( (BaseAddon) this, 1822, 10, -7, 0, 1083, -1, "", 1);// 891
			AddComplexComponent( (BaseAddon) this, 1822, 11, -7, 0, 1083, -1, "", 1);// 892
			AddComplexComponent( (BaseAddon) this, 1822, 1, -8, 0, 1083, -1, "", 1);// 893
			AddComplexComponent( (BaseAddon) this, 1822, 2, -8, 0, 1083, -1, "", 1);// 894
			AddComplexComponent( (BaseAddon) this, 1822, 3, -8, 0, 1083, -1, "", 1);// 895
			AddComplexComponent( (BaseAddon) this, 1822, 4, -8, 0, 1083, -1, "", 1);// 896
			AddComplexComponent( (BaseAddon) this, 1822, 5, -8, 0, 1083, -1, "", 1);// 897
			AddComplexComponent( (BaseAddon) this, 1822, 6, -8, 0, 1083, -1, "", 1);// 898
			AddComplexComponent( (BaseAddon) this, 1822, 7, -8, 0, 1083, -1, "", 1);// 899
			AddComplexComponent( (BaseAddon) this, 1822, 8, -8, 0, 1083, -1, "", 1);// 900
			AddComplexComponent( (BaseAddon) this, 1822, 9, -8, 0, 1083, -1, "", 1);// 901
			AddComplexComponent( (BaseAddon) this, 1822, 10, -8, 0, 1083, -1, "", 1);// 902
			AddComplexComponent( (BaseAddon) this, 1822, 11, -8, 0, 1083, -1, "", 1);// 903
			AddComplexComponent( (BaseAddon) this, 1822, 1, -8, 5, 1083, -1, "", 1);// 904
			AddComplexComponent( (BaseAddon) this, 1822, 2, -8, 5, 1083, -1, "", 1);// 905
			AddComplexComponent( (BaseAddon) this, 1822, 3, -8, 5, 1083, -1, "", 1);// 906
			AddComplexComponent( (BaseAddon) this, 1822, 4, -8, 5, 1083, -1, "", 1);// 907
			AddComplexComponent( (BaseAddon) this, 1822, 5, -8, 5, 1083, -1, "", 1);// 908
			AddComplexComponent( (BaseAddon) this, 1822, 6, -8, 5, 1083, -1, "", 1);// 909
			AddComplexComponent( (BaseAddon) this, 1822, 7, -8, 5, 1083, -1, "", 1);// 910
			AddComplexComponent( (BaseAddon) this, 1822, 8, -8, 5, 1083, -1, "", 1);// 911
			AddComplexComponent( (BaseAddon) this, 1822, 9, -8, 5, 1083, -1, "", 1);// 912
			AddComplexComponent( (BaseAddon) this, 1822, 10, -8, 5, 1083, -1, "", 1);// 913
			AddComplexComponent( (BaseAddon) this, 1822, 11, -8, 5, 1083, -1, "", 1);// 914
			AddComplexComponent( (BaseAddon) this, 1823, 10, -6, 0, 1083, -1, "", 1);// 915
			AddComplexComponent( (BaseAddon) this, 1822, 1, -7, 5, 1083, -1, "", 1);// 916
			AddComplexComponent( (BaseAddon) this, 1822, 2, -7, 5, 1083, -1, "", 1);// 917
			AddComplexComponent( (BaseAddon) this, 1822, 3, -7, 5, 1083, -1, "", 1);// 918
			AddComplexComponent( (BaseAddon) this, 1822, 4, -7, 5, 1083, -1, "", 1);// 919
			AddComplexComponent( (BaseAddon) this, 1822, 5, -7, 5, 1083, -1, "", 1);// 920
			AddComplexComponent( (BaseAddon) this, 1822, 6, -7, 5, 1083, -1, "", 1);// 921
			AddComplexComponent( (BaseAddon) this, 1822, 7, -7, 5, 1083, -1, "", 1);// 922
			AddComplexComponent( (BaseAddon) this, 1822, 8, -7, 5, 1083, -1, "", 1);// 923
			AddComplexComponent( (BaseAddon) this, 1822, 9, -7, 5, 1083, -1, "", 1);// 924
			AddComplexComponent( (BaseAddon) this, 1822, 1, -8, 10, 1083, -1, "", 1);// 925
			AddComplexComponent( (BaseAddon) this, 1822, 2, -8, 10, 1083, -1, "", 1);// 926
			AddComplexComponent( (BaseAddon) this, 1822, 3, -8, 10, 1083, -1, "", 1);// 927
			AddComplexComponent( (BaseAddon) this, 1822, 4, -8, 10, 1083, -1, "", 1);// 928
			AddComplexComponent( (BaseAddon) this, 1822, 5, -8, 10, 1083, -1, "", 1);// 929
			AddComplexComponent( (BaseAddon) this, 1822, 6, -8, 10, 1083, -1, "", 1);// 930
			AddComplexComponent( (BaseAddon) this, 1822, 7, -8, 10, 1083, -1, "", 1);// 931
			AddComplexComponent( (BaseAddon) this, 1822, 8, -8, 10, 1083, -1, "", 1);// 932
			AddComplexComponent( (BaseAddon) this, 1822, 9, -8, 10, 1083, -1, "", 1);// 933
			AddComplexComponent( (BaseAddon) this, 1823, 10, -7, 5, 1083, -1, "", 1);// 934
			AddComplexComponent( (BaseAddon) this, 131, 11, -8, 10, 1083, 1, "", 1);// 935
			AddComplexComponent( (BaseAddon) this, 4632, 1, -7, 10, 1096, -1, "", 1);// 936
			AddComplexComponent( (BaseAddon) this, 4632, 2, -7, 10, 2173, -1, "", 1);// 937
			AddComplexComponent( (BaseAddon) this, 4632, 4, -7, 10, 2173, -1, "", 1);// 938
			AddComplexComponent( (BaseAddon) this, 4632, 3, -7, 10, 1096, -1, "", 1);// 939
			AddComplexComponent( (BaseAddon) this, 4632, 5, -7, 10, 1096, -1, "", 1);// 940
			AddComplexComponent( (BaseAddon) this, 4632, 6, -7, 10, 2173, -1, "", 1);// 941
			AddComplexComponent( (BaseAddon) this, 4632, 8, -7, 10, 2173, -1, "", 1);// 942
			AddComplexComponent( (BaseAddon) this, 4632, 7, -7, 10, 1096, -1, "", 1);// 943
			AddComplexComponent( (BaseAddon) this, 4632, 9, -7, 10, 1096, -1, "", 1);// 944
			AddComplexComponent( (BaseAddon) this, 6477, 11, -8, 32, 0, -1, "DragonBrazier", 1);// 946
			AddComplexComponent( (BaseAddon) this, 1308, 9, 10, 0, 1083, -1, "", 1);// 1131
			AddComplexComponent( (BaseAddon) this, 1308, 1, -2, 0, 1083, -1, "", 1);// 1132
			AddComplexComponent( (BaseAddon) this, 1308, 1, -1, 0, 1083, -1, "", 1);// 1133
			AddComplexComponent( (BaseAddon) this, 1308, 1, 0, 0, 1083, -1, "", 1);// 1134
			AddComplexComponent( (BaseAddon) this, 1308, 1, 1, 0, 1083, -1, "", 1);// 1135
			AddComplexComponent( (BaseAddon) this, 1308, 1, 2, 0, 1083, -1, "", 1);// 1136
			AddComplexComponent( (BaseAddon) this, 1308, 1, 3, 0, 1083, -1, "", 1);// 1137
			AddComplexComponent( (BaseAddon) this, 1308, 1, 4, 0, 1083, -1, "", 1);// 1138
			AddComplexComponent( (BaseAddon) this, 1308, 1, 5, 0, 1083, -1, "", 1);// 1139
			AddComplexComponent( (BaseAddon) this, 1308, 1, 6, 0, 1083, -1, "", 1);// 1140
			AddComplexComponent( (BaseAddon) this, 1308, 1, 7, 0, 1083, -1, "", 1);// 1141
			AddComplexComponent( (BaseAddon) this, 1308, 1, 8, 0, 1083, -1, "", 1);// 1142
			AddComplexComponent( (BaseAddon) this, 1308, 1, 9, 0, 1083, -1, "", 1);// 1143
			AddComplexComponent( (BaseAddon) this, 1308, 1, 10, 0, 1083, -1, "", 1);// 1144
			AddComplexComponent( (BaseAddon) this, 1308, 2, -2, 0, 1083, -1, "", 1);// 1145
			AddComplexComponent( (BaseAddon) this, 1308, 2, -1, 0, 1083, -1, "", 1);// 1146
			AddComplexComponent( (BaseAddon) this, 1308, 2, 0, 0, 1083, -1, "", 1);// 1147
			AddComplexComponent( (BaseAddon) this, 1308, 2, 1, 0, 1083, -1, "", 1);// 1148
			AddComplexComponent( (BaseAddon) this, 1308, 2, 2, 0, 1083, -1, "", 1);// 1149
			AddComplexComponent( (BaseAddon) this, 1308, 2, 3, 0, 1083, -1, "", 1);// 1150
			AddComplexComponent( (BaseAddon) this, 1308, 2, 4, 0, 1083, -1, "", 1);// 1151
			AddComplexComponent( (BaseAddon) this, 1308, 2, 5, 0, 1083, -1, "", 1);// 1152
			AddComplexComponent( (BaseAddon) this, 1308, 2, 6, 0, 1083, -1, "", 1);// 1153
			AddComplexComponent( (BaseAddon) this, 1308, 2, 7, 0, 1083, -1, "", 1);// 1154
			AddComplexComponent( (BaseAddon) this, 1308, 2, 8, 0, 1083, -1, "", 1);// 1155
			AddComplexComponent( (BaseAddon) this, 1308, 2, 9, 0, 1083, -1, "", 1);// 1156
			AddComplexComponent( (BaseAddon) this, 1308, 2, 10, 0, 1083, -1, "", 1);// 1157
			AddComplexComponent( (BaseAddon) this, 1308, 3, -2, 0, 1083, -1, "", 1);// 1158
			AddComplexComponent( (BaseAddon) this, 1308, 3, -1, 0, 1083, -1, "", 1);// 1159
			AddComplexComponent( (BaseAddon) this, 1308, 3, 0, 0, 1083, -1, "", 1);// 1160
			AddComplexComponent( (BaseAddon) this, 1308, 3, 1, 0, 1083, -1, "", 1);// 1161
			AddComplexComponent( (BaseAddon) this, 1308, 3, 2, 0, 1083, -1, "", 1);// 1162
			AddComplexComponent( (BaseAddon) this, 1308, 3, 3, 0, 1083, -1, "", 1);// 1163
			AddComplexComponent( (BaseAddon) this, 1308, 3, 4, 0, 1083, -1, "", 1);// 1164
			AddComplexComponent( (BaseAddon) this, 1308, 3, 5, 0, 1083, -1, "", 1);// 1165
			AddComplexComponent( (BaseAddon) this, 1308, 3, 6, 0, 1083, -1, "", 1);// 1166
			AddComplexComponent( (BaseAddon) this, 1308, 3, 7, 0, 1083, -1, "", 1);// 1167
			AddComplexComponent( (BaseAddon) this, 1308, 3, 8, 0, 1083, -1, "", 1);// 1168
			AddComplexComponent( (BaseAddon) this, 1308, 3, 9, 0, 1083, -1, "", 1);// 1169
			AddComplexComponent( (BaseAddon) this, 1308, 3, 10, 0, 1083, -1, "", 1);// 1170
			AddComplexComponent( (BaseAddon) this, 1308, 4, -2, 0, 1083, -1, "", 1);// 1171
			AddComplexComponent( (BaseAddon) this, 1308, 4, -1, 0, 1083, -1, "", 1);// 1172
			AddComplexComponent( (BaseAddon) this, 1308, 4, 0, 0, 1083, -1, "", 1);// 1173
			AddComplexComponent( (BaseAddon) this, 1308, 4, 1, 0, 1083, -1, "", 1);// 1174
			AddComplexComponent( (BaseAddon) this, 1308, 4, 2, 0, 1083, -1, "", 1);// 1175
			AddComplexComponent( (BaseAddon) this, 1308, 4, 3, 0, 1083, -1, "", 1);// 1176
			AddComplexComponent( (BaseAddon) this, 1308, 4, 4, 0, 1083, -1, "", 1);// 1177
			AddComplexComponent( (BaseAddon) this, 1308, 4, 5, 0, 1083, -1, "", 1);// 1178
			AddComplexComponent( (BaseAddon) this, 1308, 4, 6, 0, 1083, -1, "", 1);// 1179
			AddComplexComponent( (BaseAddon) this, 1308, 4, 7, 0, 1083, -1, "", 1);// 1180
			AddComplexComponent( (BaseAddon) this, 1308, 4, 8, 0, 1083, -1, "", 1);// 1181
			AddComplexComponent( (BaseAddon) this, 1308, 4, 9, 0, 1083, -1, "", 1);// 1182
			AddComplexComponent( (BaseAddon) this, 1308, 4, 10, 0, 1083, -1, "", 1);// 1183
			AddComplexComponent( (BaseAddon) this, 1308, 5, -2, 0, 1083, -1, "", 1);// 1184
			AddComplexComponent( (BaseAddon) this, 1308, 5, -1, 0, 1083, -1, "", 1);// 1185
			AddComplexComponent( (BaseAddon) this, 1308, 5, 0, 0, 1083, -1, "", 1);// 1186
			AddComplexComponent( (BaseAddon) this, 1308, 5, 1, 0, 1083, -1, "", 1);// 1187
			AddComplexComponent( (BaseAddon) this, 1308, 5, 2, 0, 1083, -1, "", 1);// 1188
			AddComplexComponent( (BaseAddon) this, 1308, 5, 3, 0, 1083, -1, "", 1);// 1189
			AddComplexComponent( (BaseAddon) this, 1308, 5, 4, 0, 1083, -1, "", 1);// 1190
			AddComplexComponent( (BaseAddon) this, 1308, 5, 5, 0, 1083, -1, "", 1);// 1191
			AddComplexComponent( (BaseAddon) this, 1308, 5, 6, 0, 1083, -1, "", 1);// 1192
			AddComplexComponent( (BaseAddon) this, 1308, 5, 7, 0, 1083, -1, "", 1);// 1193
			AddComplexComponent( (BaseAddon) this, 1308, 5, 8, 0, 1083, -1, "", 1);// 1194
			AddComplexComponent( (BaseAddon) this, 1308, 5, 9, 0, 1083, -1, "", 1);// 1195
			AddComplexComponent( (BaseAddon) this, 1308, 5, 10, 0, 1083, -1, "", 1);// 1196
			AddComplexComponent( (BaseAddon) this, 1308, 6, -2, 0, 1083, -1, "", 1);// 1197
			AddComplexComponent( (BaseAddon) this, 1308, 6, -1, 0, 1083, -1, "", 1);// 1198
			AddComplexComponent( (BaseAddon) this, 1308, 6, 0, 0, 1083, -1, "", 1);// 1199
			AddComplexComponent( (BaseAddon) this, 1308, 6, 1, 0, 1083, -1, "", 1);// 1200
			AddComplexComponent( (BaseAddon) this, 1308, 6, 2, 0, 1083, -1, "", 1);// 1201
			AddComplexComponent( (BaseAddon) this, 1308, 6, 3, 0, 1083, -1, "", 1);// 1202
			AddComplexComponent( (BaseAddon) this, 1308, 6, 4, 0, 1083, -1, "", 1);// 1203
			AddComplexComponent( (BaseAddon) this, 1308, 6, 5, 0, 1083, -1, "", 1);// 1204
			AddComplexComponent( (BaseAddon) this, 1308, 6, 6, 0, 1083, -1, "", 1);// 1205
			AddComplexComponent( (BaseAddon) this, 1308, 6, 7, 0, 1083, -1, "", 1);// 1206
			AddComplexComponent( (BaseAddon) this, 1308, 6, 8, 0, 1083, -1, "", 1);// 1207
			AddComplexComponent( (BaseAddon) this, 1308, 6, 9, 0, 1083, -1, "", 1);// 1208
			AddComplexComponent( (BaseAddon) this, 1308, 6, 10, 0, 1083, -1, "", 1);// 1209
			AddComplexComponent( (BaseAddon) this, 1308, 7, -2, 0, 1083, -1, "", 1);// 1210
			AddComplexComponent( (BaseAddon) this, 1308, 7, -1, 0, 1083, -1, "", 1);// 1211
			AddComplexComponent( (BaseAddon) this, 1308, 7, 0, 0, 1083, -1, "", 1);// 1212
			AddComplexComponent( (BaseAddon) this, 1308, 7, 1, 0, 1083, -1, "", 1);// 1213
			AddComplexComponent( (BaseAddon) this, 1308, 7, 2, 0, 1083, -1, "", 1);// 1214
			AddComplexComponent( (BaseAddon) this, 1308, 7, 3, 0, 1083, -1, "", 1);// 1215
			AddComplexComponent( (BaseAddon) this, 1308, 7, 4, 0, 1083, -1, "", 1);// 1216
			AddComplexComponent( (BaseAddon) this, 1308, 7, 5, 0, 1083, -1, "", 1);// 1217
			AddComplexComponent( (BaseAddon) this, 1308, 7, 6, 0, 1083, -1, "", 1);// 1218
			AddComplexComponent( (BaseAddon) this, 1308, 7, 7, 0, 1083, -1, "", 1);// 1219
			AddComplexComponent( (BaseAddon) this, 1308, 7, 8, 0, 1083, -1, "", 1);// 1220
			AddComplexComponent( (BaseAddon) this, 1308, 7, 9, 0, 1083, -1, "", 1);// 1221
			AddComplexComponent( (BaseAddon) this, 1308, 7, 10, 0, 1083, -1, "", 1);// 1222
			AddComplexComponent( (BaseAddon) this, 1308, 8, -2, 0, 1083, -1, "", 1);// 1223
			AddComplexComponent( (BaseAddon) this, 1308, 8, -1, 0, 1083, -1, "", 1);// 1224
			AddComplexComponent( (BaseAddon) this, 1308, 8, 0, 0, 1083, -1, "", 1);// 1225
			AddComplexComponent( (BaseAddon) this, 1308, 8, 1, 0, 1083, -1, "", 1);// 1226
			AddComplexComponent( (BaseAddon) this, 1308, 8, 2, 0, 1083, -1, "", 1);// 1227
			AddComplexComponent( (BaseAddon) this, 1308, 8, 3, 0, 1083, -1, "", 1);// 1228
			AddComplexComponent( (BaseAddon) this, 1308, 8, 4, 0, 1083, -1, "", 1);// 1229
			AddComplexComponent( (BaseAddon) this, 1308, 8, 5, 0, 1083, -1, "", 1);// 1230
			AddComplexComponent( (BaseAddon) this, 1308, 8, 6, 0, 1083, -1, "", 1);// 1231
			AddComplexComponent( (BaseAddon) this, 1308, 8, 7, 0, 1083, -1, "", 1);// 1232
			AddComplexComponent( (BaseAddon) this, 1308, 8, 8, 0, 1083, -1, "", 1);// 1233
			AddComplexComponent( (BaseAddon) this, 1308, 8, 9, 0, 1083, -1, "", 1);// 1234
			AddComplexComponent( (BaseAddon) this, 1308, 8, 10, 0, 1083, -1, "", 1);// 1235
			AddComplexComponent( (BaseAddon) this, 1308, 9, -2, 0, 1083, -1, "", 1);// 1236
			AddComplexComponent( (BaseAddon) this, 1308, 9, -1, 0, 1083, -1, "", 1);// 1237
			AddComplexComponent( (BaseAddon) this, 1308, 9, 0, 0, 1083, -1, "", 1);// 1238
			AddComplexComponent( (BaseAddon) this, 1308, 9, 1, 0, 1083, -1, "", 1);// 1239
			AddComplexComponent( (BaseAddon) this, 1308, 9, 2, 0, 1083, -1, "", 1);// 1240
			AddComplexComponent( (BaseAddon) this, 1308, 9, 3, 0, 1083, -1, "", 1);// 1241
			AddComplexComponent( (BaseAddon) this, 1308, 9, 4, 0, 1083, -1, "", 1);// 1242
			AddComplexComponent( (BaseAddon) this, 1308, 9, 5, 0, 1083, -1, "", 1);// 1243
			AddComplexComponent( (BaseAddon) this, 1308, 9, 6, 0, 1083, -1, "", 1);// 1244
			AddComplexComponent( (BaseAddon) this, 1308, 9, 7, 0, 1083, -1, "", 1);// 1245
			AddComplexComponent( (BaseAddon) this, 1308, 9, 8, 0, 1083, -1, "", 1);// 1246
			AddComplexComponent( (BaseAddon) this, 1308, 9, 9, 0, 1083, -1, "", 1);// 1247
			AddComplexComponent( (BaseAddon) this, 1308, 9, 10, 0, 1083, -1, "", 1);// 1248
			AddComplexComponent( (BaseAddon) this, 1305, 1, -2, 0, 1083, -1, "", 1);// 1249
			AddComplexComponent( (BaseAddon) this, 1305, 1, -1, 0, 1083, -1, "", 1);// 1250
			AddComplexComponent( (BaseAddon) this, 1305, 1, 0, 0, 1083, -1, "", 1);// 1251
			AddComplexComponent( (BaseAddon) this, 1305, 1, 1, 0, 1083, -1, "", 1);// 1252
			AddComplexComponent( (BaseAddon) this, 1305, 1, 2, 0, 1083, -1, "", 1);// 1253
			AddComplexComponent( (BaseAddon) this, 1305, 1, 3, 0, 1083, -1, "", 1);// 1254
			AddComplexComponent( (BaseAddon) this, 1305, 1, 4, 0, 1083, -1, "", 1);// 1255
			AddComplexComponent( (BaseAddon) this, 1305, 1, 5, 0, 1083, -1, "", 1);// 1256
			AddComplexComponent( (BaseAddon) this, 1305, 1, 6, 0, 1083, -1, "", 1);// 1257
			AddComplexComponent( (BaseAddon) this, 1305, 1, 7, 0, 1083, -1, "", 1);// 1258
			AddComplexComponent( (BaseAddon) this, 1305, 1, 8, 0, 1083, -1, "", 1);// 1259
			AddComplexComponent( (BaseAddon) this, 1305, 1, 9, 0, 1083, -1, "", 1);// 1260
			AddComplexComponent( (BaseAddon) this, 1305, 1, 10, 0, 1083, -1, "", 1);// 1261
			AddComplexComponent( (BaseAddon) this, 1305, 2, -2, 0, 1083, -1, "", 1);// 1262
			AddComplexComponent( (BaseAddon) this, 1305, 2, -1, 0, 1083, -1, "", 1);// 1263
			AddComplexComponent( (BaseAddon) this, 1305, 2, 0, 0, 1083, -1, "", 1);// 1264
			AddComplexComponent( (BaseAddon) this, 1305, 2, 1, 0, 1083, -1, "", 1);// 1265
			AddComplexComponent( (BaseAddon) this, 1305, 2, 2, 0, 1083, -1, "", 1);// 1266
			AddComplexComponent( (BaseAddon) this, 1305, 2, 3, 0, 1083, -1, "", 1);// 1267
			AddComplexComponent( (BaseAddon) this, 1305, 2, 4, 0, 1083, -1, "", 1);// 1268
			AddComplexComponent( (BaseAddon) this, 1305, 2, 5, 0, 1083, -1, "", 1);// 1269
			AddComplexComponent( (BaseAddon) this, 1305, 2, 6, 0, 1083, -1, "", 1);// 1270
			AddComplexComponent( (BaseAddon) this, 1305, 2, 7, 0, 1083, -1, "", 1);// 1271
			AddComplexComponent( (BaseAddon) this, 1305, 2, 8, 0, 1083, -1, "", 1);// 1272
			AddComplexComponent( (BaseAddon) this, 1305, 2, 9, 0, 1083, -1, "", 1);// 1273
			AddComplexComponent( (BaseAddon) this, 1305, 2, 10, 0, 1083, -1, "", 1);// 1274
			AddComplexComponent( (BaseAddon) this, 1305, 3, -2, 0, 1083, -1, "", 1);// 1275
			AddComplexComponent( (BaseAddon) this, 1305, 3, -1, 0, 1083, -1, "", 1);// 1276
			AddComplexComponent( (BaseAddon) this, 1305, 3, 0, 0, 1083, -1, "", 1);// 1277
			AddComplexComponent( (BaseAddon) this, 1305, 3, 1, 0, 1083, -1, "", 1);// 1278
			AddComplexComponent( (BaseAddon) this, 1305, 3, 2, 0, 1083, -1, "", 1);// 1279
			AddComplexComponent( (BaseAddon) this, 1305, 3, 3, 0, 1083, -1, "", 1);// 1280
			AddComplexComponent( (BaseAddon) this, 1305, 3, 4, 0, 1083, -1, "", 1);// 1281
			AddComplexComponent( (BaseAddon) this, 1305, 3, 5, 0, 1083, -1, "", 1);// 1282
			AddComplexComponent( (BaseAddon) this, 1305, 3, 6, 0, 1083, -1, "", 1);// 1283
			AddComplexComponent( (BaseAddon) this, 1305, 3, 7, 0, 1083, -1, "", 1);// 1284
			AddComplexComponent( (BaseAddon) this, 1305, 3, 8, 0, 1083, -1, "", 1);// 1285
			AddComplexComponent( (BaseAddon) this, 1305, 3, 9, 0, 1083, -1, "", 1);// 1286
			AddComplexComponent( (BaseAddon) this, 1305, 3, 10, 0, 1083, -1, "", 1);// 1287
			AddComplexComponent( (BaseAddon) this, 1305, 4, -2, 0, 1083, -1, "", 1);// 1288
			AddComplexComponent( (BaseAddon) this, 1305, 4, -1, 0, 1083, -1, "", 1);// 1289
			AddComplexComponent( (BaseAddon) this, 1305, 4, 0, 0, 1083, -1, "", 1);// 1290
			AddComplexComponent( (BaseAddon) this, 1305, 4, 1, 0, 1083, -1, "", 1);// 1291
			AddComplexComponent( (BaseAddon) this, 1305, 4, 2, 0, 1083, -1, "", 1);// 1292
			AddComplexComponent( (BaseAddon) this, 1305, 4, 3, 0, 1083, -1, "", 1);// 1293
			AddComplexComponent( (BaseAddon) this, 1305, 4, 4, 0, 1083, -1, "", 1);// 1294
			AddComplexComponent( (BaseAddon) this, 1305, 4, 5, 0, 1083, -1, "", 1);// 1295
			AddComplexComponent( (BaseAddon) this, 1305, 4, 6, 0, 1083, -1, "", 1);// 1296
			AddComplexComponent( (BaseAddon) this, 1305, 4, 7, 0, 1083, -1, "", 1);// 1297
			AddComplexComponent( (BaseAddon) this, 1305, 4, 8, 0, 1083, -1, "", 1);// 1298
			AddComplexComponent( (BaseAddon) this, 1305, 4, 9, 0, 1083, -1, "", 1);// 1299
			AddComplexComponent( (BaseAddon) this, 1305, 4, 10, 0, 1083, -1, "", 1);// 1300
			AddComplexComponent( (BaseAddon) this, 1305, 5, -2, 0, 1083, -1, "", 1);// 1301
			AddComplexComponent( (BaseAddon) this, 1305, 5, -1, 0, 1083, -1, "", 1);// 1302
			AddComplexComponent( (BaseAddon) this, 1305, 5, 0, 0, 1083, -1, "", 1);// 1303
			AddComplexComponent( (BaseAddon) this, 1305, 5, 1, 0, 1083, -1, "", 1);// 1304
			AddComplexComponent( (BaseAddon) this, 1305, 5, 2, 0, 1083, -1, "", 1);// 1305
			AddComplexComponent( (BaseAddon) this, 1305, 5, 3, 0, 1083, -1, "", 1);// 1306
			AddComplexComponent( (BaseAddon) this, 1305, 5, 4, 0, 1083, -1, "", 1);// 1307
			AddComplexComponent( (BaseAddon) this, 1305, 5, 5, 0, 1083, -1, "", 1);// 1308
			AddComplexComponent( (BaseAddon) this, 1305, 5, 6, 0, 1083, -1, "", 1);// 1309
			AddComplexComponent( (BaseAddon) this, 1305, 5, 7, 0, 1083, -1, "", 1);// 1310
			AddComplexComponent( (BaseAddon) this, 1305, 5, 8, 0, 1083, -1, "", 1);// 1311
			AddComplexComponent( (BaseAddon) this, 1305, 5, 9, 0, 1083, -1, "", 1);// 1312
			AddComplexComponent( (BaseAddon) this, 1305, 5, 10, 0, 1083, -1, "", 1);// 1313
			AddComplexComponent( (BaseAddon) this, 1305, 6, -2, 0, 1083, -1, "", 1);// 1314
			AddComplexComponent( (BaseAddon) this, 1305, 6, -1, 0, 1083, -1, "", 1);// 1315
			AddComplexComponent( (BaseAddon) this, 1305, 6, 0, 0, 1083, -1, "", 1);// 1316
			AddComplexComponent( (BaseAddon) this, 1305, 6, 1, 0, 1083, -1, "", 1);// 1317
			AddComplexComponent( (BaseAddon) this, 1305, 6, 2, 0, 1083, -1, "", 1);// 1318
			AddComplexComponent( (BaseAddon) this, 1305, 6, 3, 0, 1083, -1, "", 1);// 1319
			AddComplexComponent( (BaseAddon) this, 1305, 6, 4, 0, 1083, -1, "", 1);// 1320
			AddComplexComponent( (BaseAddon) this, 1305, 6, 5, 0, 1083, -1, "", 1);// 1321
			AddComplexComponent( (BaseAddon) this, 1305, 6, 6, 0, 1083, -1, "", 1);// 1322
			AddComplexComponent( (BaseAddon) this, 1305, 6, 7, 0, 1083, -1, "", 1);// 1323
			AddComplexComponent( (BaseAddon) this, 1305, 6, 8, 0, 1083, -1, "", 1);// 1324
			AddComplexComponent( (BaseAddon) this, 1305, 6, 9, 0, 1083, -1, "", 1);// 1325
			AddComplexComponent( (BaseAddon) this, 1305, 6, 10, 0, 1083, -1, "", 1);// 1326
			AddComplexComponent( (BaseAddon) this, 1305, 7, -2, 0, 1083, -1, "", 1);// 1327
			AddComplexComponent( (BaseAddon) this, 1305, 7, -1, 0, 1083, -1, "", 1);// 1328
			AddComplexComponent( (BaseAddon) this, 1305, 7, 0, 0, 1083, -1, "", 1);// 1329
			AddComplexComponent( (BaseAddon) this, 1305, 7, 1, 0, 1083, -1, "", 1);// 1330
			AddComplexComponent( (BaseAddon) this, 1305, 7, 2, 0, 1083, -1, "", 1);// 1331
			AddComplexComponent( (BaseAddon) this, 1305, 7, 3, 0, 1083, -1, "", 1);// 1332
			AddComplexComponent( (BaseAddon) this, 1305, 7, 4, 0, 1083, -1, "", 1);// 1333
			AddComplexComponent( (BaseAddon) this, 1305, 7, 5, 0, 1083, -1, "", 1);// 1334
			AddComplexComponent( (BaseAddon) this, 1305, 7, 6, 0, 1083, -1, "", 1);// 1335
			AddComplexComponent( (BaseAddon) this, 1305, 7, 7, 0, 1083, -1, "", 1);// 1336
			AddComplexComponent( (BaseAddon) this, 1305, 7, 8, 0, 1083, -1, "", 1);// 1337
			AddComplexComponent( (BaseAddon) this, 1305, 7, 9, 0, 1083, -1, "", 1);// 1338
			AddComplexComponent( (BaseAddon) this, 1305, 7, 10, 0, 1083, -1, "", 1);// 1339
			AddComplexComponent( (BaseAddon) this, 1305, 8, -2, 0, 1083, -1, "", 1);// 1340
			AddComplexComponent( (BaseAddon) this, 1305, 8, -1, 0, 1083, -1, "", 1);// 1341
			AddComplexComponent( (BaseAddon) this, 1305, 8, 0, 0, 1083, -1, "", 1);// 1342
			AddComplexComponent( (BaseAddon) this, 1305, 8, 1, 0, 1083, -1, "", 1);// 1343
			AddComplexComponent( (BaseAddon) this, 1305, 8, 2, 0, 2174, -1, "", 1);// 1344
			AddComplexComponent( (BaseAddon) this, 1305, 8, 3, 0, 2174, -1, "", 1);// 1345
			AddComplexComponent( (BaseAddon) this, 1305, 8, 4, 0, 1083, -1, "", 1);// 1346
			AddComplexComponent( (BaseAddon) this, 1305, 8, 5, 0, 1083, -1, "", 1);// 1347
			AddComplexComponent( (BaseAddon) this, 1305, 8, 6, 0, 1083, -1, "", 1);// 1348
			AddComplexComponent( (BaseAddon) this, 1305, 8, 7, 0, 1083, -1, "", 1);// 1349
			AddComplexComponent( (BaseAddon) this, 1305, 8, 8, 0, 1083, -1, "", 1);// 1350
			AddComplexComponent( (BaseAddon) this, 1305, 8, 9, 0, 1083, -1, "", 1);// 1351
			AddComplexComponent( (BaseAddon) this, 1305, 8, 10, 0, 1083, -1, "", 1);// 1352
			AddComplexComponent( (BaseAddon) this, 1305, 9, -2, 0, 1083, -1, "", 1);// 1353
			AddComplexComponent( (BaseAddon) this, 1305, 9, -1, 0, 1083, -1, "", 1);// 1354
			AddComplexComponent( (BaseAddon) this, 1305, 9, 0, 0, 1083, -1, "", 1);// 1355
			AddComplexComponent( (BaseAddon) this, 1305, 9, 1, 0, 1083, -1, "", 1);// 1356
			AddComplexComponent( (BaseAddon) this, 1305, 9, 2, 0, 2174, -1, "", 1);// 1357
			AddComplexComponent( (BaseAddon) this, 1305, 9, 3, 0, 2174, -1, "", 1);// 1358
			AddComplexComponent( (BaseAddon) this, 1305, 9, 4, 0, 1083, -1, "", 1);// 1359
			AddComplexComponent( (BaseAddon) this, 1305, 9, 5, 0, 1083, -1, "", 1);// 1360
			AddComplexComponent( (BaseAddon) this, 1305, 9, 6, 0, 1083, -1, "", 1);// 1361
			AddComplexComponent( (BaseAddon) this, 1305, 9, 7, 0, 1083, -1, "", 1);// 1362
			AddComplexComponent( (BaseAddon) this, 1305, 9, 8, 0, 1083, -1, "", 1);// 1363
			AddComplexComponent( (BaseAddon) this, 1305, 9, 9, 0, 1083, -1, "", 1);// 1364
			AddComplexComponent( (BaseAddon) this, 1305, 9, 10, 0, 1083, -1, "", 1);// 1365
			AddComplexComponent( (BaseAddon) this, 1305, 10, -2, 0, 1083, -1, "", 1);// 1383
			AddComplexComponent( (BaseAddon) this, 1305, 10, -1, 0, 1083, -1, "", 1);// 1384
			AddComplexComponent( (BaseAddon) this, 1305, 10, 0, 0, 1083, -1, "", 1);// 1385
			AddComplexComponent( (BaseAddon) this, 1305, 10, 1, 0, 1083, -1, "", 1);// 1386
			AddComplexComponent( (BaseAddon) this, 1305, 10, 2, 0, 1083, -1, "", 1);// 1387
			AddComplexComponent( (BaseAddon) this, 1305, 10, 3, 0, 1083, -1, "", 1);// 1388
			AddComplexComponent( (BaseAddon) this, 1305, 10, 4, 0, 1083, -1, "", 1);// 1389
			AddComplexComponent( (BaseAddon) this, 1305, 10, 5, 0, 1083, -1, "", 1);// 1390
			AddComplexComponent( (BaseAddon) this, 1305, 10, 6, 0, 1083, -1, "", 1);// 1391
			AddComplexComponent( (BaseAddon) this, 1305, 10, 7, 0, 1083, -1, "", 1);// 1392
			AddComplexComponent( (BaseAddon) this, 1305, 10, 8, 0, 1083, -1, "", 1);// 1393
			AddComplexComponent( (BaseAddon) this, 1305, 10, 9, 0, 1083, -1, "", 1);// 1394
			AddComplexComponent( (BaseAddon) this, 1305, 10, 10, 0, 1083, -1, "", 1);// 1395
			AddComplexComponent( (BaseAddon) this, 1822, 11, -2, 0, 1083, -1, "", 1);// 1396
			AddComplexComponent( (BaseAddon) this, 1822, 11, -1, 0, 1083, -1, "", 1);// 1397
			AddComplexComponent( (BaseAddon) this, 1822, 11, 0, 0, 1083, -1, "", 1);// 1398
			AddComplexComponent( (BaseAddon) this, 1822, 11, 1, 0, 1083, -1, "", 1);// 1399
			AddComplexComponent( (BaseAddon) this, 1822, 11, 2, 0, 1083, -1, "", 1);// 1400
			AddComplexComponent( (BaseAddon) this, 1822, 11, 3, 0, 1083, -1, "", 1);// 1401
			AddComplexComponent( (BaseAddon) this, 1822, 11, 4, 0, 1083, -1, "", 1);// 1402
			AddComplexComponent( (BaseAddon) this, 1822, 11, 5, 0, 1083, -1, "", 1);// 1403
			AddComplexComponent( (BaseAddon) this, 1822, 11, 6, 0, 1083, -1, "", 1);// 1404
			AddComplexComponent( (BaseAddon) this, 1822, 11, 7, 0, 1083, -1, "", 1);// 1405
			AddComplexComponent( (BaseAddon) this, 1822, 11, 8, 0, 1083, -1, "", 1);// 1406
			AddComplexComponent( (BaseAddon) this, 1822, 11, 9, 0, 1083, -1, "", 1);// 1407
			AddComplexComponent( (BaseAddon) this, 1822, 11, 10, 0, 1083, -1, "", 1);// 1408
			AddComplexComponent( (BaseAddon) this, 1822, 2, 10, 0, 1083, -1, "", 1);// 1409
			AddComplexComponent( (BaseAddon) this, 1822, 3, 10, 0, 1083, -1, "", 1);// 1410
			AddComplexComponent( (BaseAddon) this, 1822, 4, 10, 0, 1083, -1, "", 1);// 1411
			AddComplexComponent( (BaseAddon) this, 1822, 5, 10, 0, 1083, -1, "", 1);// 1412
			AddComplexComponent( (BaseAddon) this, 1822, 6, 10, 0, 1083, -1, "", 1);// 1413
			AddComplexComponent( (BaseAddon) this, 1822, 7, 10, 0, 1083, -1, "", 1);// 1414
			AddComplexComponent( (BaseAddon) this, 1822, 8, 10, 0, 1083, -1, "", 1);// 1415
			AddComplexComponent( (BaseAddon) this, 1822, 9, 10, 0, 1083, -1, "", 1);// 1416
			AddComplexComponent( (BaseAddon) this, 1822, 10, 10, 0, 1083, -1, "", 1);// 1417
			AddComplexComponent( (BaseAddon) this, 4635, 9, 3, 0, 1096, -1, "", 1);// 1418
			AddComplexComponent( (BaseAddon) this, 4635, 9, 2, 0, 1096, -1, "", 1);// 1419
			AddComplexComponent( (BaseAddon) this, 131, 11, 10, 5, 1083, 1, "", 1);// 1420
			AddComplexComponent( (BaseAddon) this, 131, 2, 10, 5, 1083, 1, "", 1);// 1421
			AddComplexComponent( (BaseAddon) this, 6477, 2, 10, 27, 0, -1, "DragonBrazier", 1);// 1422
			AddComplexComponent( (BaseAddon) this, 6477, 11, 10, 27, 0, -1, "DragonBrazier", 1);// 1423

		}

		public pvp_arenaAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class pvp_arenaAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new pvp_arenaAddon();
			}
		}

		[Constructable]
		public pvp_arenaAddonDeed()
		{
			Name = "pvp_arena";
		}

		public pvp_arenaAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}