/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DragonLampAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DragonLampAddonDeed();
			}
		}

		[ Constructable ]
		public DragonLampAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 6477 );
			ac.Light = LightType.ArchedWindowEast;
			ac.Name = "LampShade";
			AddComponent( ac, 0, 0, 14 );
			ac = new AddonComponent( 2853 );
			AddComponent( ac, 0, 0, 0 );

		}

		public DragonLampAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DragonLampAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DragonLampAddon();
			}
		}

		[Constructable]
		public DragonLampAddonDeed()
		{
			Name = "DragonLamp";
		}

		public DragonLampAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}