
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LighthouseAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6835, 1, -2, 0}, {6838, 0, -2, 0}, {6841, 1, -2, 0}// 1	2	3	
			, {6841, -1, -3, 0}, {6842, -2, -3, 0}, {6843, -3, -3, 0}// 4	5	6	
			, {6844, -3, -2, 0}, {6862, -2, -2, 0}, {6863, -1, -2, 0}// 7	8	9	
			, {6820, -1, 3, 0}, {6821, 0, 3, 0}, {6822, 1, 3, 0}// 10	11	12	
			, {6823, 2, 3, 0}, {6824, 3, 3, 0}, {6825, 3, 2, 0}// 13	14	15	
			, {6826, 3, 1, 0}, {6827, 3, 0, 0}, {6828, 3, -1, 0}// 16	17	18	
			, {6829, 2, -1, 0}, {6832, 1, -1, 0}, {6845, -3, -1, 0}// 19	20	21	
			, {6846, -2, 0, 0}, {6849, -2, 1, 0}, {6852, -1, 2, 0}// 22	23	24	
			, {6855, -1, 1, 0}, {6858, -1, 0, 0}, {6859, -1, -1, 0}// 25	26	27	
			, {6860, 0, -1, 0}, {6861, -2, -1, 0}// 28	29	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LighthouseAddonDeed();
			}
		}

		[ Constructable ]
		public LighthouseAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 6864, 2, 2, 0, 0, 29, "", 1);// 30

		}

		public LighthouseAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LighthouseAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LighthouseAddon();
			}
		}

		[Constructable]
		public LighthouseAddonDeed()
		{
			Name = "Lighthouse";
		}

		public LighthouseAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}