
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace UOPTele
{
	public class UOPTeleAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {19507, 1, 0, 9}, {19508, 1, 1, 9}// 2	3	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new UOPTeleAddonDeed();
			}
		}

		[ Constructable ]
		public UOPTeleAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 19506, 1, -1, 9, 0, -1, "Screen", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1848, 0, 2, 9, 1083, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1848, 0, 2, 14, 1083, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1848, 0, 2, 19, 1083, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1848, 0, 1, 24, 1083, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1848, 0, -2, 9, 1083, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1848, 0, -2, 14, 1083, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1848, 0, -2, 19, 1083, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1848, 0, 0, 24, 1083, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1848, 0, 2, 24, 1083, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1848, 0, -1, 24, 1083, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1848, 0, -2, 24, 1083, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1301, 0, -2, 29, 1303, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1301, 0, -1, 29, 1303, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1301, 0, 0, 29, 1303, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1301, 0, 1, 29, 1303, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1301, 0, 2, 29, 1303, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1301, 0, -3, 29, 1303, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1301, 0, 3, 29, 1303, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1301, 0, -4, 29, 1303, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 1301, 0, 4, 29, 1303, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 7727, 1, 2, 9, 2199, -1, "speaker", 1);// 24
			AddComplexComponent( (BaseAddon) this, 7727, 1, 2, 0, 2199, -1, "Speaker", 1);// 25
			AddComplexComponent( (BaseAddon) this, 7727, 1, -2, 10, 2199, -1, "Speaker", 1);// 26
			AddComplexComponent( (BaseAddon) this, 7727, 1, -2, 0, 2199, -1, "speaker", 1);// 27
			AddComplexComponent( (BaseAddon) this, 5990, 0, 4, 9, 1, -1, "fishtank base", 1);// 28
			AddComplexComponent( (BaseAddon) this, 5992, 0, 4, 9, 1, -1, "fishtank base", 1);// 29
			AddComplexComponent( (BaseAddon) this, 5990, 0, 4, 10, 1, -1, "fishtank base", 1);// 30
			AddComplexComponent( (BaseAddon) this, 5992, 0, 4, 10, 1, -1, "fishtank base", 1);// 31
			AddComplexComponent( (BaseAddon) this, 5990, 0, 4, 11, 92, -1, "water", 1);// 32
			AddComplexComponent( (BaseAddon) this, 4846, 0, 4, 11, 92, 0, "water", 1);// 33
			AddComplexComponent( (BaseAddon) this, 5990, 0, 4, 12, 92, -1, "water", 1);// 34
			AddComplexComponent( (BaseAddon) this, 4846, 0, 4, 12, 92, 0, "water", 1);// 35
			AddComplexComponent( (BaseAddon) this, 5990, 0, 4, 13, 93, -1, "water", 1);// 36
			AddComplexComponent( (BaseAddon) this, 4846, 0, 4, 13, 93, 0, "water", 1);// 37
			AddComplexComponent( (BaseAddon) this, 5990, 0, 4, 14, 93, -1, "water", 1);// 38
			AddComplexComponent( (BaseAddon) this, 4846, 0, 4, 14, 93, 0, "water", 1);// 39
			AddComplexComponent( (BaseAddon) this, 5990, 0, 4, 15, 94, -1, "water", 1);// 40
			AddComplexComponent( (BaseAddon) this, 4846, 0, 4, 15, 94, 0, "water", 1);// 41
			AddComplexComponent( (BaseAddon) this, 5990, 0, 4, 16, 94, -1, "water", 1);// 42
			AddComplexComponent( (BaseAddon) this, 4846, 0, 4, 16, 94, 0, "water", 1);// 43
			AddComplexComponent( (BaseAddon) this, 5990, 0, 4, 17, 95, -1, "water", 1);// 44
			AddComplexComponent( (BaseAddon) this, 4846, 0, 4, 17, 95, 0, "water", 1);// 45
			AddComplexComponent( (BaseAddon) this, 4846, 0, 4, 18, 95, 0, "water", 1);// 46
			AddComplexComponent( (BaseAddon) this, 4846, 0, 4, 18, 95, 0, "water", 1);// 47
			AddComplexComponent( (BaseAddon) this, 4846, 0, 4, 19, 96, 0, "water", 1);// 48
			AddComplexComponent( (BaseAddon) this, 4846, 0, 4, 19, 96, 0, "water", 1);// 49
			AddComplexComponent( (BaseAddon) this, 4846, 0, 4, 20, 96, 0, "water", 1);// 50
			AddComplexComponent( (BaseAddon) this, 4846, 0, 4, 22, 1, 0, "fishtank lid", 1);// 51
			AddComplexComponent( (BaseAddon) this, 4846, 0, 4, 23, 1, 0, "fishtank lid", 1);// 52
			AddComplexComponent( (BaseAddon) this, 4846, 1, 5, 21, 348, 0, "sand", 1);// 53
			AddComplexComponent( (BaseAddon) this, 15102, 1, 5, 25, 0, -1, "a Blue Fish", 1);// 54
			AddComplexComponent( (BaseAddon) this, 5990, 0, -4, 9, 1, -1, "fishtank base", 1);// 55
			AddComplexComponent( (BaseAddon) this, 5992, 0, -4, 9, 1, -1, "fishtank base", 1);// 56
			AddComplexComponent( (BaseAddon) this, 5990, 0, -4, 10, 1, -1, "fishtank base", 1);// 57
			AddComplexComponent( (BaseAddon) this, 5992, 0, -4, 10, 1, -1, "fishtank base", 1);// 58
			AddComplexComponent( (BaseAddon) this, 5990, 0, -4, 11, 92, -1, "water", 1);// 59
			AddComplexComponent( (BaseAddon) this, 4846, 0, -4, 11, 92, 0, "water", 1);// 60
			AddComplexComponent( (BaseAddon) this, 5990, 0, -4, 12, 92, -1, "water", 1);// 61
			AddComplexComponent( (BaseAddon) this, 4846, 0, -4, 12, 92, 0, "water", 1);// 62
			AddComplexComponent( (BaseAddon) this, 5990, 0, -4, 13, 93, -1, "water", 1);// 63
			AddComplexComponent( (BaseAddon) this, 4846, 0, -4, 13, 93, 0, "water", 1);// 64
			AddComplexComponent( (BaseAddon) this, 5990, 0, -4, 14, 93, -1, "water", 1);// 65
			AddComplexComponent( (BaseAddon) this, 4846, 0, -4, 14, 93, 0, "water", 1);// 66
			AddComplexComponent( (BaseAddon) this, 5990, 0, -4, 15, 94, -1, "water", 1);// 67
			AddComplexComponent( (BaseAddon) this, 4846, 0, -4, 15, 94, 0, "water", 1);// 68
			AddComplexComponent( (BaseAddon) this, 5990, 0, -4, 16, 94, -1, "water", 1);// 69
			AddComplexComponent( (BaseAddon) this, 4846, 0, -4, 16, 94, 0, "water", 1);// 70
			AddComplexComponent( (BaseAddon) this, 5990, 0, -4, 17, 95, -1, "water", 1);// 71
			AddComplexComponent( (BaseAddon) this, 4846, 0, -4, 17, 95, 0, "water", 1);// 72
			AddComplexComponent( (BaseAddon) this, 4846, 0, -4, 18, 95, 0, "water", 1);// 73
			AddComplexComponent( (BaseAddon) this, 4846, 0, -4, 18, 95, 0, "water", 1);// 74
			AddComplexComponent( (BaseAddon) this, 4846, 0, -4, 19, 96, 0, "water", 1);// 75
			AddComplexComponent( (BaseAddon) this, 4846, 0, -4, 19, 96, 0, "water", 1);// 76
			AddComplexComponent( (BaseAddon) this, 4846, 0, -4, 20, 96, 0, "water", 1);// 77
			AddComplexComponent( (BaseAddon) this, 4846, 0, -4, 22, 1, 0, "fishtank lid", 1);// 78
			AddComplexComponent( (BaseAddon) this, 4846, 0, -4, 23, 1, 0, "fishtank lid", 1);// 79
			AddComplexComponent( (BaseAddon) this, 4846, 1, -3, 21, 348, 0, "sand", 1);// 80
			AddComplexComponent( (BaseAddon) this, 15102, 1, -3, 25, 0, -1, "a Blue Fish", 1);// 81
			AddComplexComponent( (BaseAddon) this, 1981, 0, -3, 9, 1096, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 1981, 0, 3, 9, 1096, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 1981, 0, 4, 23, 1096, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 1981, 0, 4, 25, 1096, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 1981, 0, 4, 27, 1096, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 1981, 0, -4, 23, 1096, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 1981, 0, -4, 25, 1096, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 1981, 0, -4, 27, 1096, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 3630, 0, 0, 29, 1366, 0, "UOP-TV", 1);// 90
			AddComplexComponent( (BaseAddon) this, 4145, 0, 3, 29, 1366, -1, "Remote", 1);// 91
			AddComplexComponent( (BaseAddon) this, 3834, 0, -2, 29, 1285, -1, "TV-Guide", 1);// 92

		}

		public UOPTeleAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class UOPTeleAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new UOPTeleAddon();
			}
		}

		[Constructable]
		public UOPTeleAddonDeed()
		{
			Name = "UOPTele";
		}

		public UOPTeleAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}