/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AquariumEAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AquariumEAddonDeed();
			}
		}

		[ Constructable ]
		public AquariumEAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 12386 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 12387 );
			AddComponent( ac, 0, 0, 0 );

		}

		public AquariumEAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AquariumEAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AquariumEAddon();
			}
		}

		[Constructable]
		public AquariumEAddonDeed()
		{
			Name = "AquariumE";
		}

		public AquariumEAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}